<a href="zapisy/add">Dodaj</a>
<table id="lista"  class="tablesorter"cellspacing="1" >
<thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>e-mail</th>
      <th>telefon</th>
      <th>utworzony</th>
      <th>R</th>
      <th> </th>
      </tr>
</thead>
<tbody> 
<?php
foreach($this->students as $student) {
    ?>
    <tr class="student">
        <td><?php echo $student->imie;?></td>
        <td><?php echo $student->nazwisko;?></td>
        <td><?php echo $student->email;?></td>
        <td><?php echo $student->telefon;?></td>
        <td><?php echo date("d-m-Y",strtotime( $student->created) );?></td>
        <td><?php echo $student->registered?'TAK':'NIE';?></td>
       <td>
       <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'zapisy', 'action' => 'edit')).'/'.$student->id?>">Edytuj</a>
       <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'zapisy', 'action' => 'delete')).'/'.$student->id?>">Usuń</a>
       </td>
       </tr>
    </tr><!--artykuł-->
    <?php
}
?>
    </tbody> 
</table>