<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OSK AUTO TURBO Grzegorz Pałasz</title>
        <meta name="robots" content="all, index, follow" /> 
        <meta name="description" content="OSK AUTO TURBO zaprasza na kursy PRAWA JAZDY kat. B w Rzeszowie. Wysoka zdawalność! Liczne PROMOCJE! Jazdy doszkalające: 1 godzina - 90 zł. Zapisz się już dziś! Tel.: 605 330 708, 693 776 163" />
        <meta name="keywords" content="prawo jazdy rzeszów, nauka jazdy rzeszów, kurs prawa jazdy rzeszów, prawo jazdy, nauka jazdy, nauka jazdy łańcut, prawo jazdy łańcut, kursy prawa jazdy, kurs prawa jazdy kat. B, ośrodek szkolenia kierowców, szkoła jazdy, szkoła nauki jazdy, osk auto turbo, auto turbo rzeszów, prawo jazdy w rzeszowie, jazdy doszkalające rzeszów, szkoła jazdy rzeszów, szkoła jazdy, kursy doszkalające rzeszów, prawo jazdy rzeszów cennik, kurs prawa jazdy cennik" />
        <meta name="type" content="descriptive" />
        <meta name="coverage" content="global" /> 
        <meta name="audience" content="all" />
        <meta name="classification" content="global,all" /> 
        <meta name="rating" content="general" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
        <!-- Favicon -->
        <link href="/img/favicon.ico" rel="shortcut icon" />
        
        <?php if (APPLICATION_ENV != 'development') { ?>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-31529993-1']);
            _gaq.push(['_trackPageview']); 
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        
        </script>
        <?php }?>
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"> <!--wercja z ikonka tiktoka-->
        
        <!-- Libraries Stylesheet -->
        <link href="lib/animate/animate.min.css" rel="stylesheet">
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        
        <!-- Customized Bootstrap Stylesheet -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        
        <!-- Template Stylesheet -->
        <link href="css/style.css" rel="stylesheet">
        <link href="css/turbo.css" rel="stylesheet">
    </head>
    
    <body>
    <?php
//        $this->dialogMessage = array();
//        $this->dialogMessage['title'] = 'ala';
//        $this->dialogMessage['text'] = array( 
//            'imie' => 'Marcin',
//            'nazwisko' => 'Wrona'
//        );
        echo $this->Message($this->dialogMessage);
//        if(isset($this->dialogMessage)){
//            echo $this->partial('partials/message.phtml', 'default',array('dialogMessage' => $this->dialogMessage));   
//        }
        ?>
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <?php //echo $this->partial('partials/wyloguj.phtml', 'admin') ?>
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="index.html" class="navbar-brand d-flex align-items-center px-2 px-lg-3">
                <img class="img-fluid" src="img/logo_auto_turbo.svg " alt="">
                <div class="navbar-brand_column flex-column">
                    <h2 class="m-0 text-primary">AUTO TURBO</h2>
                    <h6 class="m-0">Ośrodek Szolenia Kierowców</h6>
                </div>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <?php
                      echo $this->navigation()->menu()->setPartial(array('partials/menu.phtml', 'default'));
                    ?>
                </div>
                <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block"><i class="fa fa-phone-alt ms-3"></i>  Zadzwoń</a>
            </div>
        </nav>
        <!-- Navbar End -->
                <div>
                    <h1><?php echo $this->title; ?></h1>
                        <?php echo $this->layout()->content; ?>
                </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">AUTO TURBO</a>, Wszelkie prawa zastrzeżone.
    
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            <!--Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>-->
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="/#">O nas</a>
                                <a href="">Cookies</a>
                                <a href="">Pomoc</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
        </div>
        <!-- Footer End -->
    
    
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    
    
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/wow/wow.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    
        <!-- Template Javascript -->
        <script src="js/main.js"></script>
    </body>

</html>