<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OSK AUTO TURBO Grzegorz Pałasz</title>
        <meta name="robots" content="all, index, follow" /> 
        <meta name="description" content="OSK AUTO TURBO zaprasza na kursy PRAWA JAZDY kat. B w Rzeszowie. Wysoka zdawalność! Liczne PROMOCJE! Jazdy doszkalające: 1 godzina - 90 zł. Zapisz się już dziś! Tel.: 605 330 708, 693 776 163" />
        <meta name="keywords" content="prawo jazdy rzeszów, nauka jazdy rzeszów, kurs prawa jazdy rzeszów, prawo jazdy, nauka jazdy, nauka jazdy łańcut, prawo jazdy łańcut, kursy prawa jazdy, kurs prawa jazdy kat. B, ośrodek szkolenia kierowców, szkoła jazdy, szkoła nauki jazdy, osk auto turbo, auto turbo rzeszów, prawo jazdy w rzeszowie, jazdy doszkalające rzeszów, szkoła jazdy rzeszów, szkoła jazdy, kursy doszkalające rzeszów, prawo jazdy rzeszów cennik, kurs prawa jazdy cennik" />
        <meta name="type" content="descriptive" />
        <meta name="coverage" content="global" /> 
        <meta name="audience" content="all" />
        <meta name="classification" content="global,all" /> 
        <meta name="rating" content="general" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
        <!-- Favicon -->
        <link href="/img/favicon.ico" rel="shortcut icon" />
        
        <?php if (APPLICATION_ENV != 'development') { ?>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-31529993-1']);
            _gaq.push(['_trackPageview']); 
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        
        </script>
        <?php }?>
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"> <!--wercja z ikonka tiktoka-->
        
        <!-- Libraries Stylesheet -->
        <link href="/lib/animate/animate.min.css" rel="stylesheet">
        <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        
        <!-- Customized Bootstrap Stylesheet -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        
		<!-- Lightbox2 CSS -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/css/lightbox.min.css" rel="stylesheet" />
		
        <!-- Template Stylesheet -->
        <link href="/css/style.css" rel="stylesheet">
        <link href="/css/turbo.css?v=124" rel="stylesheet">
    </head>
    
    <body>
    <?php
//        $this->dialogMessage = array();
//        $this->dialogMessage['title'] = 'ala';
//        $this->dialogMessage['text'] = array( 
//            'imie' => 'Marcin',
//            'nazwisko' => 'Wrona'
//        );
        echo $this->Message($this->dialogMessage);
//        if(isset($this->dialogMessage)){
//            echo $this->partial('partials/message.phtml', 'default',array('dialogMessage' => $this->dialogMessage));   
//        }
        ?>
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <?php //echo $this->partial('partials/wyloguj.phtml', 'admin') ?>
        		
		

		
		
		
		<div class="container-fluid bg-dark text-light footer pt-0 wow fadeIn">
			<div class="container-fluid-padding-top py-2 m-0">
				<div class="d-flex justify-content-between align-items-center flex-column flex-md-row gap-3">

					<!-- Najbliższy kurs -->
					<div class="text-white d-flex align-items-center flex-wrap fs-6">
						
						<span class="me-2 fs-6"><i class="fa fa-arrow-right text-primary me-2"></i> Kurs:</span>
						<span class="me-2  fs-6"><i class="fa fa-calendar-day text-primary me-2"></i> 23.04.25 r. (śr.)</span>
						<span><i class="fa fa-clock text-primary me-2 fs-6"></i> 16:00</span>
						<!--
                        <span class="flex-fill text-center ms-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></span>
                   -->
					</div>
					<!-- Ikony społecznościowe -->
					<!--
					<div class="d-flex">
						<a class="btn btn-outline-light btn-social rounded-circle me-2" href="https://www.youtube.com/c/PrawojazdyAUTOTURBOGrzegorzPa%C5%82asz/videos">
							<i class="fab fa-youtube"></i>
						</a>
						<a class="btn btn-outline-light btn-social rounded-circle me-2" href="https://www.tiktok.com/@oskautoturbo">
							<i class="fab fa-tiktok"></i>
						</a>
						<a class="btn btn-outline-light btn-social rounded-circle me-2" href="https://www.facebook.com/prawojazdyautoturbo">
							<i class="fab fa-facebook-f"></i>
						</a>
						<a class="btn btn-outline-light btn-social rounded-circle" href="https://www.instagram.com/prawojazdyautoturbo">
							<i class="fab fa-instagram"></i>
						</a>
					</div>
					-->

				</div>
			</div>
		</div>




<!-- Navbar Start -->

		
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="/" class="navbar-brand d-flex align-items-center px-2 px-lg-3">
                <img class="img-fluid" src="/img/logo_auto_turbo.svg " alt="">
                <div class="navbar-brand_column flex-column">
                    <h1 class="naglowek-responsive-big text-primary m-0">AUTO TURBO</h1>
                    <h1 class="naglowek-responsive text-center">Ośrodek Szolenia Kierowców</h1>
                </div>
            </a>
            <button type="button" class="navbar-toggler me-0" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <?php
                      echo $this->navigation()->menu()->setPartial(array('partials/menu.phtml', 'default'));
                    ?>
                </div>
                <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block"><i class="fa fa-phone-alt ms-3"></i>  Zadzwoń</a>
            </div>
        </nav>
        <!-- Navbar End -->
               
			    <div>
                        <?php echo $this->layout()->content; ?>
                </div>
				
		<!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-2 wow fadeIn" data-wow-delay="0.1s">
			<div class="container-fluid-padding-top">
				<div class="container py-5">
					<div class="row g-5 pb-3">
					
						<!-- footer LINKI--- START--------------->
						<div class="col-lg-3 col-md-6">
							<h4 class="text-white mb-3">Linki</h4>
							<a class="btn btn-link" href="https://info-car.pl/new/prawo-jazdy/zapisz-sie-na-egzamin-na-prawo-jazdy">Zapisy na egzamin ON-LINE</a>
							<a class="btn btn-link" href="https://www.word.rzeszow.pl/">WORD Rzeszów</a>
							<a class="btn btn-link" href="https://info-car.pl/new/prawo-jazdy/sprawdz-status-prawa-jazdy">Odbiór prawa jazdy</a>
						</div>
						<!-- footer LINKI--END------------------->
						
						<!-- footer KONTAKT--- START--------------->
						<div class="col-lg-3 col-md-6">
							<h4 class="text-white mb-3">Kontakt</h4>
							<p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>35-005 Rzeszów, Bardowskiego 1C</p>
							<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>605 330 708, 693 776 163</p>
							<p class="mb-2"><i class="fa fa-envelope me-3"></i>oskautoturbo@gmail.com</p>
							<div class="d-flex pt-2">
								<a class="btn btn-outline-light btn-social" href="https://www.youtube.com/c/PrawojazdyAUTOTURBOGrzegorzPa%C5%82asz/videos"><i class="fab fa-youtube"></i></a>
								<a class="btn btn-outline-light btn-social" href="https://www.tiktok.com/@oskautoturbo"><i class="fab fa-tiktok"></i></a>
								<a class="btn btn-outline-light btn-social" href="https://www.facebook.com/prawojazdyautoturbo"><i class="fab fa-facebook-f"></i></a>
								<a class="btn btn-outline-light btn-social" href="https://www.instagram.com/prawojazdyautoturbo?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="><i class="fab fa-instagram"></i></a>
							</div>
						</div>
						<!-- footer KONTAKT--- END--------------->
						
						<!-- footer GALERIA--- START--------------->
						<div class="col-lg-3 col-md-6">
							<h4 class="text-white mb-3">Galeria</h4>
							<div class="row g-2 pt-2">
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_plac_manewrowy.jpg" alt="">
								</div>
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_sala_wykladowa.jpg" alt="">
								</div>
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_zdjecie_01.jpg" alt="">
								</div>
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_zdjecie_02.jpg" alt="">
								</div>
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_zdjecie_03.jpg" alt="">
								</div>
								<div class="col-4">
									<img class="img-fluid bg-light p-1" src="/img/galeria/auto_turbo_zdjecie_04.jpg" alt="">
								</div>
							</div>
						</div>
						<!-- footer GALERIA--- END--------------->
						
						<!-- footer OPINIE O NAS--- START--------------->
						<div class="col-lg-3 col-md-6">
							<h4 class="text-white mb-3">Opinie o nas</h4>
							<a class="btn btn-link" href="https://www.superprawojazdy.pl/osk-auto-turbo,9598.htm">Superprawojazdy.pl</a>
							<a class="btn btn-link" href="https://www.prawo-jazdy-360.pl/ranking-szkol-jazdy/osrodek-szkolenia-kierowcow-auto-turbo-grzegorz-palasz/rzeszow">prawojazdy360.pl</a>
							<a class="btn btn-link" href="https://g.co/kgs/QFkZTSm">Opinie Google</a>
							<a class="btn btn-link" href="https://www.facebook.com/prawojazdyautoturbo">Opinie Facebook</a>
				   
						</div>
						<!-- footer OPINIE O NAS--- END--------------->
						
					</div>	
					
					
					<div class="container">
						<div class="copyright">
							<div class="row">
								<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
									&copy; <a class="border-bottom" href="/">AUTO TURBO</a>, Wszelkie prawa zastrzeżone.
			
									<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
									<!--Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>-->
								</div>
								<div class="col-md-6 text-center text-md-end">
									<div class="footer-menu">
										<a href="/#dalczego_my">O nas</a>
										<!--<a href="">Cookies</a>
										<a href="">Pomoc</a>
										<a href="">FQAs</a>-->
										<a href="../doci/AUTO_TURBO_Polityka_prywatnosci.pdf">Polityka prywatności</a>
									</div>
								</div>
							</div>
						</div>
					</div> 
				
				
				
				
				</div>
			</div>
		</div>
        <!-- Footer End -->
    
    
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    
    
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/lib/wow/wow.min.js"></script>
        <script src="/lib/easing/easing.min.js"></script>
        <script src="/lib/waypoints/waypoints.min.js"></script>
        <script src="/lib/owlcarousel/owl.carousel.min.js"></script>
    
        <!-- Template Javascript -->
        <script src="/js/main.js"></script>
		
		<!-- Lightbox2 JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/js/lightbox.min.js"></script>
		
    </body>

</html>