<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_Student', 'doctrine');

/**
 * Application_Model_Base_Student
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $imie
 * @property string $nazwisko
 * @property integer $rodzaj_kursu
 * @property string $pesel
 * @property string $miejsce_urodzenia
 * @property string $obywatelstwo
 * @property string $adres_zamieszkania
 * @property string $email
 * @property string $telefon
 * @property string $uwagi
 * @property timestamp $created
 * @property bool $activated
 * @property bool $registered
 * @property string $link
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Application_Model_Base_Student extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('students');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('imie', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('nazwisko', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('rodzaj_kursu', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pesel', 'string', 11, array(
             'type' => 'string',
             'length' => '11',
             ));
        $this->hasColumn('miejsce_urodzenia', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('obywatelstwo', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('adres_zamieszkania', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('email', 'string', 70, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '70',
             ));
        $this->hasColumn('telefon', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('uwagi', 'string', 300, array(
             'type' => 'string',
             'length' => '300',
             ));
        $this->hasColumn('created', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('activated', 'bool', null, array(
             'type' => 'bool',
             'notnull' => true,
             ));
        $this->hasColumn('registered', 'bool', null, array(
             'type' => 'bool',
             'notnull' => true,
             ));
        $this->hasColumn('link', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '32',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}