<?php
$this->headLink()
        ->appendStylesheet('/css/forms.css');
$this->headScript()
        ->appendFile('/js/jquery.form.js')
        ->appendFile('/js/turbo.utils.js');
?>
<?php
 ?>
<form id="addGalery" method="post" action="<?php echo $this->gallery['save_url'] ?>">
    <div>
        <div class="element-group">
            <label><?php echo $this->gallery['add_label']; ?></label>
            <input  type="text" name="name_gallery" value="<?php echo $this->gallery['name']; ?>"/>
        </div>
        <input class="id_gallery" name="id_gallery" type="hidden" value="<?php echo $this->gallery['id']; ?>"/>
        <div class="submit-group">
            <input id="addGalerySubmit" type="submit" value="<?php echo $this->gallery['submit_label']; ?>" />
        </div>
       
    </div>
</form>
<?php
$this->headLink()
        ->appendStylesheet('/css/upload.gallery/jquery.fileupload-ui.css')
        ->appendStylesheet('/css/upload.gallery/bootstrap-image-gallery.min.css')
        ->appendStylesheet('/css/upload.gallery/bootstrap.min.css');
$this->headScript()
        ->appendFile('/js/upload.gallery/vendor/jquery.ui.widget.js')
        ->appendFile('/js/upload.gallery/tmpl.min.js')
        ->appendFile('/js/upload.gallery/load-image.min.js')
        ->appendFile('/js/upload.gallery/canvas-to-blob.min.js')
        ->appendFile('/js/upload.gallery/bootstrap.min.js')
        ->appendFile('/js/upload.gallery/bootstrap-image-gallery.min.js')
        ->appendFile('/js/upload.gallery/jquery.iframe-transport.js')
        ->appendFile('/js/upload.gallery/jquery.fileupload.js')
        ->appendFile('/js/upload.gallery/jquery.fileupload-process.js')
        ->appendFile('/js/upload.gallery/jquery.fileupload-resize.js')
        ->appendFile('/js/upload.gallery/jquery.fileupload-validate.js')
        ->appendFile('/js/upload.gallery/jquery.fileupload-ui.js');
?>


<form id="fileupload" action="<?php echo $this->gallery['upload_url']; ?>" method="POST" enctype="multipart/form-data">
    <!-- Redirect browsers with JavaScript disabled to the origin page -->
    <noscript><input type="hidden" name="redirect" value="http://blueimp.github.com/jQuery-File-Upload/"></noscript>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
        <div class="span7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="icon-plus icon-white"></i>
                <span>Add files...</span>
                <input type="file" name="files[]" multiple>
            </span>
            <button type="submit" class="btn btn-primary start">
                <i class="icon-upload icon-white"></i>
                <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
                <i class="icon-ban-circle icon-white"></i>
                <span>Cancel upload</span>
            </button>
            <button type="button" class="btn btn-danger delete">
                <i class="icon-trash icon-white"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" class="toggle">
            <!-- The loading indicator is shown during file processing -->
            <span class="fileupload-loading"></span>
        </div>
        <!-- The global progress information -->
        <div class="span5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="bar" style="width:0%;"></div>
            </div>
            <!-- The extended global progress information -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
</form>
<!--
<div id="modal-gallery" class="modal modal-gallery hide fade" data-filter=":odd" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Download</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Previous</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Next</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>-->
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            {% if (file.error) { %}
            <div><span class="label label-important">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <p class="size">{%=o.formatFileSize(file.size)%}</p>
            {% if (!o.files.error) { %}
            <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
            {% } %}
        </td>
        <td>
            {% if (!o.files.error && !i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start">
                <i class="icon-upload icon-white"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="icon-ban-circle icon-white"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span>
                {% if (file.thumbnail_url) { %}
                <a class="grouped_elements" rel="gallery" href="{%=file.url%}" title="{%=file.name%}" data-gallery="gallery" ><img src="{%=file.thumbnail_url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </p>
            {% if (file.error) { %}
            <div><span class="label label-important">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            <button class="btn btn-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.delete_with_credentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="icon-trash icon-white"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle">
        </td>
    </tr>
    {% } %}
</script>
<script type="text/javascript">
    $(function () {
        'use strict';

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: '<?php echo $this->gallery['upload_url'] ?>',
            previewAsCanvas : false
        });

        // Enable iframe cross-domain access via redirect option:
        /*
    $('#fileupload').fileupload(
        'option',
        'redirect',
        window.location.href.replace(
            /\/[^\/]*$/,
            '/cors/result.html?%s'
        )
    );*/

        //if (window.location.hostname === 'autoturbo.pl' ) {
            // Demo settings:
            $('#fileupload').fileupload('option', {
                url: '<?php echo $this->gallery['upload_url'] ?>',
                disableImageResize: false,
                maxFileSize: 5000000,
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
                previewAsCanvas: false
            });
            // Upload server status check for browsers with CORS support:
            if ($.support.cors) {
                $.ajax({
                    url: '<?php echo $this->gallery['upload_url'] ?>',
                    type: 'HEAD'
                }).fail(function () {
                    $('<span class="alert alert-error"/>')
                    .text('Upload server currently unavailable - ' +
                        new Date())
                    .appendTo('#fileupload');
                });
            }
      //  } else {
            // Load existing files:
            $('#fileupload').addClass('fileupload-processing');
            $.ajax({
                // Uncomment the following to send cross-domain cookies:
                //xhrFields: {withCredentials: true},
                url: $('#fileupload').fileupload('option', 'url'),
                dataType: 'json',
                context: $('#fileupload')[0]
            }).always(function (result) {
                $(this).removeClass('fileupload-processing');
            }).done(function (result) {
                $(this).fileupload('option', 'done')
                .call(this, null, {result: result});
               $("a.grouped_elements").fancybox();
            });
     //   }

    });
</script>
<script type="text/javascript">
    $("a.grouped_elements").fancybox();
</script>
