<div class="tresc">

    <!--<h3>Dokumenty</h3>-->
    <div class="ico_hyundai">
        <div id="plyny">
            <div  class="pdf">
                <ul>
                    <li><a href="../doc/bazawiedzy/prezentacja_hyundai_i20.pdf" target="blank">
                            Hyundai i20 - Płyny eksploatacyjne oraz światła zewnętrzne</a></li>
                </ul>
            </div>
        </div>
       
    </div>
<!--
    <div class="ico_akty_prawne">
        <a href="http://kodeks-drogowy.org/" target="blank">
            Kodeks drogowy (stan prawny luty 2018 r.)</br>http://kodeks-drogowy.org</a>
        <div class="pdf">
            <ul>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19970980602" target="blank">
                        Ustawa z dnia 20 czerwca 1997 r. - Prawo o ruchu drogowym</a></li>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20021701393" target="blank">
                        Rozporządzenie Ministrów Infrastruktury oraz Spraw Wewnętrznych i Administracji 
                        z dnia 31 lipca 2002 r. w sprawie znaków i sygnałów drogowych</a></li>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20030320262" target="blank">
                        Rozporządzenie Ministra Infrastruktury z dnia 31 grudnia 2002 r. w sprawie
                        warunków technicznych pojazdów oraz zakresu ich niezbędnego wyposażenia</a></li>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20160000232" target="blank">
                        Rozporządzenie Ministra Infrastruktury i Budownictwa z dnia 24 lutego 2016 r. 
                        w sprawie egzaminowania osób ubiegających się o uprawnienia do kierowania 
                        pojazdami, szkolenia, egzaminowania i uzyskiwania uprawnień przez egzaminatorów 
                        oraz wzorów dokumentów stosowanych w tych sprawach</a></li>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20140000949" target="blank">
                        Rozporządzenie Ministra Zdrowia z dnia 17 lipca 2014 r. w sprawie badań lekarskich osób 
                        ubiegających się o uprawnienia do kierowania pojazdami i kierowców</a></li>
                <li><a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20140000594" target="blank">
                        Rozporządzenie Ministra Infrastruktury i Rozwoju z dnia 9 maja 2014 r. zmieniające 
                        rozporządzenie w sprawie egzaminowania osób ubiegających się o uprawnienia do 
                        kierowania pojazdami, szkolenia, egzaminowania i uzyskiwania uprawnień przez 
                        egzaminatorów oraz wzorów dokumentów stosowanych w tych sprawach</a></li>
            </ul>
        </div>
    </div>

    <h3>Programy</h3>
    <div class="ico_sps">
        <h4>Vademecum wykałdowcy SPS</h4>
        <p>
            Każde nasze zajęcia prowadzone są z wykorzystaniem programu komputerowego 
            specjalnie stworzonego na cele szkolenia kandydatów na kierowców.
        </p>
        <p>
            OSK Auto Turbo jest obecnie w posiadaniu najlepszego programu przeznaczonego 
            do przeprowadzenia zajęć teoretycznych  jakim jest Vademecum Wykładowcy SPS.
        </p>
        <p>
            Program posiada ok. 1,8 tyś różnych ekranów, wyposażony jest w 240 animacji, 
            clipy wideo z realistycznych sytuacji drogowych przedstawionych z perspektywy kierowcy. 
            Co więcej program posiadam automatyczną aktualizacje przez Internet co daje, 
            że treści przekazywane w OSK  Auto  Turbo będą zawsze zgodne ze stanem faktycznym. 
        </p>
        <p>
            Kolejną ważną zaletą jest to, że po każdych zajęciach program posiada zaktualizowaną 
            bazę pytań więc kursant już od samego początku naszych spotkań ćwiczy „testy”, 
            dzięki czemu dobrze przygotowany jest do zdania teoretycznego egzaminu państwowego.
        </p>
        <p>
            Następnym plusem w/w systemu jest, że kursant w momencie zapisu dostaje Podręcznik SPS. 
            Siłą tego podręcznika jest to ,że materiał jest ułożony i ilustrowany dokładnie w taki 
            sam sposób jak Vademecum Wykładowcy SPS. Dlatego nasz Kursant sięgając pod podręcznik SPS wie dokładnie, 
            który materiały należy powtórzyć i które testy wykonać, by sprawdzić swoją wiedze.
        </p>

        <div class="youtube">
            <ul>           
                <li><a class="kamerka" href="http://youtu.be/0dEpCohloU8" target="blank" 
                       onclick="jumpScroll()">Vademecum Wykładowcy SPS PC - Pendrive</a></li>
            </ul> 
        </div>

    </div>

    <div class="ico_testy">
        <h4>Egzamin wewnętrzny 2018 - e-kierowca</h4>
        <p>
            OSK Auto Turbo posiada nowy program komputerowy „EGZAMIN WEWNĘTRZNY 2018” 
            przeznaczony do przeprowadzenia egzaminu wewnętrznego w ośrodku zgodnie 
            z wymogami.
        </p>
        <p>
            Zaletą, tego programu jest to, że został on wyposażony w moduł aktualizacji 
            przez Internet, dzięki czemu cześć teoretyczna jest zawsze na bieżąco z wytycznymi 
            Ministra Infrastruktury. W przypadku pojawienia się nowych pytań, program 
            sam „daje znać” o powiększeniu się ich bazy.
        </p>
        <p>
            W OSK Auto Turbo Kursanci na bieżąco mogą podczas zajęć ćwiczyć rozwiązywanie 
            testów i próbować swoich sił w zdaniu egzaminu.  
        </p>
    </div>
-->
    <!--
    <h2>Akty prawne</h2>
    <div class="pdf">
            <ul>
                <li><a href="../doc/bazawiedzy/12764543671rozp_mz_w_spr_badan_lekarskich_kierowcow_i_kandydatow.pdf" target="blank">Badania lekarskie kierowców i osób ubiegających się o uprawnienia do kierowania pojazdami Dz.U.04.2.15 Rozporządzenie z dnia 7 s</a></li>
                <li><a href="../doc/bazawiedzy/12764544911rozp_mz_w_spr_badan_psych_kierowcow_i_kandydatow.pdf" target="blank">Badania psychologiczne kierowców i osób ubiegających się o uprawnienia do kierowania pojazdami oraz wykonujących pracę na stanow</a></li>
                <li><a href="../doc/bazawiedzy/12764532481rozp_mswia_w_spr_kierowania_ruchem_drogowym.pdf" target="blank">Kierowanie ruchem drogowym Dz.U.03.182.1784 Rozporządzenie z dnia 17 września 2003 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764534181rozp_mswia_w_spr_kierowania_ruchem_drogowym.pdf" target="blank">Kontrola ruchu drogowego Dz.U.03.14.144 Rozporządzenie z dnia  30 grudnia 2002 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764543291rozp_mi_w_spr_okresowych_ograniczen_oraz_zakazu_ruchu.pdf" target="blank">Okresowe ograniczenia oraz zakaz ruchu niektórych pojazdów na drogach Dz.U.03.161.1565 Rozporządzenie z dnia  18 sierpnia 2003 r</a></li>
                <li><a href="../doc/bazawiedzy/12764541391rozp_mswia_w_spr_postepowania_z_kierowcami_naruszajacymi_przepisy_ruchu_drogowego.pdf" target="blank">Postępowanie z kierowcami naruszającymi przepisy ruchu drogowego Dz.U.02.236.1998 Rozporządzenie z dnia 20 grudnia 2002 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764529811prawo_o_ruchu_drogowym.pdf" target="blank">Prawo o ruchu drogowym. Dz.U.05.108.908 Ustawa z dnia 20 czerwca 1997 r.</a></li>
                <li><a href="../doc/bazawiedzy/13263564161projekt_nowelizacji_ustawy_o_kierujacych_pojazdami_styczen_2012.pdf" target="blank">Projekt nowelizacji ustawy o kierujących pojazdami styczeń 2012</a></li>
                <li><a href="../doc/bazawiedzy/12764541881rozp_mi_w_spr_szczegolowych_warunkow_zarzadzania_ruchem_na_drogach.pdf" target="blank">Szczegółowe warunki zarządzania ruchem na drogach oraz wykonywanie nadzoru nad tym zarządzaniem Dz.U.03.177.1729 Rozporządzenie </a></li>
                <li><a href="../doc/bazawiedzy/12764527591rozp_mi_w_spr_szkolenia_egzaminowania_i_uzyskiwania_uprawnien_przez_kierujacych_pojazdami.pdf" target="blank">Szkolenie, egzaminowanie i uzyskiwanie uprawnień przez kierujących pojazdami, instruktorów i egzaminatorów. Dz.U.05.217.1834 Roz</a></li>
                <li><a href="../doc/bazawiedzy/12764542641rozp_mswia_w_spr_usuwania_pojazdow.pdf" target="blank">Usuwanie pojazdów Dz.U.02.134.1133 Rozporządzenie z dnia 2 sierpnia 2002 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764540571rozp_mi_w_spr_war_techn_pojazd_oraz_zakresu_ich_niezb_wyposazenia.pdf" target="blank">Warunki techniczne pojazdów oraz zakres ich niezbędnego wyposażenia Dz.U.03.32.262 Rozporządzenie z dnia 31 grudnia 2002 r.</a></li>
                <li><a href="../doc/bazawiedzy/13219655601wydawanie_uprawnien_14.11.2011.pdf" target="blank">wydawanie uprawnień</a></li>
                <li><a href="../doc/bazawiedzy/12764534681rozp_mi_w_spr_wydawania_uprawnien_do_kierowania_pojazdami.pdf" target="blank">Wydawanie uprawnień do kierowania pojazdami Dz.U.04.24.215 Rozporządzenie z dnia 21 stycznia 2004 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764539661rozp_mi_w_spr_wymiany_praw_jazdy.pdf" target="blank">Wymiana praw jazdy Dz.U.02.69.640 Rozporządzenie z dnia 29 kwietnia 2002 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764536421rozp_m_w_spr_wzorow_dok_stwierdz_uprawn_do_kier_pojazd.pdf" target="blank">Wzory dokumentów stwierdzających uprawnienia do kierowania pojazdami Dz.U.04.89.855 Rozporządzenie z dnia 21 kwietnia 2004 r.</a></li>
                <li><a href="../doc/bazawiedzy/12764531321rozporz_mi_i_mswia_w_spr_znakow_znaki.pdf" target="blank">Znaki i sygnały drogowe. Dz.U.02.170.1393 Rozporządzenie z dnia 31 lipca 2002 r.</a></li>
            </ul>
        </div>
    -->
</div>

<script type="text/javascript">
     div = $('<div class="bez_pdf"></div>');
     ul = $('<ul>');
     li = $('<li style="list-style: none outside none;">'); 
   
    var a = $('<a rel="group1" class="grouped_elements" href="../img/bazawiedzy/slajdy_hyundai/01_slajd.png"> \
                        Hyundai i20 - Płyny eksploatacyjne oraz światła zewnętrzne</a>');
     li.append(a);
     for(i = 2; i < 10; i++){
         li.append('<a  rel="group1" style="display: none;" class="grouped_elements" href="../img/bazawiedzy/slajdy_hyundai/'+ ( i < 10 ? '0'+i : i) +'_slajd.png">\
                            Hyundai i20 - Płyny eksploatacyjne oraz światła zewnętrzne</a>')
         
     }
     $('#plyny').html(div.append(ul.append(li)));  
        
     
    $("a.grouped_elements").fancybox({
        /*'title': this.title*/
    });
</script>  