   <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_cennik_jazdy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Cennik - jazdy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="cennikkursy">Kursy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikjazdy">Jazdy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikpromocje">Promocje</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- CENNIK KURSY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
            <?php echo $this->partial('partials/cennikjazdypartial.phtml', 'default') ?>

			<div class="row g-4 justify-content-center mt-1">
			

				
				<div class="col-lg-12 col-sm-24 wow fadeInUp" data-wow-delay="0.3s">
				
					<div class="course-item bg-light">
						<div class="text-left p-4 pb-0">
						<div class="d-flex border-bottom">
							<h5>Opłaty za jazdy mozna dokonać <b>BLIKiem</b> na numer telefonu: <b>605330708</b>, lub przelewem na konto OSK AUTO TURBO.</h5>
						</div>
							<h5>Dane do przelewu</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-user text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nazwa odbiorcy:</h5>
									<p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-map-marker-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Adres odbiorcy:</h5>
									<p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-university text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nr rachunku odbiorcy:</h5>
									<p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3 pb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-pencil-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Tytułem:</h5>
									<p class="mb-0">Imię i nazwisko kursanta - jazdy doszkalające</p>
								</div>
							</div>
						</div>
					</div>
				
				</div>
			</div>


			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisyjakrozpoczac">Jak rozpocząć?</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			

		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->
