   <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_cennik_jazdy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Cennik - jazdy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="cennikkursy">Kursy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikjazdy">Jazdy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikpromocje">Promocje</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- CENNIK KURSY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                <h1 class="mb-5">Jazdy doszkalające</h1>
            </div>
			
				<!----------------------- poczatek cen jazd --------------------------->

				<div class="row g-4 justify-content-center">

					<!-- blok 1 -->
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
					<div class="course-item bg-light d-flex flex-column h-100">
						<div class="position-relative overflow-hidden">
							<img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_1h.jpg" alt="">
						</div>
						<div class="flex-grow-1 d-flex flex-column">
							<div class="text-center p-4 pb-0">
								<div class="flex-fill text-center border-bottom py-2">
									<h4 class="mb-0">110 PLN</h4>
								</div>
								<div class="flex-fill text-center border-bottom py-2">
									<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
									<h5 class="mb-0">1 godzina</h5>
								</div>
							</div>
							<div class="text-left py-2 px-4">
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
							</div>

							<div class="d-flex border-top mt-auto">
								<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>1 godz.</small>
							</div>
						</div>
						<div class="d-flex border-top">
							<small class="flex-fill text-center py-2">
								<a href="zapisynakurs" class="btn btn-sm btn-primary px-3" style="border-radius: 30px;">Zapisz się</a>
							</small>
						</div>
					</div>
				</div>


					<!-- blok 2 -->
					<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
						<div class="course-item bg-light d-flex flex-column h-100">
							<div class="position-relative overflow-hidden">
								<img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_2h.jpg" alt="">
							</div>
							<div class="flex-grow-1 d-flex flex-column">
								<div class="text-center p-4 pb-0">
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-0">220 PLN</h4>
									</div>
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
										<h5 class="mb-0">2 godziny</h5>
									</div>
								</div>
								<div class="text-left py-2 px-4">
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość jazdy na plac manewrowy</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
								</div>
								<div class="d-flex border-top">
									<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
								</div>
							</div>
							<div class="d-flex border-top mt-auto">
								<small class="flex-fill text-center py-2">
									<a href="zapisynakurs" class="btn btn-sm btn-primary px-3" style="border-radius: 30px;">Zapisz się</a>
								</small>
							</div>
						</div>
					</div>

					<!-- blok 3 -->
					<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
						<div class="course-item bg-light d-flex flex-column h-100">
							<div class="position-relative overflow-hidden">
								<img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_2h_WORD.jpg" alt="">
							</div>
							<div class="flex-grow-1 d-flex flex-column">
								<div class="text-center p-4 pb-0">
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-0">290 PLN</h4>
									</div>
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
										<h5 class="mb-0">2 godziny + WORD</h5>
									</div>
								</div>
								<div class="text-left py-2 px-4">
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych (90 min)</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po placu manewrowym WORD Rzeszów (30 min)</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić szczególnie przed egzaminem</p>
								</div>
								<div class="d-flex border-top">
									<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
								</div>
							</div>
							<div class="d-flex border-top mt-auto">
								<small class="flex-fill text-center py-2">
									<a href="zapisynakurs" class="btn btn-sm btn-primary px-3" style="border-radius: 30px;">Zapisz się</a>
								</small>
							</div>
						</div>
					</div>

					<!-- blok 4 -->
					<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
						<div class="course-item bg-light d-flex flex-column h-100">
							<div class="position-relative overflow-hidden">
								<img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_10h.jpg" alt="">
							</div>
							<div class="flex-grow-1 d-flex flex-column">
								<div class="text-center p-4 pb-0">
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-0">1000 PLN</h4>
									</div>
									<div class="flex-fill text-center border-bottom py-2">
										<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
										<h5 class="mb-0">PAKIET 10 godzin</h5>
									</div>
								</div>
								<div class="text-left py-2 px-4">
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość wjazdu na plac manewrowy</p>
									<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
								</div>
								<div class="d-flex border-top">
									<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>10 godz.</small>
								</div>
							</div>
							<div class="d-flex border-top mt-auto">
								<small class="flex-fill text-center py-2">
									<a href="zapisynakurs" class="btn btn-sm btn-primary px-3" style="border-radius: 30px;">Zapisz się</a>
								</small>
							</div>
						</div>
					</div>
				</div>


				<!--------------------------- koniec cen jazd --------------------------->

			<div class="row g-4 justify-content-center mt-1">
			

				
				<div class="col-lg-12 col-sm-24 wow fadeInUp" data-wow-delay="0.3s">
				
					<div class="course-item bg-light">
						<div class="text-left p-4 pb-0">
						<div class="d-flex border-bottom">
							<h5>Opłaty za jazdy mozna dokonać <b>BLIKiem</b> na numer telefonu: <b>605330708</b>, lub przelewem na konto OSK AUTO TURBO.</h5>
						</div>
							<h5>Dane do przelewu</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-user text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nazwa odbiorcy:</h5>
									<p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-map-marker-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Adres odbiorcy:</h5>
									<p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-university text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nr rachunku odbiorcy:</h5>
									<p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3 pb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-pencil-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Tytułem:</h5>
									<p class="mb-0">Imię i nazwisko kursanta - jazdy doszkalające</p>
								</div>
							</div>
						</div>
					</div>
				
				</div>
			</div>


			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisyjakrozpoczac">Jak rozpocząć?</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			

		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->
