   <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_cennik_promocje">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Promocje</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="cennikkursy">Kursy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikjazdy">Jazdy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikpromocje">Promocje</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- PROMOCJE ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Promocje</h6>
                <h1 class="mb-5">Promocje</h1>
            </div>
			<div class="row g-4 justify-content-center">
			
			<div class="conteiner_flash">
			
			 <div class="row g-4">
			 
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
				<div class="item_flash d-flex flex-column h-100">
                    <div class="service-item text-center pt-3 d-flex flex-column h-100">
                        <div class="p-4">
                            <i class="fa fa-3x fa-user-graduate text-primary mb-4"></i>
                            <h5 class="mb-3 text-primary">200 zł zniżki</br>dla uczniów i studentów!</h5>
                            <p>Zdobądź zniżkę 200 zł na kurs prawa jazdy! Jeśli jesteś uczniem lub studentem, skorzystaj z tej wyjątkowej oferty. Zapisz się do nas i zaoszczędzisz na szkoleniu</p>
							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i> Tylko dla uczniów i studentów</p>
                        </div>
                    </div>
                </div>
				</div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
				<div class="item_flash d-flex flex-column h-100">
                    <div class="service-item text-center pt-3 d-flex flex-column h-100">
                        <div class="p-4">
                            <i class="fa fa-3x fa-user-friends text-primary mb-4"></i>
                            <h5 class="mb-3 text-primary">1 h jazdy GRATIS</br>dla 2 osób</h5>
                            <p>Zapisz się na kurs prawa jazdy razem z przyjacielem i odbierz 1 godzinę jazdy GRATIS! Kursy będą bardziej motywujące, a Ty zaoszczędzisz na swojej nauce</p>
							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Oferta dla dwóch osób</p>
                        </div>
					</div>
                </div>
                </div>
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
				<div class="item_flash d-flex flex-column h-100">
                    <div class="service-item text-center pt-3 d-flex flex-column h-100">
                        <div class="p-4">
                            <i class="fa fa-3x fa-users text-primary mb-4"></i>
                            <h5 class="mb-3 text-primary">2 h jazdy GRATIS</br>dla 3 osób</h5>
                            <p>Zapisz 3 osoby na kurs prawa jazdy, a każda z nich otrzyma 2 godziny jazdy GRATIS. Więcej osób, większa zniżka – to doskonała okazja, by zaoszczędzić!</p>
							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Oferta dla trzech osób</p>
                        </div>
                    </div>
				</div>
                </div>
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
				<div class="item_flash d-flex flex-column h-100">
                    <div class="service-item text-center pt-3 d-flex flex-column h-100">
                        <div class="p-4">
                            <i class="fa fa-3x fa-gift text-primary mb-4"></i>
                            <h5 class="mb-3 text-primary">Poleć i ZYSKAJ</h5>
                            <p>Poleć naszą szkołę jazdy znajomym i odbierz 1 godzinę jazdy GRATIS za każdą poleconą osobę, która zapisze się na kurs. Zyskaj bonusy i pomóż innym na drodze do zdobycia prawa jazdy!</p>
							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Dla osób polecających kursy</p>
                        </div>
                    </div>
				</div>
                </div>
			
			
			</div>
                
				
				
				
				
		    </div>


			</div>


			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->

		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->
