    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_cennik_kursy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Cennik - kursy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="/cennikkursy">Kursy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="/cennikjazdy">Jazdy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="/cennikpromocje">Promocje</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- CENNIK KURSY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
			
			<!------------------------------- początek cen kursów -------------------------------------->

			<?php echo $this->partial('partials/cennikkursypartial.phtml', 'default') ?>
			
			
			<div class="row g-4 justify-content-center mt-1">
			

				<div class="col-lg-6 col-sm-12">
					<div class="course-item bg-light d-flex flex-column h-100">
						<div class="text-left p-4 pb-0">
							<h5>Opłata za kurs może być wniesiona w całości lub w systemie ratalnym (RATY 0%)</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>I</b></div>
								</div>
								<div class="ms-3">

									<p class="mb-0"><b>I rata - 1000 zł</b> - przy zapisie na kurs</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>II</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>II rata - 1100 zł</b> - przed końcem zajęć teoretycznych</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>III</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>III rata - 1100 zł</b> - przed 10 godziną jazdy</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>IV</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>IV rata - od 1099 zł</b> - przed 20 godziną jazdy</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>V</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>V rata - 1 000 zł</b> - przed 30 godziną jazdy</p>
									<small class="mb-0">(dotyczy kursów EKSPRESOWYCH)</small>
								</div>
							</div>
						</div>
					</div>				
				</div>
				
				<div class="col-lg-6 col-sm-12">
				
					<div class="course-item bg-light d-flex flex-column h-100">
						<div class="text-left p-4 pb-0">
							<h5>Dane do przelewu</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-user text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nazwa odbiorcy:</h5>
									<p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-map-marker-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Adres odbiorcy:</h5>
									<p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-university text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nr rachunku odbiorcy:</h5>
									<p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-pencil-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Tytułem:</h5>
									<p class="mb-0">Imię i nazwisko kursanta - kurs prawa jazdy</p>
								</div>
							</div>
						</div>
					</div>
				
				</div>
			</div>

			<!----------------------------------- koniec cen kursów ---------------------------------->
			
			<div class="course-item bg-light d-flex flex-column h-100 my-4">
						<div class="text-left p-4 pb-0">
							<h5>Koszty dodatkowe:</h5>
							<div class="text-left py-2 pb-10">
								<p class="mb-1"><i class="fa fa-medkit text-primary me-2"></i>Opłata za wydanie <b>orzeczenia lekarskiego</b> stwierdzającego brak przeciwwskazań zdrowotnych do kierowania pojazdami - platne u lekarza</p>
								<p class="mb-1"><i class="fa fa-laptop text-primary me-2"></i>Opłata za <b>część teoretyczną państwowego egzaminu</b> na prawo jazdy kat. B - <b>58 zł</b> <a class="text-dark" href="https://www.word.rzeszow.pl/oplaty">(płatne w WORD)</a></p>
								<p class="mb-1"><i class="fa fa-car text-primary me-2"></i>Opłata za <b>część praktyczną państwowego egzaminu</b> na prawo jazdy kat. B - <b>237 zł</b> <a class="text-dark" href="https://www.word.rzeszow.pl/oplaty">(płatne w WORD)</a></p>
								<p class="mb-1"><i class="fa fa-id-card text-primary me-2"></i>Opłata za <b>wydanie prawa jazdy</b> - <b>100 zł</b> (płatne w Wydziale Komunikacji)</p>
							</div>
						</div>
					</div>		
			
			
			

			<div class="py-5">
			<?php echo $this->partial('partials/cennikpromocjepartial.phtml', 'default') ?>
			</div>


			<!----------- początek PDF z cennikiem ---------------->
			<div class="container py-5">
				<div class="row g-4 justify-content-center">
					<p class="mb-0 border-bottom">Pliki do pobrania:</p>
					<div>
						<a class="btn text-dark" href="../doci/cennik/Cennik.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Cennik OSK AUTO TURBO</a>
					</div>
				</div>
			</div>
			<!----------- koniec PDF z cennikiem ---------------->
			
			
			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/zapisyjakrozpoczac">Jak rozpocząć?</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			
		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->