<div class="tresc">
<p>obowiązuje od 1.01.2025 r.</p>
    <table class="raty">
        <tr>
            <td class="pomar" rowspan="2" colspan="3" style="width: 500px">Rodzaj zajęć</td>
            <td class="pomarwaski" colspan="2" style="width: 100px">Ilość godzin zajęć</td>
            <td class="pomar" rowspan="2" style="width: 100px">Cena</td>
        </tr>
        <tr>
            <td class="pomarwaski" style="width: 70px">teoria</td>
            <td class="pomarwaski" style="width: 70px">praktyka</td>
        </tr>
        <tr>
            <td class="pomar" rowspan="9">Kurs prawa jazdy kat. B </td>
            <td class="szaryleft" rowspan="2"style="width: 110px"><b>PODSTAWOWY</b> </td>
			<td class="szaryleft">uczniowie i studenci</br> <span style="color:red"><B>PROMOCJA WIOSENNA</B></span></td>
            <td class="bialy">30</td>  
            <td class="bialy">30</td>
            <td class="bialybold"><s>3399 zł</s></br><span style="color:red">3199 zł</span></td>

        </tr>
        <tr>
            <td class="szaryleft">pozostali</td>
            <td class="bialy">30</td>
            <td class="bialy">30</td>
            <td class="bialybold">3399 zł</td>

        </tr> 
        <tr>
            <td class="szaryleft" rowspan="2"><b>PRAKTYCZNY</b> </br><span style="font-size:9pt">- dotyczy osób, które zdały PAŃSTWOWY EGZAMIN TEORETYCZNY</span></td>
			<td class="szaryleft">uczniowie i studenci</br> <span style="color:red"><B>PROMOCJA WIOSENNA</B></span></td>
            <td class="bialy">4</td>
            <td class="bialy">30</td>
            <td class="bialybold"><s>3199 zł</s></br><span style="color:red">2999 zł </br></span></td>

        </tr>
        <tr>
            <td class="szaryleft">pozostali</td>
            <td class="bialy">4</td>
            <td class="bialy">30</td>
            <td class="bialybold">3199 zł</br></td>

        </tr> 
        
        <tr>
            <td class="szaryleft" rowspan="2"><b>EKSPRESOWY</b></br><span style="font-size:9pt">- cały kurs w 30 dni</span></td>
			<td class="szaryleft" >uczniowie i studenci</br> <span style="color:red"><B>PROMOCJA WIOSENNA</B></span></td>
            <td class="bialy">30</td>
            <td class="bialy">30</td>
            <td class="bialybold"><s>4199 zł</s></br><span style="color:red">3999 zł</span></td>

        </tr>
        
		<tr>
            <td class="szaryleft">pozostali</td>
            <td class="bialy">30</td>
            <td class="bialy">30</td>
            <td class="bialybold">4199 zł</td>

        </tr>
        <tr>
            <td class="szaryleft" rowspan="2"><b>EKSPRESOWY PRAKTYCZNY</b></br><span style="font-size:9pt">- dotyczy osób, które zdały PAŃSTWOWY EGZAMIN TEORETYCZNY</span></td>
			<td class="szaryleft">uczniowie i studenci</br><span style="color:red"><B>PROMOCJA WIOSENNA</B></span></td>
            <td class="bialy">4</td>
            <td class="bialy">30</td>
            <td class="bialybold"><s>3999 zł</s></br><span style="color:red">3799 zł</span></td>

        </tr> 
        
		<tr>
            <td class="szaryleft">pozostali</td>
            <td class="bialy">4</td>
            <td class="bialy">30</td>
            <td class="bialybold">3999 zł</td>

        </tr> 
		
        <tr>
            <td class="szaryleft" colspan="2"><b>ROZSZERZONY</b></br>- dodatkowe 10 godzin jazd do każdego rodzaju kursu za 1000 zł!</b></td>
            <td class="bialy">-</td>
            <td class="bialy">+ 10</td>
            <td class="bialybold">+ 1000 zł</td>

        </tr>
        <tr>
            <td rowspan="3"class="pomar">Jazdy dodatkowe</td>
            <td class="szaryleft"  colspan="2" >1 godzina</td>
            <td class="bialy">-</td>
            <td class="bialy">1</td>
            <td class="bialybold">110 zł</td>

        </tr>
        <tr>
            <td class="szaryleft"  colspan="2" >2 godziny</td>
            <td class="bialy">-</td>
            <td class="bialy">2</td> 
            <td class="bialybold">220 zł</td>

        </tr>
        <tr>
            <td class="szaryleft" colspan="2">2 godziny + <B>JAZDA PRÓBNA</B> na placu egzaminacyjnym WORD w Rzeszowie</td>
            <td class="bialy">-</td>
            <td class="bialy">2</td>
            <td class="bialybold">290 zł</td>

        </tr>

    </table>

    <p><u>Cena kursu <b>PODSTAWOWEGO</b> i <b>EKSPRESWEGO</b> obejmuje:</u></p>
    <ul>
        <li>30 godzin lekcyjnych zajęć teoretycznych</li>
        <li>30 lub 40 godzin zegarowych zajęć praktycznych</li>
        <li>szkolenie z zakresu pierwszej pomocy z wykwalifikowanym ratownikiem medycznym</li>
        <li><b>NOWOŚĆ!!! Jazda na placu egzaminacyjnym WORD w Rzeszowie!</b></li> 
        <li>wewnętrzny egzamin teoretyczny</li>
        <li>wewnętrzny egzamin praktyczny</li>
        <li>materiały edukacyjne dla kursanta GRATIS! 
            (w tym dostęp do <b>PEŁNEJ I AKTUALNEJ BAZY PYTAŃ z egzaminów państwowych</b> oraz podręcznik kursanta)</li>
        
    </ul>
    
    <p><u>Cena kursu <b>PRAKTYCZNEGO </b> i <b>EKSPRESOWEGO PRAKTYCZNEGO </b> obejmuje:</u></p>
    <ul>
        <li>30 godzin zegarowych zajęć praktycznych</li>
        <li>szkolenie z zakresu pierwszej pomocy z wykwalifikowanym ratownikiem medycznym</li>
        <li><b>NOWOŚĆ!!! Jazda na placu egzaminacyjnym WORD w Rzeszowie!</b></li> 
        <li>wewnętrzny egzamin praktyczny</li>       
    </ul>
    
    <p><u>Czas trwania kursu:</u></p>
    <ul>
        <li><b>PODSTAWOWY</b> część teoretyczna - 2 tygodnie, część praktyczna - ok. 5-9 tygodni</li>
        <li><b>PRAKTYCZNY</b> ok. 5-9 tygodni</li>
        <li><b>EKSPRESOWY</b> do 30 dni</li>
        <li><b>EKSPRESOWY PRAKTYCZNY </b>od 12 do 15 dni</li> 
        <li><b>ROZSZERZONY</b> część teoretyczna - 2 tygodnie, część praktyczna - ok. 7-11 tygodni</li>
    </ul>


    <h3>Opłata za kurs może być wniesiona w całości jak również w systemie ratalnym (RATY 0%)</h3>
    <table class="raty">
        <tr>
            <td class="pomar" style="width: 90px">Nr raty</td>
            <td class="pomar" style="width: 220px">Wysokość raty</td>
            <td class="pomar" style="width: 240px">Kiedy należy wpłacić</td>
        </tr>
        <tr>
            <td class="pomar">I rata</td>
            <td class="szary">800 zł</td>
            <td class="szaryleft">przy zapisie na kurs</td>

        </tr>
        <tr>
            <td class="pomar">II rata</td>
            <td class="szary">800 zł</td>
            <td class="szaryleft">przed końcem zajęć teoretycznych</td>

        </tr>
        <tr>
            <td class="pomar">III rata</td>
            <td class="szary">800 zł</td>
            <td class="szaryleft">przed 10 godziną jazdy</td>
        </tr>
        <tr>
            <td class="pomar">IV rata</td>
            <td class="szary"><!--499 zł </br>--><DIV style="color:red">799 zł</br>PROMOCJA WIOSENNA</DIV>
            </td>
            <td class="szaryleft">przed 20 godziną jazdy</td>
        </tr>
        <tr>
            <td class="pomar">V rata *</td>
            <td class="szary">pozostała kwota</td>
            <td class="szaryleft">przed 30 godziną jazdy</td>
        </tr>
         
    </table>  
    <h6>* dotyczy kursu ROZSZERZONEGO lub EKSPRESOWEGO</h6>
    
    <h2>Koszty dodatkowe</h2>
    <ul>
        <li>Opłata za wydanie orzeczenia lekarskiego stwierdzającego brak przeciwwskazań zdrowotnych do kierowania pojazdami - platne u lekarza</li>
        <li>Opłata za część teoretyczną państwowego egzaminu na prawo jazdy kat. B - <b>55 zł</b> (płatne w WORD)</br>
            Opłata za część praktyczną państwowego egzaminu na prawo jazdy kat. B - <b>222 zł</b> (płatne w WORD)
            <ul class="list_none">
                <!--<li>
                    <a class="pdfik_link_maly" href="../doci/cennik/ceny_egzaminow.pdf" target="_blank">
                        Rozporządzenie Ministra Transportu, Budownictwa i Gospodarki Morskiej z dnia 16 stycznia 2013 r.
                        w sprawie wysokości opłat za przeprowadzenie egzaminu państwowego oraz stawek wynagrodzenia związanych
                        z uzyskiwaniem uprawnień przez egzaminatorów 
                    </a>
                </li>
                <li>
                    <a class="pdfik_link_maly" href="../doci/cennik/ceny_egzaminow_zmiana.pdf" target="_blank">
                        Rozporządzenie Ministra Transportu, Budownictwa i Gospodarki Morskiej z dnia 19 kwietnia 2013 r. 
                        zmieniające rozporządzenie w sprawie wysokości opłat za przeprowadzenie egzaminu państwowego 
                        oraz stawek wynagrodzenia związanych z uzyskiwaniem uprawnień przez egzaminatorów 
                    </a>
                </li>-->
            </ul>
        </li>
        <li>Opłata za wydanie prawa jazdy - <b>100 zł</b> (płatne w Wydziale Komunikacji)
            <ul class="list_none">
                <li>
                    <a class="pdfik_link_maly" href="../doci/cennik/ceny_wydania_prawa_jazdy.pdf" target="_blank">
                        Rozporządzenie Ministra Transportu, Budownictwa i Gospodarki Morskiej z dnia 11 stycznia 2013 r.
w sprawie wysokości opłat za wydanie dokumentów stwierdzających uprawnienia do kierowania pojazdami
                    </a>
                </li>
            </ul> 
        </li>
    </ul>
       
    <h4>Dane do przelewu</h4> 
    
    <table class="raty"> 
        <tr>
            <td class="pomar" style="width: 25%">Nazwa odbiorcy:</td>
            <td class="bialleft" style="width: 75%">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO”</hr> GRZEGORZ PAŁASZ</td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Adres odbiorcy:</td>
            <td class="bialleft" style="width: 220px">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Nr rachunku odbiorcy:</td>
            <td class="bialleft" style="width: 220px"><b>51 1950 0001 2006 0263 1600 0002</b></td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Tytułem (przykłady):</td>
            <td class="bialleft" style="width: 220px">
                <ul>
                    <li>Opłata za kurs prawa jazdy</li>
                    <li>Opłata za kurs prawa jazdy (I rata)</li>
                    <li>Opłata za 2 godziny jazdy doszkalającej</li>
                </ul>
            </td>
        </tr>
    </table>
    
    
    <h2>Cennik (wersja pdf)</h2>
    <div class="pdf">
            <ul> 
                <li><a href="../doci/cennik/Cennik.pdf" target="blank">Cennik.pdf</a></li>
            </ul>
    </div>
</div>