    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_cennik_kursy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Cennik - kursy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="cennikkursy">Kursy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikjazdy">Jazdy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikpromocje">Promocje</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- CENNIK KURSY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
			
			<!------------------------------- początek cen kursów -------------------------------------->

			<?php echo $this->partial('partials/cennikkursypartial.phtml', 'default') ?>

			<!----------------------------------- koniec cen kursów ---------------------------------->

			<div class="py-5">
			<?php echo $this->partial('partials/cennikpromocjepartial.phtml', 'default') ?>
			</div>

			<!-- przyciski na dole------------------>
			
			
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisyjakrozpoczac">Jak rozpocząć?</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->

		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->