    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_dlaczego_my">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Dlaczego my?</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="/zapisyjakrozpoczac">Jak rozpocząć?</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="/zapisynakurs">Zapisy</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="/szkolenieinstruktorzy">Nasi instruktorzy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- GALERIA ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			<div class="text-center">
                <h6 class="section-title bg-white text-center text-primary px-3">O nas</h6>
                <h1 class="mb-1">Dlaczego my?</h1>
            </div>
			
			<div class="container py-5">
			  
				<div class="row g-3">
					
					<div class="col-lg-9 col-md-12">
					<div class="row g-3">
					
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-chart-line text-primary mb-4"></i>
							<h5 class="mb-3">Wysoka zdawalność</h5>
							<p>Kursanci AUTO TURBO osiągają świetne wyniki na egzaminach państwowych, co świadczy o skuteczności szkolenia naszego ośrodka</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-trophy text-primary mb-4"></i>
							<h5 class="mb-3">Najwyżej w rankingach</h5>
							<p>Szkoła regularnie zajmuje czołowe miejsca w ogólnopolskich rankingach szkół nauki jazdy w Rzeszowie, co potwierdza jej renomę</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">								
							<i class="fa fa-4x fa-car text-primary mb-4"></i>
							<h5 class="mb-3">Auta identyczne jak na egzaminie w WORD</h5>
							<p>Jazdy odbywają się na nowoczesnych autach (z klimatyzacją i czujnikami parkowania) identycznych jak te używane podczas egzaminów w WORD Rzeszów</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-chalkboard-teacher text-primary mb-4"></i>
							<h5 class="mb-3">Cierpliwi i doświadczeni instruktorzy</h5>
							<p>Profesjonalna kadra potrafi w przystępny sposób przekazać wiedzę i stworzyć komfortową atmosferę do nauki, nawet dla najbardziej zestresowanych kursantów</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-film text-primary mb-4"></i>
							<h5 class="mb-3">Filmy instruktażowe</h5>
							<p>Dodatkowe materiały wideo pomagają lepiej zrozumieć przepisy i manewry egzaminacyjne, co znacznie ułatwia naukę</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa fa-map-marker-alt me-3 text-primary mb-4"></i>
							<h5 class="mb-3">Świetna lokalizacja</h5>
							<p>AUTO TURBO mieści się tuż obok dworca PKP i PKS, co czyni ją idealnym wyborem dla osób dojeżdżających z okolicznych miejscowości</p>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-clock text-primary mb-4"></i>
							<h5 class="mb-3">Elastyczne godziny jazd</h5>
							<p>Możliwość umawiania się na jazdy codziennie w godzinach od 7:00 do 21:00 oraz w weekendy</p>
						</div>
					</div>			
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-thumbs-up text-primary mb-4"></i>
							<h5 class="mb-3">Setki pozytywnych opinii</h5>
							<p>Zadowoleni kursanci chętnie dzielą się pozytywnymi recenzjami w Internecie, co mówi samo za siebie</p>
						</div>
					</div>       
					<div class="col-lg-4 col-md-6">
						<div class="bg-light text-center p-4 h-100 d-flex flex-column shadow-sm rounded-4">
							<i class="fa fa-4x fa-file-signature text-primary mb-4"></i>
							<h5 class="mb-3">Pomoc w założeniu PKK</h5>
							<p>Wypełnienie niezbędnych dokumentów i wykonanie badań lekarskich na miejscu – wszystko w OSK AUTO TURBO</p>
						</div>
					</div>   
					
					</div>
					</div>
					
					<div class="col-lg-3 col-md-12">
					
						<div class="course-item bg-light d-flex flex-column h-100">
							<div class="video-container mt-2 mb-5 pb-5">
								<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
								  <iframe 
									src="https://www.youtube.com/embed/uin6-7y5Ltc?si=orMw1MhIPHACZSI-" 
									style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
									frameborder="0" 
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
									referrerpolicy="strict-origin-when-cross-origin" 
									allowfullscreen>
									
								  </iframe>
								</div>
							</div>
						</div>
					
					</div>
					
						
				</div>

			</div>
		</div>


			
			

			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->

	</div>
		
    </div>
    <!-- GALERIA ---------------------------------------- End -->