   <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_filmy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Filmy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="/bazawiedzy">Baza wiedzy</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="/filmy">Filmy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center">
                <h6 class="section-title bg-white text-center text-primary px-3">Filmy</h6>
                <h1 class="mb-3">Zobacz nasze filmy instruktażowe!</h1>
            </div>
			<div class="row g-4 justify-content-center">
			

				<div class="col-lg-6 col-sm-12">
				<div class="video-container">
					<iframe width="560" height="315" src="https://www.youtube.com/embed/XIUp_7ZxcWE?si=qV6kxwuRlDX4EOmC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
				</div>
				</div>
				<div class="col-lg-6 col-sm-12">
				<div class="video-container">
					<iframe width="560" height="315" src="https://www.youtube.com/embed/7xapYXoqPQ8?si=LWhgkx_fBf9aUO4A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
				</div>
				</div>
				
				
				<div class="text-center">
					<h6 class="section-title bg-white text-center text-primary px-3">Filmy</h6>
					<h1 class="mb-1">Szybka powtórka przed egzaminem</h1>
				</div>
				
				
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/at-x-_v7ALk?si=jMkfNGmf11nAgmIi" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/T95IuhO73Lg?si=iXJzqQ7OFhtLkcJP" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>				
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/XXKapqTM6jo" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/TCA8Awm8J_Y" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/Fyu99Trmbz4?si=jOn8VARTY3jlTDHx"
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/qOTkSv2xMyk?si=Yi58oWzj_X9lUJkm"
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/xlIqHDhnEBk?si=OV_QQJLv6vnNKKFd"
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				
				<div class="text-center">
					<h6 class="section-title bg-white text-center text-primary px-3">Filmy</h6>
					<h1 class="mb-1">To warto wiedzieć!</h1>
				</div>
				
				
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/kFHLBvFinPw?si=UkQ7zG_B4SrO6OW9" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="video-container">
					<div style="position: relative; width: 100%; padding-bottom: 177.78%; height: 0; overflow: hidden;">
					  <iframe 
						src="https://www.youtube.com/embed/FnKXJMf-3fs?si=54ZvnPhK23MEP_zl" 
						style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
						frameborder="0" 
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
						referrerpolicy="strict-origin-when-cross-origin" 
						allowfullscreen>
					  </iframe>
					</div>
				</div>
				</div>
			



			</div>


			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			
		</div>
		
    </div>
    <!-- FILMY ---------------------------------------- End -->
