<div class="tresc">
<script type="text/javascript">
    $(document).ready(function(){
        
        $("a.film_mini, a.kamerka, a.kamerka_new").click(function() {
		$.fancybox({
			'padding'		: 3,
			'autoScale'		: false,
			'transitionIn'	: 'none', 
			'transitionOut'	: 'none',
			'title'			: this.title,
			'width'		: 840,
			'height'		: 560,
			'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
			'type'			: 'swf',
			'swf'			: {
			   	 'wmode'		: 'transparent',
				'allowfullscreen'	: 'true'
			}
		});

	return false;
	});
    });
    
</script>
<!--
    <div id="tv" style="background-image: url('../img/filmy/tv.png'); background-repeat:no-repeat; height: 580px;width: 700px; padding-top: 13px;">
        <iframe style="overflow: hidden;"class="tv" name="tv" src="http://www.youtube.com/watch?v=YZP7YTEc3xU" frameborder="0" allowfullscreen></iframe>
        <img  style="display: none; margin-left: 13px;" src="../img/filmy/str03.png" />
    </div>
-->

    <!--<div id="opis">
    -->
    <h4 id="tytul">  </h4>
    <!--
    <p id="opisik">  </p>
    
</div>
    -->
    <table class="raty">

		<tr>
            <td class="pomar" colspan="2" style="width: 100%">Kurs prawa jazdy w OSK AUTO TURBO</td>
        </tr>
		<tr>
            <td class="szary">
                <a class="film_mini" title="Dlaczego warto zapisać się na kurs prawa jazdy w OSK AUTO TURBO?" href="http://www.youtube.com/watch?v=u6T_ogokt7o"  content="Dlaczego warto zapisać się na kurs prawa jazdy w OSK AUTO TURBO?">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/dlaczego_AUTO_TURBO.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Dlaczego warto zapisać się na kurs prawa jazdy w OSK AUTO TURBO?" href="http://www.youtube.com/watch?v=u6T_ogokt7o"  
                   content="opis 1"
                   >Dlaczego warto zapisać się na kurs prawa jazdy w OSK AUTO TURBO?</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Wykłady w ośrodku, czy e-learning?" href="http://www.youtube.com/watch?v=6rdbxXCz1gs"  content="Wykłady w ośrodku, czy e-learning?">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/wyklady_vs_e-learning_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Wykłady w ośrodku, czy e-learning?" href="http://www.youtube.com/watch?v=6rdbxXCz1gs"  
                   content="opis 1"
                   >Wykłady w ośrodku, czy e-learning?</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Jak długo trwa kurs prawa jazdy?" href="http://www.youtube.com/watch?v=dZ73mePrU4M"  content="Jak długo trwa kurs prawa jazdy?">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/jak_długo_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Jak długo trwa kurs prawa jazdy?" href="http://www.youtube.com/watch?v=dZ73mePrU4M"  
                   content="opis 1"
                   >Jak długo trwa kurs prawa jazdy?</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Czy wykłady są obowiązkowe?" href="http://www.youtube.com/watch?v=0M-PvMLs4Ak"  content="Czy wykłady są obowiązkowe?">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/wyklady_obowiazkowe_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Czy wykłady są obowiązkowe?" href="http://www.youtube.com/watch?v=0M-PvMLs4Ak"  
                   content="opis 1"
                   >Czy wykłady są obowiązkowe?</a>
            </td>
        </tr>
		
		<tr>
            <td class="pomar" colspan="2" style="width: 100%">Egzamin teoretyczny</td>
        </tr>
				
		<tr>
            <td class="szary">
                <a class="film_mini" title="Egzamin teoretyczny - porady i wskazówki" href="http://www.youtube.com/watch?v=YOxfSy3r6sA"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/egzamin_teoretyczny_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Egzamin teoretyczny - porady i wskazówki" href="http://www.youtube.com/watch?v=YOxfSy3r6sA"  
                   content="opis 1"
                   >Egzamin teoretyczny - porady i wskazówki</a>
            </td>
        </tr>
		
		<tr>
            <td class="pomar" colspan="2" style="width: 100%">Egzamin praktyczny</td>
        </tr>
				
		<tr>
            <td class="szary">
                <a class="film_mini" title="Egzamin praktyczny - krok po kroku" href="http://www.youtube.com/watch?v=L9zaOflUg4I"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/egzamin_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Egzamin praktyczny - krok po kroku" href="http://www.youtube.com/watch?v=L9zaOflUg4I"  
                   content="opis 1"
                   >Egzamin praktyczny - krok po kroku</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Obsługa pojazdu HYUNDAI I20 ver. 2020" href="http://www.youtube.com/watch?v=YHshxrpVAHI"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/obsluga_2020.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Obsługa pojazdu HYUNDAI I20 ver. 2020" href="http://www.youtube.com/watch?v=YHshxrpVAHI"  
                   content="opis 1"
                   >Obsługa pojazdu HYUNDAI I20 ver. 2020</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="ŚWIATŁA - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem" href="http://www.youtube.com/watch?v=ZNG0KpxEu8Q"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/swiatla_zewnetrzne_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="ŚWIATŁA - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem" href="http://www.youtube.com/watch?v=ZNG0KpxEu8Q"  
                   content="opis 1"
                   >ŚWIATŁA - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="PŁYNY EKSPLOATACYJNE - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem" href="http://www.youtube.com/watch?v=czWdmF9RiNA"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/plyny_eksploatacyjne_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="PŁYNY EKSPLOATACYJNE - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem" href="http://www.youtube.com/watch?v=czWdmF9RiNA"  
                   content="opis 1"
                   >PŁYNY EKSPLOATACYJNE - HYUNDAI I20 ver. 2020 - Szybka powtórka przed egzaminem</a>
            </td>
        </tr>
		
             		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Jazda pasem ruchu i ruszanie do przodu ze wzniesienia" href="http://www.youtube.com/watch?v=kQb2jzQPR-g"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/pas_ruchu_160.png">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Jazda pasem ruchu i ruszanie do przodu ze wzniesienia" href="http://www.youtube.com/watch?v=kQb2jzQPR-g"  
                   content="opis 1"
                   >Jazda pasem ruchu i ruszanie do przodu ze wzniesienia</a>
            </td>
        </tr>
		
		
		<tr>
            <td class="pomar" colspan="2" style="width: 100%">Zmiany w przepisach ruchu drogowego</td>
        </tr>
				
		<tr>
            <td class="szary">
                <a class="film_mini" title="Zmiany w przepisach od 1.06.2021 r." href="http://www.youtube.com/watch?v=j6Jt3OMQFmM"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/zmiany_01062021_160.png">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zmiany w przepisach od 1.06.2021 r." href="http://www.youtube.com/watch?v=j6Jt3OMQFmM"  
                   content="opis 1"
                   >Zmiany w przepisach od 1.06.2021 r.</a>
            </td>
        </tr>
        
        <tr>
            <td class="pomar" colspan="2" style="width: 100%">Trasy egzaminacyjne z perspektywy kursanta</td>
        </tr>

<tr>
            <td class="szary" colspan="2" style="width: 100%">Skrzyżowania</td>
        </tr>
        
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Kwadrat śmierci - przejazd przez ul. Partyzantów, ul. Piękną, ul. Husarską i ul. Jasną" href="http://www.youtube.com/watch?v=fq_80daBkaE"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/kwadrat_smierci_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka"  title="Kwadrat śmierci - przejazd przez ul. Partyzantów, ul. Piękną, ul. Husarską i ul. Jasną" href="http://www.youtube.com/watch?v=fq_80daBkaE"  
                   content="opis 1"
                   >"Kwadrat śmierci" - przejazd przez ul. Partyzantów, ul. Piękną, ul. Husarską i ul. Jasną</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Trójkąt - Wyspa (dawny Pogwizdów)" href="http://www.youtube.com/watch?v=leo8E95dwUg"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/trojkat_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka"  title="Trójkąt - Wyspa (dawny Pogwizdów)" href="http://www.youtube.com/watch?v=leo8E95dwUg"  
                   content="opis 1"
                   >"Trójkąt - Wyspa (dawny Pogwizdów)</a>
            </td>
        </tr>
		
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego" href="http://www.youtube.com/watch?v=8Gfp4CZPeg4"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/jalowego_wyspianskiego_mc_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego" href="http://www.youtube.com/watch?v=8Gfp4CZPeg4"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego (dla mniej cieprliwych)" href="http://www.youtube.com/watch?v=EYs80x04jnw"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/jalowego_wyspianskiego_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego (dla mniej cieprliwych)" href="http://www.youtube.com/watch?v=EYs80x04jnw"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego (dla mniej cieprliwych)</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Krakowską" href="http://www.youtube.com/watch?v=hyzzK1JR3RY"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/jalowego_krakowska_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Krakowską" href="http://www.youtube.com/watch?v=hyzzK1JR3RY"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Krakowską</a>
            </td>
        </tr>

		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Ks. Krakowskiej w ul. Wyspiańskiego, Ks. Jałowego i Reymonta" href="http://www.youtube.com/watch?v=5C-HcoELD4I"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_wyspianskiego_jalowego_reymonta_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Ks. Krakowskiej w ul. Wyspiańskiego, Ks. Jałowego i Reymonta" href="http://www.youtube.com/watch?v=5C-HcoELD4I"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Ks. Krakowskiej w ul. Wyspiańskiego, Ks. Jałowego i Reymonta</a>
            </td>
        </tr>        
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Wyspiańskiego" href="http://www.youtube.com/watch?v=mDpETLyxuCo"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_wyspianskiego_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Wyspiańskiego" href="http://www.youtube.com/watch?v=mDpETLyxuCo"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Wyspiańskiego</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Ks. Jałowego" href="http://www.youtube.com/watch?v=WClWdnUELco"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_jalowego_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Ks. Jałowego" href="http://www.youtube.com/watch?v=WClWdnUELco"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Ks. Jałowego</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Reymonta" href="http://www.youtube.com/watch?v=I_WKwnPOW84"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_reymonta_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Reymonta" href="http://www.youtube.com/watch?v=I_WKwnPOW84"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Reymonta</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie - przejazd z ul. Wyspiańskiego w ul. Ks. Jałowego" href="http://www.youtube.com/watch?v=6bOMEXzlV-k"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/wyspianskiego_jalowego_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka_new" title="Skrzyżowanie - przejazd z ul. Wyspiańskiego w ul. Ks. Jałowego" href="http://www.youtube.com/watch?v=6bOMEXzlV-k"  
                   content="opis 1"
                   >Skrzyżowanie - przejazd z ul. Wyspiańskiego w ul. Ks. Jałowego</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - przejazd z al. Cieplińskiego w ul. Krakowską" href="http://www.youtube.com/watch?v=wbe98MiU9pY"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/cieplinskiego_krakowska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - przejazd z al. Cieplińskiego w ul. Krakowską" href="http://www.youtube.com/watch?v=wbe98MiU9pY"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - przejazd z al. Cieplińskiego w ul. Krakowską</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - zawracanie z ul. Krakowskiej" href="http://www.youtube.com/watch?v=M5N_Ag5mqHg"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_krakowska_ok.jpg">
                </a>
            </td>
            <td> 
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - zawracanie z ul. Krakowskiej" href="http://www.youtube.com/watch?v=M5N_Ag5mqHg"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - zawracanie z ul. Krakowskiej</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - przejazd z ul. Krakowskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=KkTVct8Ee_U"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/krakowska_marszalkowska_ok.jpg">
                </a>
            </td>
            <td>  
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - przejazd z ul. Krakowskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=KkTVct8Ee_U"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - przejazd z ul. Krakowskiej w ul. Marszałkowską</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - przejazd z ul. Marszałkowskiej w ul. Krakowską" href="http://www.youtube.com/watch?v=zSfUbkYrRRA"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/marszalkowska_krakowska_ok.jpg">
                </a>
            </td>
            <td> 
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - przejazd z ul. Marszałkowskiej w ul. Krakowską" href="http://www.youtube.com/watch?v=zSfUbkYrRRA"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - przejazd z ul. Marszałkowskiej w ul. Krakowską</a>
            </td>
        </tr>
        
         <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - ul. Sportowa" href="http://www.youtube.com/watch?v=SCK48pJzRQc"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/sportowa_ok.jpg">
                </a>
            </td>
            <td> 
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - ul. Sportowa" href="http://www.youtube.com/watch?v=SCK48pJzRQc"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - ul. Sportowa</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną - ul. Sportowa (2)" href="http://www.youtube.com/watch?v=vs6bs7TSM8s"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/sportowa2_ok.jpg">
                </a>
            </td>
            <td> 
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną - ul. Sportowa (2)" href="http://www.youtube.com/watch?v=vs6bs7TSM8s"  
                   content="opis 1"
                   > Skrzyżowanie z wyspą centralną - ul. Sportowa (2)</a>
            </td>
        </tr>

        <tr>
            <td class="szary" colspan="2" style="width: 100%">Ronda</td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo WORD - 2 zjazd z ul. Wyzwolenia w A4 " href="http://www.youtube.com/watch?v=0Eir9UL6_Rk" content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_WORD_2_zjazd_wyzwolenia_A4.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo WORD - 2 zjazd z ul. Wyzwolenia w A4 " href="http://www.youtube.com/watch?v=0Eir9UL6_Rk"  
                   content="opis 1"
                   >Rondo WORD - 2 zjazd z ul. Wyzwolenia w A4</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo WORD - 3 zjazd z ul. Warszawskiej w A4" href="http://www.youtube.com/watch?v=Z76pq3Ya2ug"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_WORD_3_zjazd_warszawska_A4.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo WORD - 3 zjazd z ul. Warszawskiej w A4" href="http://www.youtube.com/watch?v=Z76pq3Ya2ug"  
                   content="opis 1"
                   >Rondo WORD - 3 zjazd z ul. Warszawskiej w A4</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo WORD - 3 zjazd z ul. Wyzwolenia w RADOM WARSZAWA" href="http://www.youtube.com/watch?v=eeNRBFMadVk"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_WORD_3_zjazd_wyzwolenia_RADOM_WARSZAWA.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo WORD - 3 zjazd z ul. Wyzwolenia w RADOM WARSZAWA" href="http://www.youtube.com/watch?v=eeNRBFMadVk"  
                   content="opis 1"
                   >Rondo WORD - 3 zjazd z ul. Wyzwolenia w RADOM WARSZAWA</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=j1myXWLpF8w"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_warszawska_marszalkowska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=j1myXWLpF8w"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=YJZUWitcJWE"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_rycerska_warszawska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=YJZUWitcJWE"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=ZvghybGV8HI"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_marszalkowska_warszawska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=ZvghybGV8HI"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - zawracanie z ul. Marszałkowskiej" href="http://www.youtube.com/watch?v=wK4UO1sWN5g"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_zawracanie_marszalkowska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - zawracanie z ul. Marszałkowskiej" href="http://www.youtube.com/watch?v=wK4UO1sWN5g"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - zawracanie z ul. Marszałkowskiej</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=wydI0E-dmC4"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_lubelska_warszawska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=wydI0E-dmC4"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - zawracanie z Warszawskiej" href="http://www.youtube.com/watch?v=RD8DEDbOGGs"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_zawracanie_warszawska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - zawracanie z Warszawskiej" href="http://www.youtube.com/watch?v=RD8DEDbOGGs"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - zawracanie z Warszawskiej</a>
            </td> 
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=PyCoxB39jcg"  content="opis 1">
                    <img class="foto_film_mini"  src="../img/filmy/miniaturki/rondo_jp2_marszalkowska_lubelska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=PyCoxB39jcg"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Rycersiej w ul. Lubelską" href="http://www.youtube.com/watch?v=F3iII-zAfEo"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_rycerska_lubelska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Rycersiej w ul. Lubelską" href="http://www.youtube.com/watch?v=F3iII-zAfEo"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Rycersiej w ul. Lubelską</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=jP77lHvaHBM"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_warszawska_lubelska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=jP77lHvaHBM"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską</a>
            </td>
        </tr>
        
        <tr> 
            <td class="szary">
                <a class="film_mini" title="Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej" href="http://www.youtube.com/watch?v=xE9PL-HIsbw"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_warszawska_zawracanie_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej" href="http://www.youtube.com/watch?v=xE9PL-HIsbw"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej</a>
            </td>
        </tr> 
        
        
        
        <tr>
            <td class="szary" colspan="2" style="width: 100%">Zawrotki</td>
        </tr>
        
		<tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Warszawskiej 1." href="http://www.youtube.com/watch?v=52o9-D9SOxc"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/warszawska_zawrotka_1_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Warszawskiej 1." href="http://www.youtube.com/watch?v=52o9-D9SOxc"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej 1.</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Warszawskiej 2. i 3.." href="http://www.youtube.com/watch?v=aEAWZ2twJ0c"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/warszawska_zawrotka_2_3_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Warszawskiej 2. i 3.." href="http://www.youtube.com/watch?v=aEAWZ2twJ0c"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej 2. i 3.</a>
            </td>
        </tr>
		
		<tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Warszawskiej 4." href="http://www.youtube.com/watch?v=733khx46cIU"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/warszawska_zawrotka_4_160.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Warszawskiej 4." href="http://www.youtube.com/watch?v=733khx46cIU"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej 4.</a>
            </td>
        </tr>

        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie z wyspą centralną im. Pakosława - zawracanie" href="http://www.youtube.com/watch?v=l6EKOWq6TUc"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_pakoslawa_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Skrzyżowanie z wyspą centralną im. Pakosława - zawracanie" href="http://www.youtube.com/watch?v=l6EKOWq6TUc"  
                   content="opis 1"
                   >Skrzyżowanie z wyspą centralną im. Pakosława - zawracanie</a>
            </td>
        </tr>

        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie im. Pakosława - zawracanie (1)" href="http://www.youtube.com/watch?v=jc9ompqLkMA"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/skrzyzowania_pakoslawa_1_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Skrzyżowanie im. Pakosława - zawracanie (1)" href="http://www.youtube.com/watch?v=jc9ompqLkMA"  
                   content="opis 1"
                   >Skrzyżowanie im. Pakosława - zawracanie (1)</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Skrzyżowanie im. Pakosława - zawracanie (2)" href="http://www.youtube.com/watch?v=E43OgQKQTgk"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/skrzyzowania_pakoslawa_2_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Skrzyżowanie im. Pakosława - zawracanie (2)" href="http://www.youtube.com/watch?v=E43OgQKQTgk"  
                   content="opis 1"
                   >Skrzyżowanie im. Pakosława - zawracanie (2)</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Krakowskiej" href="http://www.youtube.com/watch?v=hURQixvGBAs"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_krakowska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Krakowskiej" href="http://www.youtube.com/watch?v=hURQixvGBAs"  
                   content="opis 1"
                   >Zawracanie na ul. Krakowskiej</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Lubelskiej (1) - sygnalizacja S3" href="http://www.youtube.com/watch?v=hOUJcZS69G4"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_lubelska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Lubelskiej (1) - sygnalizacja S3" href="http://www.youtube.com/watch?v=hOUJcZS69G4"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (1) - sygnalizacja S3</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary">
                <a class="film_mini" title="Zawracanie na ul. Lubelskiej (2) - sygnalizacja S3" href="http://www.youtube.com/watch?v=70gFSZMPJ2o"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_lubelska2_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Zawracanie na ul. Lubelskiej (2) - sygnalizacja S3" href="http://www.youtube.com/watch?v=70gFSZMPJ2o"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (2) - sygnalizacja S3</a>
            </td>
        </tr>
        
        <tr>
            <td class="szary" colspan="2" style="width: 100%">Przejazdy kolejowe</td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Przejazd kolejowy" href="http://www.youtube.com/watch?v=YZP7YTEc3xU"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/przejazd_kolejowy_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Przejazd kolejowy" href="http://www.youtube.com/watch?v=YZP7YTEc3xU"  
                   content="opis 1"
                   >Przejazd kolejowy</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Przejazd kolejowy - ul. Miłocińska (1)" href="http://www.youtube.com/watch?v=2E6XR5VtUzE"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/przejazd_kolejowy_milocinska_2_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Przejazd kolejowy - ul. Miłocińska (1)" href="http://www.youtube.com/watch?v=2E6XR5VtUzE"  
                   content="opis 1"
                   >Przejazd kolejowy - ul. Miłocińska (1)</a>
            </td>
        </tr>
        <tr>
            <td class="szary">
                <a class="film_mini" title="Przejazd kolejowy - ul. Miłocińska (2)" href="http://www.youtube.com/watch?v=IFpzzMf5QPc"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/przejazd_kolejowy_milocinska_2_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Przejazd kolejowy - ul. Miłocińska (2)" href="http://www.youtube.com/watch?v=IFpzzMf5QPc"  
                   content="opis 1"
                   >Przejazd kolejowy - ul. Miłocińska (2)</a>
            </td>
        </tr>
         <tr>
            <td class="szary">
                <a class="film_mini" title="Przejazd kolejowy - Rzeszów z ul. Warszawskiej w Miłocinską i z ul. Przy Torze w ul. Warszawską" href="http://www.youtube.com/watch?v=evBZtGGCuZM"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/przejazd_kolejowy_warszawska_milocinska_ok.jpg">
                </a>
            </td>
            <td>
                <a class="kamerka" title="Przejazd kolejowy - Rzeszów z ul. Warszawskiej w Miłocinską i z ul. Przy Torze w ul. Warszawską" href="http://www.youtube.com/watch?v=evBZtGGCuZM"  
                   content="opis 1"
                   >Przejazd kolejowy - Rzeszów z ul. Warszawskiej w Miłocinską i z ul. Przy Torze w ul. Warszawską</a>
            </td>
        </tr>
        
        <tr>
            <td class="pomar" colspan="2" style="width: 100%">Trasy egzaminacyjne z eLeczką AUTO TURBO w roli głównej</td>
        </tr>

        <tr>
            <td class="szary" colspan="2" style="width: 100%">Ronda</td>
        </tr>
        <tr>             
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=fK3YY56yFAA"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_marszalkowska_warszawska.jpg">
                </a>          
            </td>             
            
            
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=fK3YY56yFAA"  content="opis 1">
                    Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską</a>             
            </td>         
        </tr>
        <tr>       
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej" href="http://www.youtube.com/watch?v=b22CIttygzU"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_zawracanie_warszawska.jpg">
                </a>       
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej" href="http://www.youtube.com/watch?v=b22CIttygzU" 
                   content="opis 2"
                   >Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej
                </a>             
            </td>         
        </tr>
        <tr>         
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=PfEfBTEWEOQ"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_marszalkowska_lubelska.jpg">
                </a>       
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=PfEfBTEWEOQ" 
                   content="opis 2"
                   >Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską
                </a>             
            </td>         
        </tr>
        <tr>          
            <td class="szary">                 

                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=dyE0QvoeNeU"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_lubelska_warszawska.jpg">
                </a>            
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=dyE0QvoeNeU"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską</a>             
            </td>         
        </tr>
        <tr>      
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - zawracanie z ul. Lubelskiej" href="http://www.youtube.com/watch?v=Cby0oVuqh1M"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_zawracanie_lubelska.jpg">
                </a>       
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - zawracanie z ul. Lubelskiej" href="http://www.youtube.com/watch?v=Cby0oVuqh1M"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - zawracanie z ul. Lubelskiej</a>             
            </td>         
        </tr>
        <tr>       
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=J7bTCW3ubns"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_warszawska_lubelska.jpg">
                </a>       
            </td>             

            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską" href="http://www.youtube.com/watch?v=J7bTCW3ubns"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską</a>             
            </td>         
        </tr>
        <tr>         
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=dRw7Fqqph8s"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_warszawska_marszalkowska.jpg">
                </a>       
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską" href="http://www.youtube.com/watch?v=dRw7Fqqph8s"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską</a>             
            </td>         
        </tr>
        <tr>     
            <td class="szary">                 
                <a class="film_mini" title="Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=oZOMdo7Kl3g"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/rondo_jp2_rycerska_warszawska.jpg">
                </a>        
            </td>             
            <td>                 
                <a class="kamerka" title="Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską" href="http://www.youtube.com/watch?v=oZOMdo7Kl3g"  
                   content="opis 1"
                   >Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską</a>             
            </td>
        </tr>

       
        <tr>
            <td class="szary" colspan="2" style="width: 100%">Zawrotki</td>
        </tr>


        <tr>            
            <td class="szary">   
                <a class="film_mini" title="Zawracanie na ul. Warszawskiej (3)" href="http://www.youtube.com/watch?v=X0Bl7GRNEjg"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_warszawska_3.jpg">
                </a> 
            </td>             
            <td>                 
                <a class="kamerka" title="Zawracanie na ul. Warszawskiej (3)" href="http://www.youtube.com/watch?v=X0Bl7GRNEjg"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej (3)</a>             
            </td>
        </tr>
        <tr>      
            <td class="szary">                 
                <a class="film_mini" title="Zawracanie na ul. Warszawskiej (5)" href="http://www.youtube.com/watch?v=67kejVjAjfE"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_warszawska_5.jpg">
                </a>
            </td>             
            <td>                 
                <a  class="kamerka" title="Zawracanie na ul. Warszawskiej (5)" href="http://www.youtube.com/watch?v=67kejVjAjfE"  
                    content="opis 1"
                    >Zawracanie na ul. Warszawskiej (5)</a>             
            </td>
        </tr>
        <tr>       
            <td class="szary">                 
                <a class="film_mini" title="Zawracanie na ul. Lubelskiej (1)" href="http://www.youtube.com/watch?v=OQZL8CP33XM"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_lubelska_1.jpg">
                </a>
            </td>             
            <td>                 
                <a class="kamerka" title="Zawracanie na ul. Lubelskiej (1)" href="http://www.youtube.com/watch?v=OQZL8CP33XM"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (1)</a>             
            </td>
        </tr>
        <tr>          
            <td class="szary">                 
                <a class="film_mini" title="Zawracanie na ul. Lubelskiej (2)" href="http://www.youtube.com/watch?v=xuXhuYI_kK4"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_lubelska_2.jpg">
                </a>
            </td>             
            <td>                 
                <a class="kamerka" title="Zawracanie na ul. Lubelskiej (2)" href="http://www.youtube.com/watch?v=xuXhuYI_kK4"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (2)</a>             
            </td>
        </tr>
        <tr>       
            <td class="szary">                 
                <a class="film_mini" title="Skrzyżowanie im. Pakosława - zawracanie" href="http://www.youtube.com/watch?v=FTehBcvQtlE"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/skrzyzowanie_pakoslawa_zawracanie.jpg">
                </a>
            </td>             
            <td>                 
                <a class="kamerka" title="Skrzyżowanie im. Pakosława - zawracanie" href="http://www.youtube.com/watch?v=FTehBcvQtlE" 
                   content="opis 2"
                   >Skrzyżowanie im. Pakosława - zawracanie</a>             
            </td>
        </tr>
        
        <tr>     
            <td class="szary">                 
                <a class="film_mini" title="Zawracanie na ul. Krakowskiej" href="http://www.youtube.com/watch?v=lPlZLuOWOjo"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/zawracanie_krakowska.jpg">
                </a>
            </td>             
            <td>                 
                <a class="kamerka" title="Zawracanie na ul. Krakowskiej" href="http://www.youtube.com/watch?v=lPlZLuOWOjo" 
                   content="opis 2"
                   >Zawracanie na ul. Krakowskiej</a>             
            </td>
        </tr>


        <tr>
            <td class="szary" colspan="2" style="width: 100%">Przejazdy kolejowe</td>
        </tr>


 

        <tr>             
            <td class="szary">                 
                <a class="film_mini" title="Przejazd kolejowy" href="http://www.youtube.com/watch?v=T4zxh19cPZg"  content="opis 1">
                    <img class="foto_film_mini" title="miniaturka" src="../img/filmy/miniaturki/przejazd_kolejowy.jpg">
                </a>
            </td>             
            <td>                 
                <a class="kamerka" title="Przejazd kolejowy" href="http://www.youtube.com/watch?v=T4zxh19cPZg"  
                   content="opis 1"
                   >Przejazd kolejowy</a>             
            </td>
        </tr>


    </table>


    <!--
<h2>Trasy egzaminacyjne z perspektywy kursanta</h2>
<div class="youtube">
   
    <ul>   
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=zq_I6COg5gU"  
               content="opis 1"
               >Zawracanie na ul. Warszawskiej (5)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=jc9ompqLkMA"  
               content="opis 1"
               >Skrzyżowanie im. Pakosława - zawracanie (1)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=E43OgQKQTgk"  
               content="opis 1"
               >Skrzyżowanie im. Pakosława - zawracanie (2)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=hURQixvGBAs"  
               content="opis 1"
               >Zawracanie na ul. Krakowskiej</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=dSlGpIc2L6E"  
               content="opis 1"
               >"Kwadrat śmierci" - przejazd przez ul. Partyzantów, ul. Piękną, ul. Husarską i ul. Jasną</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=YZP7YTEc3xU"  
               content="opis 1"
               >Przejazd kolejowy - ul. Miłocińska</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=2E6XR5VtUzE"  
               content="opis 1"
               >Przejazd kolejowy - ul. Miłocińska (1)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=IFpzzMf5QPc"  
               content="opis 1"
               >Przejazd kolejowy - ul. Miłocińska (2)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=Qm1R33CU5js"  
               content="opis 1"
               >Pogwizdów Nowy (1)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=yEEs_l6vNrY"  
               content="opis 1"
               >Pogwizdów Nowy (2)</a>
        </li>
        <li><a class="kamerka" href="http://www.youtube.com/watch?v=cFRD_AdncTA"  
               content="opis 1"
               >Pogwizdów Nowy (3)</a>
        </li>
        
    </ul>
    
</div>
    
    
<h2>Ronda</h2>
<div class="youtube">
   
    <ul>           
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=fK3YY56yFAA"  
               content="opis 1"
               >Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Warszawską</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=b22CIttygzU" 
               content="opis 2"
               >Rondo im. Jana Pawła II - zawracanie z ul. Warszawskiej</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=PfEfBTEWEOQ" 
               content="opis 2"
               >Rondo im. Jana Pawła II - z ul. Marszałkowskiej w ul. Lubelską</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=dyE0QvoeNeU"  
               content="opis 1"
               >Rondo im. Jana Pawła II - z ul. Lubelskiej w ul. Warszawską</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=Cby0oVuqh1M"  
               content="opis 1"
               >Rondo im. Jana Pawła II - zawracanie z ul. Lubelskiej</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=J7bTCW3ubns"  
               content="opis 1"
               >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Lubelską</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=dRw7Fqqph8s"  
               content="opis 1"
               >Rondo im. Jana Pawła II - z ul. Warszawskiej w ul. Marszałkowską</a></li>
        <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=oZOMdo7Kl3g"  
               content="opis 1"
               >Rondo im. Jana Pawła II - z ul. Rycerskiej w ul. Warszawską</a></li>
    </ul>
    
</div>
    
    <h2>Skrzyżowania</h2> 
    <div class="youtube">

        <ul>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=s8SS3gAe6YY"  
                   content="opis 26""
                   >"Kwadrat śmierci" - przejazd przez ul. Partyzantów, ul. Piękną, ul. Husarską i ul. Jasną</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=RbquLArBMJo"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Wyspiańskiego</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=RwKyZ8J32mY"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Krakowskiej w ul. Wyspiańskiego</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=f_BHwY69238"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Reymonta w ul. Ks. Jałowego</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=IksRp0djp-A"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Wyspiańskiego w ul. Ks. Jałowego</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=NWA2Z2_F5yo"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Krakowską</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=sxbvS3TylK8"  
                   content="opis 26""
                   >Skrzyżowanie - przejazd z ul. Ks. Jałowego w ul. Reymonta</a></li>
        </ul>

    </div>
    
    <h2>Zawrotki</h2>
    <div class="youtube">

        <ul>           
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=X0Bl7GRNEjg"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej (3)</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=67kejVjAjfE"  
                   content="opis 1"
                   >Zawracanie na ul. Warszawskiej (5)</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=OQZL8CP33XM"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (1)</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=xuXhuYI_kK4"  
                   content="opis 1"
                   >Zawracanie na ul. Lubelskiej (2)</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=FTehBcvQtlE" 
                   content="opis 2"
                   >Skrzyżowanie im. Pakosława - zawracanie</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=1SOy9VSy1Qg" 
                   content="opis 2"
                   >Pogwizdów Nowy - zawracanie</a></li>
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=lPlZLuOWOjo" 
                   content="opis 2"
                   >Zawracanie na ul. Krakowskiej</a></li>
        </ul>

    </div>

    <h2>Przejazdy kolejowe</h2>
    <div class="youtube">

        <ul>           
            <li><a class="kamerka" title="" href="http://www.youtube.com/watch?v=T4zxh19cPZg"  
                   content="opis 1"
                   >Przejazd kolejowy</a></li>
        </ul>

    </div>

    -->
    
</div>

<script type="text/javascript" >
    function jumpScroll() {
        window.scroll(0,485); // horizontal and vertical scroll targets
    }
    $('.kamerka_szary').click(function(e){ 
        
        tytul = "";
        tytul = $(this).text();
        //// opisik = "";
        // $('#tytul').text(tytul);
        ////  $('#opisik').text(opisik);
        //$('#opis').attr('style', "background-color: #fff;");
        //$('#tytul').attr('style', "background-color: #fff;");
        //$('#tv iframe').slideUp('slow');
        //$('#tv img').slideDown('slow');
        jumpScroll();
        return false;
    });
    
    /*
    $('.kamerka, .kamerka_new, .film_mini').click(function(e){
        $('#tv iframe').attr('src',$(this).attr('href'));
        
        tytul = $(this).text();
        ////  opisik = $(this).attr('content');
        //  $('#opis').attr('style', "background-color: #ffd;");
        //  $('#tytul').attr('style', "background-color: #ffb;");
        //  $('#tytul').text(tytul);
        //  $('#opisik').text(opisik);
        
        //alert(cont);
        
        $('#tv img').slideUp('slow');
        $('#tv iframe').slideDown('slow');
        jumpScroll();
        return false;
    });*/
    
    
</script>

  