<!-- Carousel Start -->
        <div class="container-fluid p-0 mb-5">
            <div class="owl-carousel header-carousel position-relative">
                <div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_1.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Prawo jazdy na Twoich zasadach</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Zyskaj 200 zł zniżki na kurs!</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Dla uczniów i studentów – taniej i wygodniej!</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a><!----------------- tu przekierowanie do telefonu------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a> <!--------------------- tu przekierowanie do zapisów online-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_2.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Ucz się skutecznie – kiedy chcesz</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Obejrzyj filmy o jeździe, egzaminie i przepisach</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zobacz wszystko, zanim wsiądziesz do samochodu</p>
                                    <a href="" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Filmy</a> <!----------------- tu przekierowanie do filmów ------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_3.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Trenuj tam, gdzie zdajesz</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Plac manewrowy WORD w cenie kursu</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zyskaj pewność jazdy na egzaminie praktycznym</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a><!----------------- tu przekierowanie do telefonu------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a><!--------------------- tu przekierowanie do zapisów online-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_4.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Szkoła w sercu miasta</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Świetna lokalizacja – wszędzie blisko</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Bez problemu dotrzesz do nas autobusem, pociagiem lub pieszo</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a><!----------------- tu przekierowanie do telefonu------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a><!--------------------- tu przekierowanie do zapisów online-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_5.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Nauka jazdy na najwyższym poziomie</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Doświadczeni instruktorzy, nowoczesne auta</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zdaj bez stresu – ucz się z najlepszymi</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a><!----------------- tu przekierowanie do telefonu------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a><!--------------------- tu przekierowanie do zapisów online-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/baner_auto_turbo_6.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Zacznij kurs już dziś</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Zrób pierwszy krok do prawa jazdy</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Z nami zdasz pewnie i bez nerwów</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Nie czekaj! Zadzwoń</a><!----------------- tu przekierowanie do telefonu------>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a><!--------------------- tu przekierowanie do zapisów online-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel End -->
    
    
        <!-- DLACZEGO MY -------------------------------------Service Start -->
        <div class="container-xxl py-5" id="dlaczego_my">
            <div class="container">
    		
    			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">O nas</h6>
                    <h1 class="mb-5">Dlaczego my?</h1>
                </div>
    <!-- stara wersja statyczna---------------------------			
                <div class="row g-4">
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chalkboard-teacher text-primary mb-4"></i>
                                <h5 class="mb-3">Cierpliwi i doświadczeni instruktorzy</h5>
                                <p>Profesjonalna kadra potrafi w przystępny sposób przekazać wiedzę i stworzyć komfortową atmosferę do nauki, nawet dla najbardziej zestresowanych kursantów</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
                                <h5 class="mb-3">Wysoka zdawalność</h5>
                                <p>Kursanci AUTO TURBO osiągają świetne wyniki na egzaminach państwowych, co świadczy o skuteczności szkolenia naszego ośrodka</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-trophy text-primary mb-4"></i>
                                <h5 class="mb-3">Najwyżej w rankingach</h5>
                                <p>Szkoła regularnie zajmuje czołowe miejsca w ogólnopolskich rankingach szkół nauki jazdy w Rzeszowie, co potwierdza jej renomę</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-car text-primary mb-4"></i>
                                <h5 class="mb-3">Nowoczesna flota pojazdów</h5>
                                <p>Jazdy odbywają się na nowoczesnych autach (z klimatyzacją i czujnikami parkowania) identycznych jak te używane podczas egzaminów w WORD Rzeszów</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    		<div class="container">
                <div class="row g-4">
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.9s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-film text-primary mb-4"></i>
                                <h5 class="mb-3">Filmy instruktażowe</h5>
                                <p>Dodatkowe materiały wideo pomagają lepiej zrozumieć przepisy i manewry egzaminacyjne, co znacznie ułatwia naukę</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="1.1s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa fa-map-marker-alt me-3 text-primary mb-4"></i>
                                <h5 class="mb-3">Świetna lokalizacja</h5>
                                <p>AUTO TURBO mieści się tuż obok dworca PKP i PKS, co czyni ją idealnym wyborem dla osób dojeżdżających z okolicznych miejscowości</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="1.3s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-clock text-primary mb-4"></i>
                                <h5 class="mb-3">Elastyczne godziny jazd</h5>
                                <p>Możliwość umawiania się na jazdy codziennie w godzinach od 7:00 do 21:00 oraz w weekendy</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="1.5s">
                        <div class="service-item text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-thumbs-up text-primary mb-4"></i>
                                <h5 class="mb-3">Setki pozytywnych opinii</h5>
                                <p>Zadowoleni kursanci chętnie dzielą się pozytywnymi recenzjami w Internecie, co mówi samo za siebie</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    		
    		------------------------------------------ koniec starej wersji statyczne-->
    		
    		
    			<div class="owl-carousel testimonial-carousel position-relative">
    			  
    				<div class="testimonial-item text-center">
    					<div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chalkboard-teacher text-primary mb-4"></i>
                                <h5 class="mb-3">Cierpliwi i doświadczeni instruktorzy</h5>
                                <p>Profesjonalna kadra potrafi w przystępny sposób przekazać wiedzę i stworzyć komfortową atmosferę do nauki, nawet dla najbardziej zestresowanych kursantów</p>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
                                <h5 class="mb-3">Wysoka zdawalność</h5>
                                <p>Kursanci AUTO TURBO osiągają świetne wyniki na egzaminach państwowych, co świadczy o skuteczności szkolenia naszego ośrodka</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-trophy text-primary mb-4"></i>
                                <h5 class="mb-3">Najwyżej w rankingach</h5>
                                <p>Szkoła regularnie zajmuje czołowe miejsca w ogólnopolskich rankingach szkół nauki jazdy w Rzeszowie, co potwierdza jej renomę</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-car text-primary mb-4"></i>
                                <h5 class="mb-3">Nowoczesna flota pojazdów</h5>
                                <p>Jazdy odbywają się na nowoczesnych autach (z klimatyzacją i czujnikami parkowania) identycznych jak te używane podczas egzaminów w WORD Rzeszów</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">>
                            <div class="p-4">
                                <i class="fa fa-3x fa-film text-primary mb-4"></i>
                                <h5 class="mb-3">Filmy instruktażowe</h5>
                                <p>Dodatkowe materiały wideo pomagają lepiej zrozumieć przepisy i manewry egzaminacyjne, co znacznie ułatwia naukę</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa fa-map-marker-alt me-3 text-primary mb-4"></i>
                                <h5 class="mb-3">Świetna lokalizacja</h5>
                                <p>AUTO TURBO mieści się tuż obok dworca PKP i PKS, co czyni ją idealnym wyborem dla osób dojeżdżających z okolicznych miejscowości</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-clock text-primary mb-4"></i>
                                <h5 class="mb-3">Elastyczne godziny jazd</h5>
                                <p>Możliwość umawiania się na jazdy codziennie w godzinach od 7:00 do 21:00 oraz w weekendy</p>
                            </div>
                        </div>
                    </div>			
                    <div class="testimonial-item text-center">
    					<div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-thumbs-up text-primary mb-4"></i>
                                <h5 class="mb-3">Setki pozytywnych opinii</h5>
                                <p>Zadowoleni kursanci chętnie dzielą się pozytywnymi recenzjami w Internecie, co mówi samo za siebie</p>
                            </div>
                        </div>
                    </div>
                    
                  
                    
                </div>
    			
    			
    			
    			
    			
    			
    		</div>
    	</div>
        <!-- Service End -->
    
    
    
        <!--CENNIK - Kursy prawa jazdy ---------->
        <div class="container-xxl py-5" id="cennik">
            <div class="container">
    		
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                    <h1 class="mb-5">Kursy prawa jazdy</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
					<!-- KURS PODSTATOWY -->
					<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
						
                        <div class="ramka">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_kurs_podstawowy.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    						
								<div class="flex-fill text-center border-bottom py-2 px-3">
									<h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
									<h3 class="mb-0 text-primary">3 199 PLN</h3>
									<small class="mb-0 text-primary">(uczniowie i studenci)</small>
								</div>
								<div class="flex-fill text-center border-bottom py-2">
									<h4 class="mb-0">3 399 PLN</h4>
									<small>(pozostali)</small>
								</div>
								<div class="flex-fill text-center border-bottom py-2">
									<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
									<h4 class="mb-0">PODSTAWOWY</h4>
								</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
    								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
    								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
    								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
    								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
    								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
    								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>WYKŁADY: 2 tygodnie</small>
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>JAZDY: ok. 5-9 tygodni</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
    					</div>
                    </div>
    				
					<!-- KURS PRAKTYCZNY -->
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_kurs_praktyczny.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    						
    						<div class="flex-fill text-center border-bottom py-2 px-3">
    						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                                <h3 class="mb-0 text-primary">2 999 PLN</h3>
    							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
    						</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">3 199 PLN</h4>
    							<small>(pozostali)</small>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
    							<h4 class="mb-0">PRAKTYCZNY</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
    								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
    								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
    								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
    								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <!--<small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>WYKŁADY: 2 tygodnie</small>-->
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 5-9 tygodni</small>
                            </div>
    						<div class="d-flex border-top">
                                <!--<small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>WYKŁADY: 2 tygodnie</small>-->
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
					<!-- KURS EKSPRESOWY -->
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_kurs_ekspresowy.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    						
    						<div class="flex-fill text-center border-bottom py-2 px-3">
    						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                                <h3 class="mb-0 text-primary">3 999 PLN</h3>
    							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
    						</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">4 199 PLN</h4>
    							<small>(pozostali)</small>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
    							<h4 class="mb-0">EKSPRESOWY</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
    								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
    								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
    								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
    								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
    								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
    								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 30 dni</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
					<!-- KURS EKSPRESOWY PRAKTYCZNY -->
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_kurs_ekspresowy_praktyczny.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    						
    						<div class="flex-fill text-center border-bottom py-2 px-3">
    						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                                <h3 class="mb-0 text-primary">3 799 PLN</h3>
    							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
    						</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">3 999 PLN</h4>
    							<small>(pozostali)</small>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
    							<h4 class="mb-0">EKSPRESOWY PRAKTYCZNY</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
    								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
    								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
    								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
    								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 12-15 dni</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>

    		   </div>
    		   
    
    			<div class="row g-4 justify-content-center mt-1">
    			
					<!-- RATY -->
    				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.1s">
    					<div class="course-item bg-light d-flex flex-column h-100">
    						<div class="text-left p-4 pb-0">
    							<h5>Opłata za kurs może być wniesiona w całości lub w systemie ratalnym (RATY 0%)</h5>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<div class="text-center p-4 text-white"><b>I</b></div>
    								</div>
    								<div class="ms-3">
    
    									<p class="mb-0"><b>I rata - 800 zł</b> - przy zapisie na kurs</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<div class="text-center p-4 text-white"><b>II</b></div>
    								</div>
    								<div class="ms-3">
    									<p class="mb-0"><b>II rata - 800 zł</b> - przed końcem zajęć teoretycznych</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<div class="text-center p-4 text-white"><b>III</b></div>
    								</div>
    								<div class="ms-3">
    									<p class="mb-0"><b>III rata - 800 zł</b> - przed 10 godziną jazdy</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<div class="text-center p-4 text-white"><b>IV</b></div>
    								</div>
    								<div class="ms-3">
    									<p class="mb-0"><b>IV rata - 799 zł</b> - przed 20 godziną jazdy</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<div class="text-center p-4 text-white"><b>V</b></div>
    								</div>
    								<div class="ms-3">
    									<p class="mb-0"><b>V rata - pozostała kwota</b> - przed 30 godziną jazdy</p>
    								</div>
    							</div>
    						</div>
    					</div>				
    				</div>
    				
					<!-- DANE DO PRZELEWU -->
    				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.3s">
    				
    					<div class="course-item bg-light d-flex flex-column h-100">
    						<div class="text-left p-4 pb-0">
    							<h5>Dane do przelewu</h5>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<i class="fa fa-user text-white"></i>
    								</div>
    								<div class="ms-3">
    									<h5 class="text-primary">Nazwa odbiorcy:</h5>
    									<p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<i class="fa fa-map-marker-alt text-white"></i>
    								</div>
    								<div class="ms-3">
    									<h5 class="text-primary">Adres odbiorcy:</h5>
    									<p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<i class="fa fa-university text-white"></i>
    								</div>
    								<div class="ms-3">
    									<h5 class="text-primary">Nr rachunku odbiorcy:</h5>
    									<p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
    								</div>
    							</div>
    							<div class="d-flex align-items-center mb-3">
    								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
    									<i class="fa fa-pencil-alt text-white"></i>
    								</div>
    								<div class="ms-3">
    									<h5 class="text-primary">Tytułem:</h5>
    									<p class="mb-0">Imię i nazwisko kursanta - kurs prawa jazdy</p>
    								</div>
    							</div>
    						</div>
    					</div>
    				
    				</div>
    			</div>
    
    
    		</div>
    	</div>
    	
    	<!--CENNIK - Promocje ---------->
        <div class="container-xxl py-5" id="cennik_promocje">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                    <h1 class="mb-5">Promocje</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			<div class="conteiner_flash">
    			
    			 <div class="row g-4">
    			 
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
    				<div class="item_flash d-flex flex-column h-100">
                        <div class="service-item text-center pt-3 d-flex flex-column h-100">
                            <div class="p-4">
                                <i class="fa fa-3x fa-user-graduate text-primary mb-4"></i>
                                <h5 class="mb-3 text-primary">200 zł zniżki</br>dla uczniów i studentów!</h5>
                                <p>Zdobądź zniżkę 200 zł na kurs prawa jazdy! Jeśli jesteś uczniem lub studentem, skorzystaj z tej wyjątkowej oferty. Zapisz się do nas i zaoszczędzisz na szkoleniu</p>
    							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i> Tylko dla uczniów i studentów</p>
                            </div>
                        </div>
                    </div>
    				</div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
    				<div class="item_flash d-flex flex-column h-100">
                        <div class="service-item text-center pt-3 d-flex flex-column h-100">
                            <div class="p-4">
                                <i class="fa fa-3x fa-user-friends text-primary mb-4"></i>
                                <h5 class="mb-3 text-primary">1 h jazdy GRATIS</br>dla 2 osób</h5>
                                <p>Zapisz się na kurs prawa jazdy razem z przyjacielem i odbierz 1 godzinę jazdy GRATIS! Kursy będą bardziej motywujące, a Ty zaoszczędzisz na swojej nauce</p>
    							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Oferta dla dwóch osób</p>
                            </div>
    					</div>
                    </div>
                    </div>
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
    				<div class="item_flash d-flex flex-column h-100">
                        <div class="service-item text-center pt-3 d-flex flex-column h-100">
                            <div class="p-4">
                                <i class="fa fa-3x fa-users text-primary mb-4"></i>
                                <h5 class="mb-3 text-primary">2 h jazdy GRATIS</br>dla 3 osób</h5>
                                <p>Zapisz 3 osoby na kurs prawa jazdy, a każda z nich otrzyma 2 godziny jazdy GRATIS. Więcej osób, większa zniżka – to doskonała okazja, by zaoszczędzić!</p>
    							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Oferta dla trzech osób</p>
                            </div>
                        </div>
    				</div>
                    </div>
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
    				<div class="item_flash d-flex flex-column h-100">
                        <div class="service-item text-center pt-3 d-flex flex-column h-100">
                            <div class="p-4">
                                <i class="fa fa-3x fa-gift text-primary mb-4"></i>
                                <h5 class="mb-3 text-primary">Poleć i ZYSKAJ</h5>
                                <p>Poleć naszą szkołę jazdy znajomym i odbierz 1 godzinę jazdy GRATIS za każdą poleconą osobę, która zapisze się na kurs. Zyskaj bonusy i pomóż innym na drodze do zdobycia prawa jazdy!</p>
    							<p class="offer text-primary"><i class="fa fa-hand-point-right text-primary me-2"></i>  Dla osób polecających kursy</p>
                            </div>
                        </div>
    				</div>
                    </div>
    			
    			
    			</div>
    			
    			</div>
    			
    					
    
    			
    			
    			</div>
    		</div>
    	</div>
    	
    
    	<!--CENNIK - Jazdy-->	
    	<div class="container-xxl py-5" id="cennik_jazdy">
    		
    		<div class="container">
    		   	
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                    <h1 class="mb-5">Jazdy doszkalające</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_1h.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">110 PLN</h4>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Jazda doszkalajaca kat. B</h4>
    							<h5 class="mb-0">1 godzina</h5>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>1 godz.</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_2h.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">220 PLN</h4>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
    							<h5 class="mb-0">2 godziny</h5>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość jazdy na plac manerwowy</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_2h_WORD.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">290 PLN</h4>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
    							<h5 class="mb-0">2 godziny + WORD</h5>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych (90 min)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po placu manewrowym WORD Rzeszów (30 min)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić szczególnie przez egzaminem</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="img/cennik_kursy/auto_turbo_jazda_10h.jpg" alt="">
                            </div>
                            <div class="text-center p-4 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-0">1000 PLN</h4>
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Jazda doszkalająca kat. B</h4>
    							<h5 class="mb-0">PAKIET 10 godzin</h5>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość wjazdu na plac manewrowy</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>10 godz.</small>
                            </div>
    						<div class="d-flex border-top">
                                <small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
                            </div>
    
                        </div>
                    </div>
    				
    		   </div>
    
    
    	   </div>
        </div>
        <!-- Courses End -->
    
    
    <!--ZAPISY - Jak rozpocząc? ---------->
        <div class="container-xxl py-5" id="zapisy_jak_rozpoczac">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Zapisy</h6>
                    <h1 class="mb-5">Jak rozpocząć kurs?</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			
    			
    			 <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
    				<div class="service-item d-flex flex-column h-100">
    					<div class="text-center p-4 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<img src="img/ikonki_numery/1.png">
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Zapis na kurs</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom">Na kurs prawa jazdy można zapisać się na kilka sposobów:</p>
    						<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i>Formularz zgłoszeniowy</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-map-marker-alt text-primary me-2"></i>Osobiście</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="kontakt" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Rzeszów, Bardowskiego 1C</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-phone text-primary me-2"></i>Telefonicznie</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="tel:+48605330708" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">605330708</a></small>
    						</div>
    					</div>			
    				</div>							
                </div>
    			
    			<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.2s">
    				<div class="service-item d-flex flex-column h-100">
    					<div class="text-center p-4 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<img src="img/ikonki_numery/2.png">
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Dokumenty</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom">Będą potrzebne następujące dokumenty:</p>
    						<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i><b>Wniosek o wydanie prawa jazdy</b> 
							<small>(dostępny również w ośrodku)</small>
							</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="../doci/2025_zgoda.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-file-medical text-primary me-2"></i><b>Orzeczenie lekarskie</b> <small>stwierdzające brak przeciwwskazań zdrowotnych do kierowania pojazdami (badania można zrobić w OSK Auto Turbo)</small>
							</p>
    						<p class="mb-0 border-top"><i class="fa fa-id-badge text-primary me-2"></i><b>Zdjęcie</b>
							<small>(aktualne, kolorowe) do prawa jazdy o wymiarach 3,5 x 4,5 cm</small>
							</p>
    						<p class="mb-0 border-top"><i class="fa fa-file-signature text-primary me-2"></i><b>Zgoda rodziców</b>
							<small>dotyczy osób przed ukończeniem 18-tego roku życia</small> 
							<small>(dostepna również w ośrodku)</small>
							</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="../doci/2025_zgoda.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
    						</div>
    						
    					</div>			
    				</div>							
                </div>
    			
    			<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
    				<div class="service-item d-flex flex-column h-100">
    					<div class="text-center p-4 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<img src="img/ikonki_numery/3.png">
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Założenie PKK</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom">PKK jest to numer, który zakłada się w <b>Wydziale Komunikacji</b> odpowiednim dla miejsca zameldowania</p>
    						<p class="mb-0 border-bottom">Aby go uzyskać należy złożyć w urzędzie przygotowane wcześniej <b>dokumenty</b> (patrz pkt. 2.)</p>
    					</div>			
    				</div>							
                </div>
    			
    			<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.4s">
    				<div class="service-item d-flex flex-column h-100">
    					<div class="text-center p-4 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<img src="img/ikonki_numery/4.png">
                            </div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Przekazanie PKK </br>do AUTO TURBO</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom"><b>Po odbiorze numeru PKK</b> z Wydziału Komunikacji należy go przekazać <b>do biura OSK AUTO TURBO</b> lub przesłać SMS</p>
    					</div>			
    				</div>							
                </div>
    
    			
    			</div>
    		</div>
    	</div>
    	
    <!--ZAPISY - Na kurs ---------->
        <div class="container-xxl py-5" id="zapisy_na_kurs">
            <div class="container">
                <div class="row g-4 justify-content-center">
    				<div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.1s" style="min-height: 50px;">
    					<div class="text-center data-wow-delay="0.1s">
    						<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się na kurs ON-LINE</a>
    					</div>
    				</div>
    				<div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.1s" style="min-height: 50px;">
    					<div class="text-center data-wow-delay="0.1s">
    						<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Masz pytania? Zadzwoń</a>
    					</div>
    				</div>
    							
    			</div>
    		</div>
    	</div>
    	
    <!--SZKOLENIE - Teoria ---------->
        <div class="container-xxl py-5" id="szkolenie_teoretyczne">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                    <h1 class="mb-5">Teoria</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			<p class="mb-0 border-bottom">Zajęcia teoretyczne odbywają się cyklicznie w <b>poniedziałki</b>, <b>środy</b> i <b>czwartki</b> o godz. <b>17.00</b> w siedzibie naszej szkoły (Rzeszów, ul. Bardowskiego 1C, I piętro nad barberem).</p>
    			<p class="mb-0">Całość teorii podzielona jest na siedem bloków temetycznych:</p>
    	
    			
    			<div class="row g-4 justify-content-left">
    			
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 1.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Wiadomości ogólne i przepisy szczegółowe</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Podstawowe pojęcia i definicje oraz ogólne zasady poruszania się po drogach</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Prędkość i hamowanie</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przejazdy kolejowe</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zachowanie się wobec pieszych</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.2s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 2.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Znaki i sygnały drogowe</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki drogowe – wiadomości ogólne</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki ostrzegawcze</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki zakazu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki nakazu, informacyjne, kierunku i miejscowości, poziome</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 3.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Przepisy szczegółowe </h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Włączanie się do ruchu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wymijanie, omijanie, cofanie</p> 
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zmiana kierunku jazdy i pasa ruchu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zawracanie</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.4s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 4.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Przepisy szczegółowe </h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wyprzedzanie</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zatrzymanie i postój</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Holowanie</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Obowiązkowe wyposażenie pojazdu</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 5.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Przepisy szczegółowe</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przecinanie kierunków ruchu i pierwszeństwo przejazdu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu kierowanym</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu okrężnym</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.6s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 6.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Zasady egzaminu państwowego</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>ogólne zasady egzaminu państwowego – zapoznanie się z obsługą pojazdu</p>
    								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>egzamin teoretyczny</p>
    								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>egzamin praktyczny</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 7.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Pierwsza pomoc z ratownikiem medycznym</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Szkolenie teoretyczne</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zajęcia praktyczne</p>
    							</div>
                        </div>
                    </div>
    				
    
    
    		   </div>
    		   
    		   
    			
    			</div>
    		</div>
    	</div>
    	
    <!--SZKOLENIE - Praktyka ---------->
        <div class="container-xxl py-5" id="szkolenie_praktyczne">
    			
    		<div class="container">
                <div class="row g-5">
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                        <div class="position-relative h-100">
                            <img class="img-fluid position-absolute w-100 h-100" src="img/galeria/auto_turbo_plac_manewrowy.jpg" alt="" style="object-fit: cover;">
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s">
                        <h6 class="section-title bg-white text-start text-primary pe-3">Szkolenie</h6>
                        <h1 class="mb-4">Praktyka</h1>
                        <p class="mb-4"><b>Po ukończeniu zajęć teoretycznych</b> (7 spotkań, około 2 tygodnie) uczestnik kursu rozpoczyna <b>zajęcia praktyczne</b>.</p>
                        <p class="mb-4">Na zajęcia praktyczne (jazdy) umawiamy się z kursantami indywidualnie:</p>
                        <div class="row gy-4 gx-8 mb-0">
                            <div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>codziennie: od poniedziałku do soboty</p>
                            </div>
                            <div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>w godz. 7.00 - 21.00</p>
                            </div>
    						<div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>wszystkie jazdy rozpoczynają i kończą się z parkingu przed OSK AUTO TURBO przy ul. Bardowskiego</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    			
    	</div>
    
    <!--SZKOLENIE - Instruktorzy ---------->
        <div class="container-xxl py-5" id="szkolenie_instruktorzy">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                    <h1 class="mb-5">Nasi instruktorzy</h1>
                </div>

    			<div class="owl-carousel testimonial-carousel position-relative">
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Grzegorz_Pałasz.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Grzegorz Pałasz</h5>
    									<small>Instruktor/Wykładowca</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Damian_Zamorski.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Damian Zamorski</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Mieczysław_Błądziński.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Mieczysław Błądzsiński</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Janusz_Froń.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Janusz Froń</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Rafał_Jaroń.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Rafał Jaroń</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Bogdan_Szewczyk.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Bogdan Szewczyk</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Piotr_Sowa.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Piotr Sowa</h5>
    									<small>Ratownik medyczny</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				
    			</div>
    			
    	  </div>
        </div>
    <!-- Instruktorzy End -->
    
    <!--BAZA WIEDZY ---------->
        <div class="container-xxl py-5" id="baza_wiedzy_egzamin">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Baza wiedzy</h6>
                    <h1 class="mb-5">Przed egzaminem</h1>
                </div>
    			
    			
                <div class="row g-4">
    				
                        
    			</div>
          <!--------------------------------------->
    	  <div class="owl-carousel testimonial-carousel position-relative">
                    <div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/01.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.2s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/02.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.3s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/03.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.4s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/04.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.5s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/05.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.6s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/06.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.7s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/baza_wiedzy_egzamin/07.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                </div>
    			<!--------------------------------->
    			
    		</div>
    		
    	</div>
	
	<!--FILMY START ---------->
    	<div class="container-xxl py-5" id="baza_wiedzy_filmy">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Baza wiedzy</h6>
                    <h1 class="mb-5">Filmy</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    
    				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.1s">
    				<div class="video-container">
    					<iframe width="560" height="315" src="https://www.youtube.com/embed/XIUp_7ZxcWE?si=qV6kxwuRlDX4EOmC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    				</div>
    				</div>
    				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.3s">
    				<div class="video-container">
    					<iframe width="560" height="315" src="https://www.youtube.com/embed/7xapYXoqPQ8?si=LWhgkx_fBf9aUO4A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    				</div>
    				</div>
							 
						   
    			</div>
    		</div>
    	</div>
    <!--FILMY END ---------->
    
    
    <!--GALERIA ----START ------>	
    <div class="container-xxl py-5 category" id="galeria">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Galeria</h6>
                    <h1 class="mb-5">Galeria</h1>
                </div>
                <div class="row g-3">
                    <div class="col-lg-7 col-md-6">
                        <div class="row g-3">
                            <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/galeria/auto_turbo_nasza_flota.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Nasza flota</h5>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/galeria/auto_turbo_plac_manewrowy.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Plac manewrowy</h5>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="img/galeria/auto_turbo_sala_wykladowa.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Sala wykładowa</h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.7s" style="min-height: 350px;">
                        <a class="position-relative d-block h-100 overflow-hidden" href="">
                            <img class="img-fluid position-absolute w-100 h-100" src="img/galeria/auto_turbo_nasza_siedziba.jpg" alt="" style="object-fit: cover;">
    						<div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
    							<h5 class="m-0">Nasza siedziba</h5>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    	
    <!-- end GALERIA ------------------------>	
    	
    <!--OPINIE  START ---------->
        <div class="container-xxl py-5" id="opinie">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Opinie</h6>
                    <h1 class="mb-5">Opinie o nas</h1>
									 
                </div>
    		
                
    			
                <div class="owl-carousel testimonial-carousel position-relative">
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="img/testimonial-1.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Ola Kociszewska</h5>
                        <p>08.04.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Z całego serca polecam tą szkołę jazdy! Organizacja jazd nastawiona na kursanta, wykłady prowadzone tak, aby każdy zrozumiał i przyswoił wiedzę, a jazdy z Panem Damianem odbywały się profesjonalnie. Polecam zapisać się do Auto Turbo i się nie bać, bo jest się w dobrych rękach!</p>
								   
						   
						 
                        </div>
                    </div>
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="img/testimonial-2.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Regina Regi</h5>
                        <p>24.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Szkoła OSK TURBO zasługuje na najlepszą opinię , za całokształt.....za wykłady, za profesjonalnych instruktorów . Damian instruktor przygotował mnie na medal i zdałam za pierwszym razem . Polecam wszystkim !!!</p>
                        </div>
                    </div>
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="img/testimonial-3.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Oliwia Furman</h5>
                        <p>14.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Gorąco polecam tę szkołę jazdy!! Profesjonalne podejście, miła atmosfera i skuteczna nauka sprawiają, że kurs przebiega sprawnie i bez stresu. Szczególnie polecam pana Rafała – świetnego instruktora, który cierpliwie i jasno tłumaczy, dodając pewności siebie za kierownicą. Nauka jazdy to tam prawdziwa przyjemność.</p>
	  
								 
																	   
			
                        </div>
                    </div>
			
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="img/testimonial-4.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Zuza Świątek</h5>
                        <p>13.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Jeśli szukacie najlepszej szkoły jazdy, to OSK Auto Turbo jest idealnym miejscem. Profesjonalne podejście, świetna atmosfera i instruktorzy. Szczególnie polecam instruktora Damiana i Janusza – pełen profesjonalizm, cierpliwość i umiejętność przekazywania wiedzy w sposób zrozumiały i bezstresowy.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- OPINIE End----------------------------------------- -->
            
    
    <!--KONTAKT ---------->
        <!--<div class="container-xxl py-5" id="kontakt">
            <div class="container">-->
    			<div class="row g-4 justify-content-center">
    				
    				
    				<div class="map-container">
    					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2562.359445057581!2d22.006371676231684!3d50.04209751668242!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473cfafe33c6fab7%3A0x2dbaffd11322ff69!2sPrawo%20jazdy%20AUTO%20TURBO%20Grzegorz%20Pa%C5%82asz!5e0!3m2!1spl!2spl!4v1744050964166!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
    					</iframe>
    				</div>
    				
    			</div>
    		<!--</div>
    	</div>-->
    
    
        
    