<!-- Carousel Start -->
        <!--<div class="container-fluid p-0 mb-5">
		
            <div class="owl-carousel header-carousel position-relative">
			
                <div class="owl-carousel-item position-relative">
				
                    <img class="img-fluid" src="/img/baner_auto_turbo/3.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .5);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h1 class="display-3 text-white animated slideInDown">AUTO TURBO</h1>
                                    <h2 class="text-white mb-4 pb-2">PROMOCJA - 200 zł zniżki!</h2>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a> 
                                </div>								
                            </div>
                        </div>
						
                    </div>
                </div>-->
				
                <!--
				<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/2.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Ucz się skutecznie – kiedy chcesz</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Obejrzyj filmy o jeździe, egzaminie i przepisach</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zobacz wszystko, zanim wsiądziesz do samochodu</p>
                                    <a href="" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Filmy</a>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/3.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Trenuj tam, gdzie zdajesz</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Plac manewrowy WORD w cenie kursu</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zyskaj pewność jazdy na egzaminie praktycznym</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/4.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Szkoła w sercu miasta</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Świetna lokalizacja – wszędzie blisko</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Bez problemu dotrzesz do nas autobusem, pociagiem lub pieszo</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    			<div class="owl-carousel-item position-relative">
                    <img class="img-fluid" src="img/baner_auto_turbo/5.jpg" alt="">
                    <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(24, 29, 56, .7);">
                        <div class="container">
                            <div class="row justify-content-start">
                                <div class="col-sm-10 col-lg-8">
                                    <h5 class="text-primary text-uppercase mb-3 animated slideInDown">Nauka jazdy na najwyższym poziomie</h5>
                                    <h1 class="display-3 text-white animated slideInDown">Doświadczeni instruktorzy, nowoczesne auta</h1>
                                    <p class="fs-5 text-white mb-4 pb-2">Zdaj bez stresu – ucz się z najlepszymi</p>
                                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Masz pytanie? Zadzwoń</a>
                                    <a href="zapisynakurs" class="btn btn-light py-md-3 px-md-5 animated slideInRight">Zapisz się</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            -->
			<!--</div>
        </div>-->
        <!-- Carousel End -->
    
	<div class="container-fluid bg-primary py-5 mb-5 page_header_index">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
					<h1 class="display-5 text-white">Prawo jazdy Rzeszów</h1>
                    <h1 class="display-1 text-white">AUTO TURBO</h1>
                    <h2 class="text-white mb-4">PROMOCJA - 200 zł zniżki!</h2>
                    <a href="tel:+48605330708" class="btn btn-primary py-md-3 px-md-5 me-3">Masz pytanie? Zadzwoń</a>
                    <a href="/zapisynakurs" class="btn btn-light py-md-3 px-md-5">Zapisz się</a> 
					
					
                </div>
            </div>
        </div>
    </div>
		
	
		        <!-- NAJBLIŻSZE KURSY ---------------------------------- -->
        <div class="container-xxl py-5" id="najblizsze_kursy">
     		
    			<div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Terminy</h6>
                    <h1 class="mb-5">Najbliższe kursy</h1>
                </div>
			

    		<div class="container">
                <div class="row g-4">
                    <?php echo $this->partial('partials/najblizszykurskarteczka.phtml', 'default') ?>
                </div>
    			
    		</div>
    	</div>
		
		
    
        <!-- DLACZEGO MY -------------------------------------Service Start -->
        <div class="container-xxl py-5" id="dlaczego_my">
            <div class="container">
    		
    			<div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">O nas</h6>
                    <h1 class="mb-5">Dlaczego my?</h1>
                </div>
    		
    			<div class="owl-carousel testimonial-carousel position-relative">
    			  
    				<div class="testimonial-item text-center">
    					<div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chalkboard-teacher text-primary mb-4"></i>
                                <h5 class="mb-3">Cierpliwi i doświadczeni instruktorzy</h5>
                                <p>Profesjonalna kadra potrafi w przystępny sposób przekazać wiedzę i stworzyć komfortową atmosferę do nauki, nawet dla najbardziej zestresowanych kursantów</p>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
                                <h5 class="mb-3">Wysoka zdawalność</h5>
                                <p>Kursanci AUTO TURBO osiągają świetne wyniki na egzaminach państwowych, co świadczy o skuteczności szkolenia naszego ośrodka</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-trophy text-primary mb-4"></i>
                                <h5 class="mb-3">Najwyżej w rankingach</h5>
                                <p>Szkoła regularnie zajmuje czołowe miejsca w ogólnopolskich rankingach szkół nauki jazdy w Rzeszowie, co potwierdza jej renomę</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-car text-primary mb-4"></i>
                                <h5 class="mb-3">Nowoczesna flota pojazdów</h5>
                                <p>Jazdy odbywają się na nowoczesnych autach (z klimatyzacją i czujnikami parkowania) identycznych jak te używane podczas egzaminów w WORD Rzeszów</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">>
                            <div class="p-4">
                                <i class="fa fa-3x fa-film text-primary mb-4"></i>
                                <h5 class="mb-3">Filmy instruktażowe</h5>
                                <p>Dodatkowe materiały wideo pomagają lepiej zrozumieć przepisy i manewry egzaminacyjne, co znacznie ułatwia naukę</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa fa-map-marker-alt me-3 text-primary mb-4"></i>
                                <h5 class="mb-3">Świetna lokalizacja</h5>
                                <p>AUTO TURBO mieści się tuż obok dworca PKP i PKS, co czyni ją idealnym wyborem dla osób dojeżdżających z okolicznych miejscowości</p>
                            </div>
                        </div>
                    </div>
    				<div class="testimonial-item text-center">
                       <div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-clock text-primary mb-4"></i>
                                <h5 class="mb-3">Elastyczne godziny jazd</h5>
                                <p>Możliwość umawiania się na jazdy codziennie w godzinach od 7:00 do 21:00 oraz w weekendy</p>
                            </div>
                        </div>
                    </div>			
                    <div class="testimonial-item text-center">
    					<div class="testimonial-text bg-light text-center pt-3">
                            <div class="p-4">
                                <i class="fa fa-3x fa-thumbs-up text-primary mb-4"></i>
                                <h5 class="mb-3">Setki pozytywnych opinii</h5>
                                <p>Zadowoleni kursanci chętnie dzielą się pozytywnymi recenzjami w Internecie, co mówi samo za siebie</p>
                            </div>
                        </div>
                    </div>       
                    
                </div>

    		</div>
    	</div>
        <!-- Service End -->
    
    
    
        <!--CENNIK - Kursy prawa jazdy ---------->
        <div class="container-xxl py-5" id="cennik">
            <div class="container">
    			<?php echo $this->partial('partials/cennikkursypartial.phtml', 'default') ?>
    		</div>    
    	</div>
    	
    	<!--CENNIK - Promocje ---------->
        <div class="container-xxl py-5" id="cennik_promocje">
            <div class="container">
				
				<?php echo $this->partial('partials/cennikpromocjepartial.phtml', 'default') ?>
				
    		</div>
    	</div>
    	
    
    	<!--CENNIK - Jazdy-->	
    	<div class="container-xxl py-5" id="cennik_jazdy">
    		
    		<div class="container">
				
				<?php echo $this->partial('partials/cennikjazdypartial.phtml', 'default') ?>
    
    	   </div>
        </div>
        <!-- Courses End -->
    
    
    <!--ZAPISY - Jak rozpocząc? ---------->
        <div class="container-xxl py-5" id="zapisy_jak_rozpoczac">
            <div class="container">
    			
				<?php echo $this->partial('partials/zapisyjakrozpoczacpartial.phtml', 'default') ?>

			</div>
    	</div>
    	
    <!--ZAPISY - Na kurs ---------->
        <div class="container-xxl py-5" id="zapisy_na_kurs">
            <div class="container">
                <div class="row g-4 justify-content-center">
    				<div class="col-lg-5 col-md-6" style="min-height: 50px;">
    					<div class="text-center">
    						<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="/zapisynakurs">Zapisz się na kurs ON-LINE</a>
    					</div>
    				</div>
    				<div class="col-lg-5 col-md-6" style="min-height: 50px;">
    					<div class="text-center">
    						<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Masz pytania? Zadzwoń</a>
    					</div>
    				</div>
    							
    			</div>
    		</div>
    	</div>
    	
    <!--SZKOLENIE - Teoria ---------->
        <div class="container-xxl py-5" id="szkolenie_teoretyczne">
            <div class="container">
    			
				<?php echo $this->partial('partials/szkolenieteoretycznepartial.phtml', 'default') ?>


			</div>
    	</div>
    	
    <!--SZKOLENIE - Praktyka ---------->
        <div class="container-xxl py-5" id="szkolenie_praktyczne">
    			
    		<div class="container">

				<?php echo $this->partial('partials/szkoleniepraktycznepartial.phtml', 'default') ?>

			</div>
    			
    	</div>
    
    <!--SZKOLENIE - Instruktorzy ---------->
        <div class="container-xxl py-5" id="szkolenie_instruktorzy">
            <div class="container">
                
				<?php echo $this->partial('partials/szkolenienasiinstruktorzykaruzelapartial.phtml', 'default') ?>
				
    	    </div>
        </div>
    <!-- Instruktorzy End -->
    
    <!--BAZA WIEDZY ---------->
	<!--
        <div class="container-xxl py-5" id="baza_wiedzy_egzamin">
            <div class="container">
    			
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Baza wiedzy</h6>
                    <h1 class="mb-5">Przed egzaminem</h1>
                </div>		
                <div class="row g-4">                      
    			</div>
    	  <div class="owl-carousel testimonial-carousel position-relative">
                    <div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/01.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.2s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/02.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.3s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/03.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.4s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/04.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.5s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/05.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.6s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/06.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                    <div class="testimonial-item text-center">
                        <div class="wow zoomIn" data-wow-delay="0.7s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <img class="img-fluid" src="/img/baza_wiedzy_egzamin/07.png" alt="">
                                </a>
                            </div>
    					</div>
                    </div>
                </div>

    			
    		</div>
    		
    	</div>
	-->
	<!--FILMY START ---------->
    	<div class="container-xxl py-5" id="baza_wiedzy_filmy">
            <div class="container">
    			
                <div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Baza wiedzy</h6>
                    <h1 class="mb-5">Filmy</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    
    				<div class="col-lg-6 col-sm-12">
    				<div class="video-container">
    					<iframe width="560" height="315" src="https://www.youtube.com/embed/XIUp_7ZxcWE?si=qV6kxwuRlDX4EOmC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    				</div>
    				</div>
    				<div class="col-lg-6 col-sm-12">
    				<div class="video-container">
    					<iframe width="560" height="315" src="https://www.youtube.com/embed/7xapYXoqPQ8?si=LWhgkx_fBf9aUO4A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    				</div>
    				</div>
							 
						   
    			</div>
    		</div>
    	</div>
    <!--FILMY END ---------->
    
    
    <!--GALERIA ----START ------>	
    <div class="container-xxl py-5 category" id="galeria">
            <div class="container">
                <div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Galeria</h6>
                    <h1 class="mb-5">Galeria</h1>
                </div>
                <div class="row g-3">
                    <div class="col-lg-7 col-md-6">
                        <div class="row g-3">
                            <div class="col-lg-12 col-md-12">
                                <a class="position-relative d-block overflow-hidden" href="/galerianowa">
                                    <img class="img-fluid" src="/img/galeria/auto_turbo_nasza_flota.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Nasza flota</h5>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <a class="position-relative d-block overflow-hidden" href="/galerianowa">
                                    <img class="img-fluid" src="/img/galeria/auto_turbo_plac_manewrowy.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Plac manewrowy</h5>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <a class="position-relative d-block overflow-hidden" href="/galerianowa">
                                    <img class="img-fluid" src="/img/galeria/auto_turbo_sala_wykladowa.jpg" alt="">
                                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                        <h5 class="m-0">Sala wykładowa</h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-6" style="min-height: 350px;">
                        <a class="position-relative d-block h-100 overflow-hidden" href="/galerianowa">
                            <img class="img-fluid position-absolute w-100 h-100" src="/img/galeria/auto_turbo_nasza_siedziba.jpg" alt="" style="object-fit: cover;">
    						<div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
    							<h5 class="m-0">Nasza siedziba</h5>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    	
    <!-- end GALERIA ------------------------>	
    	
    <!--OPINIE  START ---------->
        <div class="container-xxl py-5" id="opinie">
			
			<div class="container">
    			
                <div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Opinie</h6>
                    <h1 class="mb-5">Opinie o nas</h1>
									 
                </div>
		
			<?php echo $this->partial('partials/opinieonas.phtml', 'default') ?>
			
			</div>
            
		</div>
        <!-- OPINIE End----------------------------------------- -->
            
    
    <!--KONTAKT ---------->
        <!--<div class="container-xxl py-5" id="kontakt">
            <div class="container">-->
    			<div class="row g-4 justify-content-center">
    				
    				
    				<div class="map-container">
    					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2562.359445057581!2d22.006371676231684!3d50.04209751668242!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473cfafe33c6fab7%3A0x2dbaffd11322ff69!2sPrawo%20jazdy%20AUTO%20TURBO%20Grzegorz%20Pa%C5%82asz!5e0!3m2!1spl!2spl!4v1744050964166!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
    					</iframe>
    				</div>
    				
    			</div>
    		<!--</div>
    	</div>-->
    
    
        
    