<div class="tresc">

    <h2>Instruktor nauki jazdy kat. B</h2>
    <h3>Opis stanowiska pracy:</h3>
    <p>Poszukujemy wyłącznie osób posiadających aktualną legitymację instruktorską.</p>
    <p>Naszą siłą jest praca zespołowa i tego wymagamy od naszych instruktorów.</p>
    <p>Kładziemy ogromny nacisk na szkolenie w miłej atmosferze i pracę z dużym zaangażowaniem, 
        czego oczekujemy od naszych instruktorów.</p>
    <p>Szukamy osób z doświadczeniem, które chcą się dalej rozwijać i uczyć.</p>
    
    <h3>Wymagania:</h3>
    <ul>
        <li>uprawnienia instruktora nauki jazdy kat. B (aktualne)
        <li>miłe i bezstresowe podejście do kursanta</li>
        <li>umiejętność nawiązywania kontaktów z ludźmi</li>
        <li>punktualność</li>
        <li>zaangażowanie w pracę</li>
        <li>dobra organizacja</li>
        <li>umiejętność pracy w zespole</li>
        <li>dyspozycyjność</li>
    </ul>
    
    <h3>Oferujemy:</h3>
    <ul>
        <li>pracę w  dynamicznie rozwijającej się firmie,</li>
        <li>wynagrodzenie adekwatne do posiadanych umiejętności, zaangażowania i efektów pracy</li>
        <li>system premiowy</li>
        <li>warsztaty doskonalenia zawodowego dla instruktorów</li>
        <li>przyjazną kulturę organizacyjną firmy</li>
    </ul>

    <p>Osoby zainteresowane ofertą prosimy o przesłanie aplikacji zawierającej CV na adres: <b>oskautoturbo@gmail.com</b></p>
 <p>Prosimy w przesłanej aplikacji zamieścić zapis:
     "Wyrażam zgodę na przetwarzanie moich danych osobowych do celów rekrutacyjnych, zgodnie z Ustawą z dn. 29.08.1997 o ochronie danych osobowych (Dz. U. nr 133, poz. 883)"</p>

</div>