<div class="tresc">
    <img class="foto_left" title="plakat konkursu" src="../img/konkurs/plakat_konkurs.jpg">
    
    <h2>Regulamin konkursu</h2>
    <div class="pdf">
            <ul>
                <li><a href="../doc/konkurs/RegulaminKonkursu.pdf" target="blank">Regulamin.pdf</a></li>
            </ul>
    </div>
    
    <h3>UWAGA!!! Zapisanie się na konkurs nie zobowiązuje do zapisania się na kurs prawa jazdy.</h3>
    
    <h2 id="zapisy">Zgłoszenia na konkurs</h2>
    <p>
    <?php
    if(isset($this->form)){
        echo $this->form;
    }else{
        
    }
    
?>
        
    </p>
</div>