    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_kontakt">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Kontakt</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="/#dlaczego_my">O nas</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="cennikkursy">Cennik</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Kontakt</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    
    <div class="container-xxl py-5">
	
		<!-- Contact Start -->
        <div class="container">
		
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Kontakt</h6>
                <h1 class="mb-5">Masz pytania? Zadzwoń, napisz lub odwiedź nas osobiście</h1>
            </div>
			
            <div class="row g-4">
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <h4>Ośrodek Szkolenia Kierowców AUTO TURBO Grzegorz Pałasz</h4>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-map-marker-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Biuro i sala wykładowa</h5>
                            <p class="mb-0">ul. Bardowskiego 1C (I piętro, nad barberem)</p>
							<p class="mb-0">35-005 Rzeszów</p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Telefon</h5>
                            <p class="mb-0">605 330 708</p>
							<p class="mb-0">693 776 163</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-envelope-open text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Email</h5>
                            <p class="mb-0">oskautoturbo@gmail.com</p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-car text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Plac manewrowy</h5>
                            <p class="mb-0">Rzeszów - Krasne 20 (obok Auchan)</p>
                        </div>
                    </div>
					<small>(Wszystkie jazdy rozpoczynają i kończą się z samego centrum Rzeszowa - ul. Bardowskiego)</small>
                    
					<p></p>
					<h5>Godziny otwarcia biura</h5>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-clock text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Biuro jest czynne:</h5>
                            <p class="mb-0"><b>poniedziałki</b> w godz.: 9<sup>00</sup> - 11<sup>00</sup> i 16<sup>00</sup> - 17<sup>00</sup></p>
							<p class="mb-0"><b>środy</b> w godz.: 16<sup>00</sup> - 17<sup>00</sup></p>
							<p class="mb-0"><b>czwartki</b> w godz.: 9<sup>00</sup> - 11<sup>00</sup> i 16<sup>00</sup> - 17<sup>00</sup></p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-book-open text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Zajęcia teoretyczne odbywają się:</h5>
                            <p class="mb-0"><b>poniedziałki</b> w godz.: 17<sup>00</sup> - 19<sup>30</sup></p>
							<p class="mb-0"><b>środy</b> w godz.: 17<sup>00</sup> - 19<sup>30</sup></p>
							<p class="mb-0"><b>czwartki</b> w godz.: 17<sup>00</sup> - 19<sup>30</sup></p>
                        </div>
                    </div>
					<small>W pozostałych godzinach i dniach również jesteśmy do Państwa dyspozycji, ale prosimy o wcześniejszy kontakt telefoniczny.</small>

                </div>
				
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
					
					<iframe class="position-relative rounded w-100 h-100" src=	"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2562.359445057581!2d22.006371676231684!3d50.04209751668242!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473cfafe33c6fab7%3A0x2dbaffd11322ff69!2sPrawo%20jazdy%20AUTO%20TURBO%20Grzegorz%20Pa%C5%82asz!5e0!3m2!1spl!2spl!4v1744050964166!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
					</iframe>
				
                </div>
				
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
				
				<h5>Dane do przelewu</h5>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-user text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Nazwa odbiorcy:</h5>
                            <p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-map-marker-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Adres odbiorcy:</h5>
                            <p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-university text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Nr rachunku odbiorcy:</h5>
                            <p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
                        </div>
                    </div>
					<div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-pencil-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Tytułem:</h5>
                            <p class="mb-0">Imię i nazwisko kursanta - kurs prawa jazdy</p>
                        </div>
                    </div>
					
					<h5>Masz pytania? Napisz:</h5>
                    
					<!--
					<form>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" placeholder="Imię i nazwisko">
                                    <label for="name">Imię i nazwisko</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="phone" class="form-control" id="phone" placeholder="Telefon">
                                    <label for="phone">Telefon</label>
                                </div>
                            </div>
							<div class="col-md-12">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="mail" placeholder="mail">
                                    <label for="email">Adres e-mail</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" placeholder="Temat">
                                    <label for="subject">Temat</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 150px"></textarea>
                                    <label for="message">Wiadomość</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Wyślij wiadomość</button>
                            </div>
                        </div>
                    </form>
					-->
					
					
					
					<!--
					<form id="contactForm">
					  <div class="row g-3">
						<div class="col-md-6">
						  <div class="form-floating">
							<input type="text" class="form-control" id="name" name="name" placeholder="Imię i nazwisko" required>
							<label for="name">Imię i nazwisko</label>
						  </div>
						</div>
						<div class="col-md-6">
						  <div class="form-floating">
							<input type="tel" class="form-control" id="phone" name="phone" placeholder="Telefon">
							<label for="phone">Telefon</label>
						  </div>
						</div>
						<div class="col-md-12">
						  <div class="form-floating">
							<input type="email" class="form-control" id="mail" name="email" placeholder="mail" required>
							<label for="mail">Adres e-mail</label>
						  </div>
						</div>
						<div class="col-12">
						  <div class="form-floating">
							<input type="text" class="form-control" id="subject" name="subject" placeholder="Temat">
							<label for="subject">Temat</label>
						  </div>
						</div>
						<div class="col-12">
						  <div class="form-floating">
							<textarea class="form-control" placeholder="Wiadomość" id="message" name="message" style="height: 150px" required></textarea>
							<label for="message">Wiadomość</label>
						  </div>
						</div>
						<div class="col-12">
						  <button class="btn btn-primary w-100 py-3" type="submit">Wyślij wiadomość</button>
						</div>
						<div class="col-12">
						  <div id="formAlert" class="mt-3 text-center fw-bold"></div>
						</div>

					  </div>
					</form>-->



					                      <?php
    if(isset($this->form)){
        echo $this->form;
    }else{
        
    } 
    
?>
    <script type="text/javascript" >
    jQuery(function($){
        $('#telefon').mask("999-999-999");
    });
    </script>
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
--><script type="text/javascript">
   
   /* $('#zapisy').validate();
    $('#zapisy').submit(function(){
         alert('ala');
         $('#zapisy').valid();
        return false;
    })*/
$(function(){

    $('input,textarea').change(function (){
        
        var formElementId = $(this).parent().find('label').attr('for');
        //alert(formElementId);
        //doValidation(formElementId);
    })
}) 
function doValidation(id){
    var url = '/validateform';
    var data = {};
    $('input').each(function(){
        data[$(this).attr('name')] = $(this).val();
    })
    
    $.post(url,data,function(resp){
        $("#"+id).parent().find('.errors').remove();
        $("#"+id).parent().append(getErrorHtml(resp[id],id));
    },'json');
}
function getErrorHtml(formErrors,id){
    var o = '<ul id="errors-"'+id+'" class="errors">';
    for(errorKey in formErrors){
        o += '<li>'+ formErrors[errorKey]+'</li>' ;
    }
    o+='</ul>';
    return o;
}
</script>
					  
					  
					  
					  
					  



                </div>
            </div>
			

			
			
        </div>
		<!-- Contact End -->
	
		<!----------- początek PDF z regulaminem ---------------->
		<div class="container py-5">
			<div class="row g-4 justify-content-center">
				<p class="mb-0 border-bottom">Pliki do pobrania:</p>
				<div class="wow fadeInUp" data-wow-delay="0.1s">
					<a class="btn text-dark" href="../doci/Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Regulamin.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Regulamin OSK AUTO TURBO</a>
                </div>
		   </div>
		</div>
		<!----------- koniec PDF z regulaminem ---------------->

   </div>
	
	