<div class="tresc">
    <h2>Ośrodek Szkolenia Kierowców "Auto Turbo"</h2>
    <h3>Grzegorz Pałasz</h3>
    <h4>Biuro obsługi klienta i adres wykładów:</h4>
    <p>
        <?php echo $this->partial('partials/adresIkonki.phtml','default') ?>
    </p>
    
    <h4>Godziny otwarcia biura:</h4>
    <img class=foto_right_none title=zegar src="../img/layout/zegar.png"><p>
	<p>Biuro jest czynne:</p>
	<ul>
		<li>w <b>poniedziałki</b> w godzinach: <b>9<sup>00</sup> - 11<sup>00</sup></b> i <b>16<sup>00</sup> - 17<sup>00</sup></b></li>
		<li>w <b>środy</b> w godzinach: <b>16<sup>00</sup> - 17<sup>00</sup></b></li>
		<li>w <b>czwartki</b> w godzinach: <b>9<sup>00</sup> - 11<sup>00</sup></b> i <b>16<sup>00</sup> - 17<sup>00</sup></b></li>
	</ul>
	<p>Zajęcia teoretyczne odbywają się:</p>
	<ul>
		<li>w <b>poniedziałki</b> w godzinach: <b>17<sup>00</sup> - 19<sup>30</sup></b></li>
		<li>w <b>środy</b> w godzinach: <b>17<sup>00</sup> - 19<sup>30</sup></b></li>
		<li>w <b>czwartki</b> w godzinach: <b>17<sup>00</sup> - 19<sup>30</sup></b></li>
	</ul>
<p>
 W pozostałych godzinach i dniach również jesteśmy do Państwa dyspozycji, ale prosimy o wcześniejszy kontakt telefoniczny.
</p>
    
    <!--<img class="foto_left" title="mapka" src="../img/kontakt/bardowskiego_mala.jpg">-->
    <iframe width="690" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?hl=pl&amp;sig=KbF&amp;ie=UTF8&amp;q=prawo+jazdy+rzesz%C3%B3w&amp;fb=1&amp;gl=pl&amp;cid=0,0,16780527323174558328&amp;t=m&amp;ll=50.043443,22.009327&amp;spn=0.005512,0.012681&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
    <br />
    <small><a href="https://maps.google.pl/maps?hl=pl&amp;sig=KbF&amp;ie=UTF8&amp;q=prawo+jazdy+rzesz%C3%B3w&amp;fb=1&amp;gl=pl&amp;cid=0,0,16780527323174558328&amp;t=m&amp;ll=50.043443,22.009327&amp;spn=0.005512,0.012681&amp;z=16&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">Wyświetl większą mapę</a></small>
       
    
    <h4>Adres placu manewrowego:</h4>
    <p>
        Rzeszów - Krasne 20 (obok Auchan)
    <h6>(Wszystkie jazdy rozpoczynają sie i kończą z samego centrum Rzeszowa - ul. Bardowskiego)</h6>
    </p>
    
        
    <h4>Rachunek bankowy OSK Auto Turbo:</h4>
    <p>
        Bank Pekao S.A.<br/>  
        nr konta: 51 1950 0001 2006 0263 1600 0002 <br/>  
    </p>
    <h4>Dane do przelewu</h4> 
    
    <table class="raty"> 
        <tr>
            <td class="pomar" style="width: 25%">Nazwa odbiorcy:</td>
            <td class="bialleft" style="width: 75%">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO”</hr> GRZEGORZ PAŁASZ</td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Adres odbiorcy:</td>
            <td class="bialleft" style="width: 220px">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Nr rachunku odbiorcy:</td>
            <td class="bialleft" style="width: 220px"><b>51 1950 0001 2006 0263 1600 0002</b></td>
        </tr>
        <tr>
            <td class="pomar" style="width: 90px">Tytułem (przykłady):</td>
            <td class="bialleft" style="width: 220px">
                <ul>
                    <li>Opłata za kurs prawa jazdy</li>
                    <li>Opłata za kurs prawa jazdy (I rata)</li>
                    <li>Opłata za 2 godziny jazdy doszkalającej</li>
                </ul>
            </td>
        </tr>
    </table>

</div>