<div class="tresc">
    <h2>Ośrodek Szkolenia Kierowców "Auto Turbo"</h2>
    <img class="foto_right" title="samochód" src="../img/onas/auta.png">
    <p>
        Ośrodek Szkolenia Kierowców Auto Turbo zajmuje się profesjonalnym szkoleniem kandydatów na 
        kierowców, a także doszkalaniem osób przed egzaminem. Jednocześnie staramy się pomagać osobom, 
        które posiadają prawo jazdy, lecz nie czują się na siłach by jeździć samochodem po ulicach dużych 
        miast jak Rzeszów. 
    </p> 
    
    <!--<p>
       Zajęcia teoretyczne prowadzone są w profesjonalnej sali wykładowej wyposażonej w niezbędne 
       materiały dydaktyczne i pomoce naukowe, które pozwolą przyszłemu kierowcy w jeszcze bardziej 
       obrazowy sposób zrozumieć przepisy ruchu drogowego. Jednocześnie zajęcia teoretyczne prowadzone 
       są przy pomocy nowoczesnych technik nauczania i ciekawych multimedialnych prezentacji. 
       Ośrodek kładzie nacisk na to, aby zajęcia teoretyczne nie były jedynie suchym przekazem wiedzy. 
       W trakcie zajęć instruktor w pełni angażuje słuchaczy, wraz z którymi omawia poszczególne przepisy, 
       sytuacje na drodze oraz testy egzaminacyjne.   
    </p>/!-->
    <img class="foto_left" title="auta" src="../img/onas/sala.png">
    <!--<p>
        Szkolenie praktyczne odbywa się na samochodach marki <b>Hyundai i20</b> z klimatyzacją.
            </p>
            <p>
        Na tych samochodach obecnie zdaje się egzamin państwowy - praktyczny w Wojewódzkim Ośrodku Ruchu Drogowego 
        w Rzeszowie.
            </p>
    
    <p>
        Ponadto zadania egzaminacyjne odbywają się na pełnowymiarowym placu manewrowym, 
        który spełnia wszystkie wymogi jak na placu egzaminacyjnym.
    </p>
    /!-->
    <h3>
        Atuty naszej szkoły:
    </h3>
    <lu>
        <li>samochody identyczne jak na egzaminie państwowym (z klimatyzacją),</li>
        <li><b>zajęcia teoretyczne</b> prowadzone w <b>multimedialny sposób</b> w profesjonalnej sali wykładowej,</li>
        <li><b>nowoczesny plac manewrowy</b> pełnowymiarowy jak na placu egzaminacyjnym w WORD,</li>
        <li><b>pomoc w założeniu PKK</b></li>
        <li><b>badania</b> lekarskie możliwe <b>w ośrodku</b>,</li>
        <li>dla kursantów <b>pomoce dydaktyczne GRATIS!</b> 
            W tym:
            <ul>
                <li><b>płytka z NOWYMI TESTAMI</b> z możliwością aktualizacji bazy pytań przez Internet</li>
                <li>podręcznik kursanta w systemie SPS</li>
                <li>materiały własne instruktora</li>
            </ul>
        <li>zajęcia z <b>pierwszej pomocy</b> prowadzone z wykwalifikowanym <b>ratownikiem medycznym</b></li>
        <li>mozliwość opłaty za kurs w ratach (<b>RATY 0%</b>)</li>
        <li>świetna <b>lokalizacja w centrum Rzeszowa</b> (obok dworca PKP)</li>
        </li>
    </lu>

    <p>
        Ośrodek AUTO TURBO kładzie nacisk na to, aby Nasi kursanci i przyszli kierowcy nie tylko 
        zdali egzamin, ale również w sposób pewny, bezpieczny i odpowiedzialny czuli się jako kierowcy 
        na drodze.
    </p>
        
    <h2>Regulamin ośrodka</h2>
    <div class="pdf">
            <ul>
                <li><a href="../doci/onas/Regulamin_AUTO_TURBO.pdf" target="blank">Regulamin.pdf</a></li>
            </ul>
    </div>
</div>