    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_opinie">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Opinie</h1>
                    <nav aria-label="breadcrumb">
                        <!--<ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenie_teoretyczne.html">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenie_praktyczne.html">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenie_instruktorzy.html">Nasi instruktorzy</a></li>
                        </ol>-->
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- CENNIK KURSY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Opinie</h6>
				<h1 class="mb-5">Tysiące osób poleca AUTO TURBO! Zobacz opinie!</h1>
				
				
				<div class="row g-4">
				<div class="col-lg-3 col-md-6 wow zoomIn" data-wow-delay="0.1s">
					<div class="team-item">
                            <a class="position-relative d-block overflow-hidden" href="https://www.superprawojazdy.pl/osk-auto-turbo,9598.htm">
                                <img class="img-fluid" src="img/opinie/auto_turbo_superprawojazdy.png" alt="">
                            </a>
						</div>
                    </div>
                    <div class="col-lg-3 col-md-6 wow zoomIn" data-wow-delay="0.2s">
						<div class="team-item">
							<a class="position-relative d-block overflow-hidden" href="https://g.co/kgs/QFkZTSm">
								<img class="img-fluid" src="img/opinie/auto_turbo_google.png" alt="">
							</a>
						</div>
                    </div>
                    <div class="col-lg-3 col-md-6 wow zoomIn" data-wow-delay="0.3s">
						<div class="team-item">
                            <a class="position-relative d-block overflow-hidden" href="https://www.prawo-jazdy-360.pl/ranking-szkol-jazdy/osrodek-szkolenia-kierowcow-auto-turbo-grzegorz-palasz/rzeszow">
                                <img class="img-fluid" src="img/opinie/auto_turbo_prawojazdy360.png" alt="">
                            </a>
						</div>
					</div>						
					<div class="col-lg-3 col-md-6 wow zoomIn" data-wow-delay="0.4s">
						<div class="team-item">
                            <a class="position-relative d-block overflow-hidden" href="https://www.facebook.com/prawojazdyautoturbo">
                                <img class="img-fluid" src="img/opinie/auto_turbo_facebook.png" alt="">
                            </a>
                        </div>
					</div>


				</div>


            </div>
			
			
			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennik_kursy.html">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennik_jazdy.html">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisy_na_kurs.html">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			

		</div>
		
    </div>
    <!-- CENNIK KURSU ---------------------------------------- End -->