    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_opinie">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Opinie</h1>
                    <nav aria-label="breadcrumb">
                        <!--<ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenie_teoretyczne.html">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenie_praktyczne.html">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenie_instruktorzy.html">Nasi instruktorzy</a></li>
                        </ol>-->
                    </nav>

					
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- OPINIE ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center">
                <h6 class="section-title bg-white text-center text-primary px-3">Opinie</h6>
				<h1 class="mb-5">Tysiące osób poleca AUTO TURBO! Zobacz nasze opinie!</h1>
				
				<?php echo $this->partial('partials/opiniepartials.phtml', 'default') ?>

            </div>
			
			
			
			<div class="text-center my-5">
				<?php echo $this->partial('partials/opinieonas.phtml', 'default') ?>
			</div>
			
			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			
			

			
			
			

		</div>
		
    </div>
    <!-- OPINIE ---------------------------------------- End -->