<div class="tresc">
    
    <p></p>
    <h2>Promocje dotyczące kursów prawa jazdy kat. B</h2>
    <ul>
        <li>
            <h3>Promocja "STUDENT"</h3>
            <p>Zniżka 50 zł od ceny kursu dla wszystkich uczniów i studentów.</p>
        </li>
        <li>
            <h3>Promocja "2 na 1"</h3>
            <p>Przy jednoczesnym zapisie na kurs dwóch osób, każda z nich dostaje po jednej godzinie jazdy GRATIS!</p>
        </li>
        <li>
            <h3>Promocja "3 na 2"</h3>
            <p>Przy jednoczesnym zapisie na kurs trzech (lub wiecej) osób, każda z nich dostaje po dwie godziny jazdy GRATIS!</p>
        </li>
        <li>
            <h3>Promocja "POLEĆ NAS"</h3>
            <p>Jeżeli polecisz nas innej osobie i ta osoba zapisze się na kurs, to oboje dostaniecie po jednej dodatkowej godzinie jazdy GRATIS!</p>
        </li>
    </ul>
    
    
    
    <p></p>
    <h6>UWAGA!!! Promocji nie można łączyć.</h6>
    
    <h2>Promocje (wersja pdf)</h2>
    <div class="pdf">
            <ul>
                <li><a href="../doci/promocje/Promocje_wazne_od_2_10_2012.pdf" target="blank">Promocje.pdf</a></li>
            </ul>
    </div>
    
    <img class="foto_left_none" title="ulotka_1" src="../img/promocje/ulotka_A8_strona_1.jpg">
    <img class="foto_right_none" title="ulotka_2" src="../img/promocje/ulotka_A8_strona_2.jpg">
    
</div>