    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_szkolenie_teoretyczne">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Szkolenie</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenieteoretyczne">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkoleniepraktyczne">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenieinstruktorzy">Nasi instruktorzy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- SZKOLENIE TEORETYCZNE ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			<?php echo $this->partial('partials/szkolenieteoretycznepartial.phtml', 'default') ?>

		</div>
		
		<!----------- początek PDF z planem zajęć ---------------->
		<div class="container py-5">
			<div class="row g-4 justify-content-left">
				<p class="mb-0 border-bottom">Pliki do pobrania:</p>
				<div>
					<a class="btn text-dark" href="../doci/szkolenie/2026__Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Ramowy_plan_zajec_teoretycznych.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Ogólny plan zajęć teoretycznych</a>
                </div>
				<div>
					<a class="btn text-dark" href="../doci/szkolenie/2026_07_08_09_Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Plan_zajec_teoretycznych.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Plan zajęć teoretycznych lipiec, sierpień i wrzesień 2026</a>
                </div>
		   </div>
		<!----------- koniec PDF z planem zajęć ---------------->

		</div>
		
			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			
			
    </div>
    <!-- SZKOLENIE TEORETYCZNE ---------------------------------------- End -->
