    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_szkolenie_instruktorzy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Szkolenie</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenieteoretyczne">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkoleniepraktyczne">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenieinstruktorzy">Nasi instruktorzy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- NASI INSTRUKTORZY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                <h1 class="mb-5">Nasi instruktorzy</h1>
            </div>
			

			
			
			<div class="text-center wow fadeInUp" data-wow-delay="0.4s">
                <!--<h6 class="section-title bg-white text-center text-primary px-3"> o</h6>
                <h1 class="mb-5">Nasi instruktorzy</h1>-->
            </div>-
            <div class="row g-4">
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Grzegorz_Pałasz.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Grzegorz Pałasz</h5>
                            <small>Instruktor/Wykładowca</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Damian_Zamorski.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Damian Zamorski</h5>
                            <small>Instruktor</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Mieczysław_Błądziński.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Mieczysław Błądzsiński</h5>
                            <small>Instruktor</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Janusz_Froń.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Janusz Froń</h5>
                            <small>Instruktor</small>
                        </div>
                    </div>
                </div>
				<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.8s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Rafał_Jaroń.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Rafał Jaroń</h5>
                            <small>Instruktor</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.9s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Bogdan_Szewczyk.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Bogdan Szewczyk</h5>
                            <small>Instruktor</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="1.0s">
                    <div class="team-item bg-light">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="img/auto_turbo_instruktorzy/AUTO_TURBO_Piotr_Sowa.jpg" alt="">
                        </div>
                        <div class="text-center p-4">
                            <h5 class="mb-0">Piotr Sowa</h5>
                            <small>Ratownik medyczny</small>
                        </div>
                    </div>
                </div>
            </div>
			
			


			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisy_nakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			

		</div>
		
    </div>
    <!-- NASI INSTRUKTORZY ---------------------------------------- End -->
