<div class="tresc">
    
    <h2>Zajęcia teoretyczne</h2>

<p><b>Zajęcia teoretyczne</b> odbywają się cyklicznie w <b>poniedziałki, środy i czwartki o godz. 17.00</b> 
    w siedzibie naszej szkoły (Rzeszów, ul. Bardowskiego 1C, I piętro nad barberem).</p>

<p>
    Zajęcia teoretyczne prowadzą:
<ul>
    <li><b>Grzegorz Pałasz</b> - Instruktor, Wykładowca</li>
    <li><b>Piotr Sowa</b> - Ratownik Medyczny</li>
</ul>
</p>
    <h2>Plan zajęć teoretycznych w OSK AUTO TURBO</h2>
    <table class="plan">
        <tr>
            <td class="pomar" style="width: 160px">Blok tematyczny</td>
            <td class="pomar" style="width: 340px">Treści programowe</td>
            <td class="pomar" style="width: 90px">Ilość godzin </br>lekcyjnych </br>(45 min.)</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 1.</td>
            <td class="bialy">
                <h4>Wiadomości ogólne i przepisy szczegółowe</h4>
                <ul>
                    <li>Podstawowe pojęcia i definicje oraz ogólne zasady poruszania się po drogach </li>
                    <li>Prędkość i hamowanie</li>
					<li>Przejazdy kolejowe</li>
					<li>Zachowanie się wobec pieszych</li>
                </ul>
            </td> 
            <td class="bialybold">4 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 2.</td>
            <td class="bialy">
                <h4>Znaki i sygnały drogowe</h4>
                <ul>
                    <li>Znaki drogowe – wiadomości ogólne</li>
                    <li>Znaki ostrzegawcze</li>
                    <li>Znaki zakazu</li>
                    <li>Znaki nakazu, informacyjne, kierunku i miejscowości, poziome </li>
                    <li>Sygnalizacja świetlna</li>
                </ul> 
            </td>
            <td class="bialybold">4 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 3.</td>
            <td class="bialy"> 
                <h4>Przepisy szczegółowe o ruchu drogowym</h4>
                <ul>
                    <li>Włączanie się do ruchu</li>
					<li>Wymijanie, omijanie, cofanie, zawracanie</li>
					<li>Zmiana kierunku jazdy i pasa ruchu</li>
                </ul>            
            </td>
            <td class="bialybold">4 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 4.</td>
            <td class="bialy"> 
                        
                <h4>Przepisy szczegółowe o ruchu drogowym</h4>
                <ul>
                    <li>Wyprzedzanie</li>
					<li>Przecinanie kierunków ruchu i pierwszeństwo przejazdu</li>
					<li>Skrzyżowania o ruchu okrężnym</li>
                </ul>
            </td>
            <td class="bialybold">5 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 5.</td>
            <td class="bialy"> 
                <h4>Przepisy szczegółowe o ruchu pojazdów</h4>
                <ul>
                    <li>Zatrzymanie i postój</li>
					<li>Holowanie</li>
					<li>Światła zewnętrzne i zasady ich używania</li>
					<li>Obowiązkowe wyposażenie pojazdu</li>
                </ul>  
            </td>
            <td class="bialybold">4 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 6.</td>
            <td class="bialy"> 
                <h4>Zasady egzaminu państwowego</h4>
                <ul>
                    <li>ogólne zasady egzaminu państwowego</li>
                    <ul>
						<li>egzamin teoretyczny</li>
						<li>egzamin praktyczny</li>
					</ul>
                </ul>   
            </td>
            <td class="bialybold">5 godz.</td>
        </tr>
        <tr>
            <td class="szary">Blok tematyczny nr 7.</td>
            <td class="bialy"> 
                <h4>Pierwsza pomoc z ratownikiem medycznym</h4>
                <ul>
                    <li>Szkolenie teoretyczne</li>
					<li>Zajęcia praktyczne</li>
                </ul>
            </td>
            <td class="bialybold">4 godz.</td>
        </tr>
        
        <tr>
            <td  class="szary" colspan="2">Razem</td>
            <td  class="szary">30 godz.</td>
        </tr>
        
    </table>
    
    <img class="foto_right_none" title="szkolenie" src="../img/szkolenie/szkolenie2.png">
    <h2>Pliki do pobrania</h2>
    <div class="pdf">
            <ul>
                <li><a href="../doci/szkolenie/Ramowy_plan_zajęć_teoretycznych_w_OSK_AUTO_TURBO_2024.pdf" target="blank">Plan zajęć teoretycznych</a></li>
                <li><a href="../doci/szkolenie/2025_04_05_06_Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Plan_zajec_teoretycznychh.pdf" target="blank">Plan zajęć teoretycznych marzec, kwiecień i maj 2025</a></li>
            </ul> 
    </div>   
     
    
    
    
    
    <h2>Zajęcia praktyczne</h2>
    <p>Po ukończeniu zajęć teoretycznych (7 spotkań, około 2 tygodnie) 
        uczestnik kursu rozpoczyna zajęcia praktyczne.</p>
    <p>
        Na <b>zajęcia praktyczne (jazdy)</b> umawiamy się z kursantami codziennie: 
        <b>od poniedziałku do soboty w godz. 7.00 - 21.00</b>.
    </p>
    <p>Zajęcia praktyczne prowadzą:</p>

    <table class="plan">
        <tr>
            <td class="pomar" colspan="3" style="width: 800px">Nasi instruktorzy</td>
        </tr>
        <tr>
            <td class="bialy" style="width: 270px"><img class="foto_none" title="Grzegorz Pałasz" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Grzegorz_Pałasz.png"></td>
            <td class="bialy" style="width: 460px"><b>Grzegorz Pałaszz</b></br></br>Instruktor</br>Wykładowca<br>kat. B</td>
        </tr>
        <tr>
            <td class="bialy"><img class="foto_none" title="Damian Zamorski" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Damian_Zamorski.png"></td>
            <td class="bialy"><b>Damian Zamorski</b></br></br>Instruktor<br>kat. B</td>
        </tr>
        <tr>
            <td class="bialy"><img class="foto_none" title="Mieczysław Błądzińśki" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Mieczyslaw_Bladzinski.png"></td>
            <td class="bialy"><b>Mieczysław Błądziński</b></br></br>Instruktor<br>kat. B</td>
        </tr>
		<tr>
            <td class="bialy"><img class="foto_none" title="Rafał Jaroń" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Rafal_Jaron.png"></td>
            <td class="bialy"><b>Rafał Jaroń</b></br></br>Instruktor<br>kat. B</td>
        </tr>
		<tr>
            <td class="bialy"><img class="foto_none" title="Janusz Froń" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Janusz_Fron.png"></td>
            <td class="bialy"><b>Janusz Froń</b></br></br>Instruktor<br>kat. B</td>
        </tr>
		
		<tr>
            <td class="bialy"><img class="foto_none" title="Bogdan Szewczyk" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_Bogdan_Szewczyk.png"></td>
            <td class="bialy"><b>Bogdan Szewczyk</b></br></br>Instruktor<br>kat. B</td>
        </tr>
		<tr>
            <td class="pomar" colspan="3" style="width: 800px">Pierwsza pomoc</td>
        </tr>
		<tr>
            <td class="bialy"><img class="foto_none" title="Piotr Sowa" src="../img/szkolenie/prawo_jazdy_rzeszow_osk_auto_turbo_ratownik_medyczny.png"></td>
            <td class="bialy"><b>Piotr Sowa</b></br></br>Ratownik medyczny</td>
        </tr>
    </table>

</div>

