    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_szkolenie_teoretyczne">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Szkolenie</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenieteoretyczne">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkoleniepraktyczne">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenieinstruktorzy">Nasi instruktorzy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- SZKOLENIE TEORETYCZNE ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			
            <div class="text-center">
                <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                <h1 class="mb-5">Teoretyczne</h1>
            </div>
			
			<div class="row g-4 justify-content-left">
			
			<p class="mb-0 border-bottom">Zajęcia teoretyczne odbywają się cyklicznie w <b>poniedziałki</b>, <b>środy</b> i <b>czwartki</b> o godz. <b>17.00</b> w siedzibie naszej szkoły (Rzeszów, ul. Bardowskiego 1C, I piętro nad barberem).</p>
			<p class="mb-0">Całość teorii podzielona jest na siedem bloków temetycznych:</p>
			
			<div class="row g-4 justify-content-left">
			
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 1.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Wiadomości ogólne i przepisy szczegółowe</h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Podstawowe pojęcia i definicje oraz ogólne zasady poruszania się po drogach</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Prędkość i hamowanie</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przejazdy kolejowe</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zachowanie się wobec pieszych</p>
							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 2.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Znaki i sygnały drogowe</h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki drogowe – wiadomości ogólne</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki ostrzegawcze</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki zakazu</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki nakazu, informacyjne, kierunku i miejscowości, poziome</p>
							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 3.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Przepisy szczegółowe </h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Włączanie się do ruchu</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wymijanie, omijanie, cofanie</p> 
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zmiana kierunku jazdy i pasa ruchu</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zawracanie</p>
							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 4.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Przepisy szczegółowe </h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wyprzedzanie</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zatrzymanie i postój</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Holowanie</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Obowiązkowe wyposażenie pojazdu</p>

							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 5.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Przepisy szczegółowe</h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przecinanie kierunków ruchu i pierwszeństwo przejazdu</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu kierowanym</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu okrężnym</p>
							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 6.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Zasady egzaminu państwowego</h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>ogólne zasady egzaminu państwowego – zapoznanie się z obsługą pojazdu</p>
								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>egzamin praktyczny</p>
							</div>
                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-4 pb-1 bg-dark">
							<div class="flex-fill text-center py-2 px-3">
								<h5 class="text-white">Blok tematyczny nr 7.</h5>
							</div>
						</div>
						<div class="text-letf p-4 pb-0 border-bottom py-2">
							<h6 class="text-dark mt-3">Pierwsza pomoc z ratownikiem medycznym</h6>
                        </div>						
							<div class="text-left py-2 px-4 pb-10">
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Szkolenie teoretyczne</p>
								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zajęcia praktyczne</p>
							</div>
                    </div>
                </div>
				


		   </div>
		   </div>

		</div>
		
		<!----------- początek PDF z planem zajęć ---------------->
		<div class="container py-5">
			<div class="row g-4 justify-content-center">
				<p class="mb-0 border-bottom">Pliki do pobrania:</p>
				<div>
					<a class="btn text-dark" href="../doci/szkolenie/2025__Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Ramowy_plan_zajec_teoretycznychh.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Ogólny plan zajęć teoretycznych</a>
                </div>
				<div>
					<a class="btn text-dark" href="../doci/szkolenie/2025_06_07_08_Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Plan_zajec_teoretycznych.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Plan zajęć teoretycznych czerwiec, lipiec i sierpień 2025</a>
                </div>
		   </div>
		<!----------- koniec PDF z planem zajęć ---------------->

		</div>
		
			<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708">Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			
			
    </div>
    <!-- SZKOLENIE TEORETYCZNE ---------------------------------------- End -->
