    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_szkolenie_instruktorzy">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Szkolenie</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="szkolenieteoretyczne">Teoretyczne</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="szkoleniepraktyczne">Praktyczne</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="szkolenieinstruktorzy">Nasi instruktorzy</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- NASI INSTRUKTORZY ----------------------- Start -->
    <div class="container-xxl py-5">
        
		<div class="container">
		
			<?php echo $this->partial('partials/szkolenienasiinstruktorzypartial.phtml', 'default') ?>            

			<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisy_nakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->
			

		</div>
		
    </div>
    <!-- NASI INSTRUKTORZY ---------------------------------------- End -->
