    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_terminy_kursow">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Terminy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="/zapisyjakrozpoczac">Jak rozpocząć?</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="/zapisynakurs">Zapisy na kurs</a></li>
							<li class="breadcrumb-item"><a class="text-white" href="/najbliszeterminykursowwszystkie">Terminy kursów</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    
    <div class="container-xxl py-5">
        <!-- NAJBLIŻSZE TERMINY KURSÓW ---------------------- Start -->
		<div class="container">
	
			<?php echo $this->partial('partials/najbliszeterminykursowwszystkiepartial.phtml', 'default', [
						'calendarId' => $this->calendarId,
						'apiKey' => $this->apiKey
					]) ?>	

		</div>

		</div>
		<!-- NAJBLIŻSZE TERMINY KURSÓW  ---------------------------------------- End -->
		
	
		
		
		
    </div>
	
	<div class="container-xxl py-5" id="najblizsze_kursy">
     		
			
			
	<!-- przyciski na dole------------------>
			<div class="text-center">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="col-lg-3 col-sm-6 w-100">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->		
			
    </div>
    