<!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_zapisy_na_kurs">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Zapisy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="zapisyjakrozpoczac">Jak rozpocząć?</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="zapisynakurs">Zapisy na kurs</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    
    <div class="container-xxl py-5">
	
        <!-- ZAPISY ----------------------- Start -->
		<div class="container">
		
			
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Zapisy</h6>
                <h1 class="mb-5">Zapisy na kurs lub jazdy</h1>
            </div>
			<div class="row g-4 justify-content-center">
			
				<div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.1s" style="min-height: 350px;">
				
                    <?php
    if(isset($this->form)){
        echo $this->form;
    }else{
        
    } 
    
?>
    <script type="text/javascript" >
    jQuery(function($){
        $('#telefon').mask("999-999-999");
    });
    </script>
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
--><script type="text/javascript">
   
   /* $('#zapisy').validate();
    $('#zapisy').submit(function(){
         alert('ala');
         $('#zapisy').valid();
        return false;
    })*/
$(function(){

    $('input,textarea').change(function (){
        
        var formElementId = $(this).parent().find('label').attr('for');
        //alert(formElementId);
        //doValidation(formElementId);
    })
}) 
function doValidation(id){
    var url = '/validateform';
    var data = {};
    $('input').each(function(){
        data[$(this).attr('name')] = $(this).val();
    })
    
    $.post(url,data,function(resp){
        $("#"+id).parent().find('.errors').remove();
        $("#"+id).parent().append(getErrorHtml(resp[id],id));
    },'json');
}
function getErrorHtml(formErrors,id){
    var o = '<ul id="errors-"'+id+'" class="errors">';
    for(errorKey in formErrors){
        o += '<li>'+ formErrors[errorKey]+'</li>' ;
    }
    o+='</ul>';
    return o;
}
</script>
				</div>
				
				<div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.1s" style="min-height: 350px;">
					<div class="position-relative h-100">
						<img class="img-fluid position-absolute w-100 h-100" src="/img/galeria/auto_turbo_zdjecie_05.jpg" alt="" style="object-fit: cover;">
					</div>
				</div>
			</div>


			

		</div>
		<!-- ZAPISY ---------------------------------------- End -->
		
		<!----------- początek PDF z planem zajęć ---------------->
		<div class="container py-5">
			<div class="row g-4 justify-content-center">
				<p class="mb-0 border-bottom">Pliki do pobrania:</p>
				<div class="wow fadeInUp" data-wow-delay="0.1s">
					<a class="btn text-dark" href="../doci/Prawo_Jazdy_Rzeszow_OSK_AUTO_TURBO_Regulamin.pdf"><i class="fa fa-file-pdf text-primary me-2"></i>Regulamin OSK AUTO TURBO</a>
                </div>
		   </div>
		<!----------- koniec PDF z planem zajęć ---------------->
		
		
		<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisyjakrozpoczac">Jak rozpocząć?</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
				</div>
            </div>
		<!------------- koniec przycisków na dole ------->
			
    </div>