<div class="tresc">
    

<!--   
<p>Terminy najbliższych kursów:</p>
<table class="raty">
    <tr>
        <td class="pomar" colspan="3">Zajęcia prowadzone są w sposób CIĄGŁY</td>
    </tr>
        <tr>
            <td colspan="2" class="pomar" style="width: 300px">Termin rozpoczęcia kursu</td>
            <td class="pomar" style="width: 270px">Godzina</td>
        </tr> 
        <tr>
            <td rowspan="3" class="szary">każdy</td>
            <td class="szary">poniedziałek</td>
            <td rowspan="3" class="szary">17<sup>00</sup></td>
        </tr> 
        <tr><td class="szary">środa</td></tr>
        <tr><td class="szary">czwartek</td></tr>
        
    </table>
 -->
<!--
<h2>Czas trwania kursu</h2>
<table class="raty">
        <tr>
            <td class="pomar" style="width: 180px"> </td>
            <td class="pomar" style="width: 180px">STANDARDOWY</td>
            <td class="pomar" style="width: 180px">EKSPRESOWY</td>
        </tr>
        <tr>
            <td class="pomar">część teoretyczna</td>
            <td class="bialy"><b>2 tygodnie</b> </br>(poniedziałek, środa, czwartek)</td>
            <td class="bialy"><b>2 tygodnie</b> </br>(poniedziałek, środa, czwartek)</td>
        </tr> 
        <tr>
            <td class="pomar">część praktyczna</td>
            <td class="bialy"><b>1 - 2,5 miesiąca</b></br>(w zależności od dyspozycji czasowej kursanta)</td>
            <td class="bialy"><b>15 dni</b></br>(codziennie po 2 lub 3 godz. jazdy)</td>
        </tr> 
        <tr>
            <td class="pomar">Razem</td>
            <td class="szary"><b>1,5 - 3 miesiące</b></td>
            <td class="szary"><b>1 miesiąc</b></td>
        </tr> 
</table>
-->

<h2>Zapisy</h2>
<p>Zapisu na kurs można dokonać:
<ul class="adresikonki">
    <li class="i_adres"><b>w biurze naszego ośrodka</b>
        <ul>
            <li>Rzeszów, ul. Bardowskiego 1C, I piętro (nad barberem)</li>
        </ul>
    </li>
    <li class="i_telefon"><b>telefonicznie</b>
        <ul>
            <li>693 776 163</li>
            <li>605 330 708</li>
        </ul>
    </li>
    <li  class="i_mail"><b>mailowo</b>
        <ul>
            <li>oskautoturbo@gmail.com</li>
        </ul>
    </li>
    <li>lub <b>za pomocą formularza</b>, który znajduje się <a href="#zapisy">tutaj</a></li>
</ul>
</p>


<h2>Dokumenty</h2>
<h3>Kurs prawa jazdy kat. B</h3>
<p>
    Przed rozpoczęciem kursu uczestnik powinien <b>udać się do 
    Wydziału Komunikacji odpowiedniego dla miejsca zamieszkania i wyrobić <span class="_blue">PROFIL KIEROWCY (PKK)</span></b>. W tym celu musi złożyć następujące dokumenty:
<ul class="ikonki">
    <li class="i_wniosek"><a href="../doc/egzamin/wniosek.pdf">Wniosek o wydanie prawa jazdy</a>
       (dostępny w ośrodku) <!--<a href="../doc/egzamin/wniosek_wzor_logo.pdf"> przykład wypełnionego wniosku</a>-->
    </li>
    <li class="i_lekarz"><b>Orzeczenie lekarskie</b> stwierdzające brak przeciwwskazań zdrowotnych do kierowania pojazdami 
        (badania można zrobić na miejscu w OSK Auto Turbo)</li>
    <li class="i_foto"><b>Zdjęcie</b> (aktualne, kolorowe) do prawa jazdy o wymiarach 3,5 x 4,5 cm</li>
    <li class="i_zgoda"><a href="../doc/egzamin/zgoda.pdf">Pisemna zgoda rodziców lub opiekunów prawnych, jeżeli osoba szkolona rozpoczyna 
        szkolenie przed ukończeniem 18-tego roku życia</a>(dostepna również w ośrodku)</li>
    <li class="i_dowod">Do wglądu <b>dowód tożsamości</b> potwierdzający dane osobowe łącznie z miejscem zamieszkania
        (osoby, które nie ukończyły 18 roku życia mogą wyrobić sobie dowód tymczasowy)</li>
    
    
</ul>

<div class="_red">Przyjdź do nas pomożemy wypelnić Ci wszystkie dokumenty i wyrobić PKK!</div>
<div class="_red">To nie jest wcale takie trudne!</div>

<p>Osoby spoza Rzeszowa numeru PKK nie muszą zakładać osobiście. Do złożenia dokumentów mogą upoważnić np. kogoś z rodziny
przesyłając pełnomocnictwo i w/w komplet dokumentów.
</p>

<ul class="ikonki">
    <li class="i_wniosek"><a href="../doc/egzamin/upowaznienie.pdf">Upoważnienie do założenia PKK przez inną osobę</a>
    </li>
</ul>

<div>

<a href=https://youtube.com/shorts/h45Uhk7TjLM?feature=share>
	<img class=foto_right_none title=auto-turbo-jak-wyrobic-PKK src=http://www.oskautoturbo.pl/img/aktualnosci/jak_wyrobic_PKK_660.jpg>
	</a>
	
</div>

<p>
    Następnie w OSK Auto Turbo będzie potrzebny:
<ul>
    <li><span class="_blue">numer PKK</span> nadany przed Wydział Komunikacji</li>
    <li>numer <b>PESEL</b></li>
    <li>
        <b>dowód wpłaty</b> za kurs prawa jazdy kat. B (lub I ratę - 600 zł), opłata może zostać dokonana 
        za pośrednictwem przelewu bankowego na konto firmowe naszego ośrodka, w tytule druku przelewu 
        bankowego prosimy wpisać: <b>opłata za kurs prawa jazdy kat. B</b>, szkolenie podstawowe (rozszerzone). 
        </br></br>
    
    </li>
</ul>
</p>

</p>



-->
<a name="zapisy-on-line"></a>
<h2>Zapisy on-line</h2>
<p>
<?php
    if(isset($this->form)){
        echo $this->form;
    }else{
        
    } 
    
?>
    <script type="text/javascript" >
    jQuery(function($){
        $('#telefon').mask("999-999-999");
    });
    </script>
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
--><script type="text/javascript">
   
   /* $('#zapisy').validate();
    $('#zapisy').submit(function(){
         alert('ala');
         $('#zapisy').valid();
        return false;
    })*/
$(function(){

    $('input,textarea').change(function (){
        
        var formElementId = $(this).parent().find('label').attr('for');
        //alert(formElementId);
        //doValidation(formElementId);
    })
}) 
function doValidation(id){
    var url = '/validateform';
    var data = {};
    $('input').each(function(){
        data[$(this).attr('name')] = $(this).val();
    })
    
    $.post(url,data,function(resp){
        $("#"+id).parent().find('.errors').remove();
        $("#"+id).parent().append(getErrorHtml(resp[id],id));
    },'json');
}
function getErrorHtml(formErrors,id){
    var o = '<ul id="errors-"'+id+'" class="errors">';
    for(errorKey in formErrors){
        o += '<li>'+ formErrors[errorKey]+'</li>' ;
    }
    o+='</ul>';
    return o;
}
</script>
</p>
</div>