    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page_header_zapisy_jak_rozpoczac">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Zapisy</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="zapisyjakrozpoczac">Jak rozpocząć?</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="zapisynakurs">Zapisy na kurs</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    
    <div class="container-xxl py-5">
        <!-- JAK ROZPOCZĄĆ ----------------------- Start -->
		<div class="container">
	
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Zapisy</h6>
                <h1 class="mb-5">Jak rozpocząć?</h1>
            </div>
			<div class="row g-4 justify-content-center">
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
					<div class="service-item d-flex flex-column h-100">
						<div class="text-center p-4 pb-0">
							<div class="flex-fill text-center border-bottom py-2">
								<img src="img/ikonki_numery/1.png">
							</div>
							<div class="flex-fill text-center border-bottom py-2">
								<h4 class="mb-2">Zapis na kurs</h4>
							</div>
						</div>
						<div class="text-left py-2 px-4 pb-10">
							<p class="mb-0 border-bottom">Na kurs prawa jazdy można zapisać się na kilka sposobów:</p>
							<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i>Formularz zgłoszeniowy</p>
							<div class="d-flex border-bottom">
								<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
							</div>
							<p class="mb-0"><i class="fa fa-map-marker-alt text-primary me-2"></i>Osobiście</p>
							<div class="d-flex border-bottom">
								<small class="flex-fill text-center py-2"><a href="kontakt" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Rzeszów, Bardowskiego 1C</a></small>
							</div>
							<p class="mb-0"><i class="fa fa-phone text-primary me-2"></i>Telefonicznie</p>
							<div class="d-flex border-bottom">
								<small class="flex-fill text-center py-2"><a href="tel:+48605330708" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">605330708</a></small>
							</div>
						</div>			
					</div>							
				</div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.2s">
					<div class="service-item d-flex flex-column h-100">
						<div class="text-center p-4 pb-0">
							<div class="flex-fill text-center border-bottom py-2">
								<img src="img/ikonki_numery/2.png">
							</div>
							<div class="flex-fill text-center border-bottom py-2">
								<h4 class="mb-2">Dokumenty</h4>
							</div>
						</div>
						<div class="text-left py-2 px-4 pb-10">
							<p class="mb-0 border-bottom">Będą potrzebne następujące dokumenty:</p>
							<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i><b>Wniosek o wydanie prawa jazdy</b> 
							<small>(dostępny również w ośrodku)</small></p>
							<div class="d-flex border-bottom">
								<small class="flex-fill text-center py-2"><a href="../doci/2025_zgoda.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
							</div>
							<p class="mb-0"><i class="fa fa-file-medical text-primary me-2"></i><b>Orzeczenie lekarskie</b> <small>stwierdzające brak przeciwwskazań zdrowotnych do kierowania pojazdami (badania można zrobić w OSK Auto Turbo)</small></p>
							<p class="mb-0 border-top"><i class="fa fa-id-badge text-primary me-2"></i><b>Zdjęcie</b>
							<small>(aktualne, kolorowe) do prawa jazdy o wymiarach 3,5 x 4,5 cm</small></p>
							<p class="mb-0 border-top"><i class="fa fa-file-signature text-primary me-2"></i><b>Zgoda rodziców</b>
							<small>dotyczy osób przed ukończeniem 18-tego roku życia (dostepna również w ośrodku)</small></p>
							<div class="d-flex border-bottom">
								<small class="flex-fill text-center py-2"><a href="../doci/2025_zgoda.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
							</div>
							
						</div>			
					</div>							
				</div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
					<div class="service-item d-flex flex-column h-100">
						<div class="text-center p-4 pb-0">
							<div class="flex-fill text-center border-bottom py-2">
								<img src="img/ikonki_numery/3.png">
							</div>
							<div class="flex-fill text-center border-bottom py-2">
								<h4 class="mb-2">Założenie PKK</h4>
							</div>
						</div>
						<div class="text-left py-2 px-4 pb-10">
							<p class="mb-0 border-bottom">PKK jest to numer, który zakłada się w <b>Wydziale Komunikacji</b> odpowiednim dla miejsca zameldowania</p>
							<p class="mb-0 border-bottom">Aby go uzyskać należy złożyć w urzędzie przygotowane wcześniej <b>dokumenty</b> (patrz pkt. 2.)</p>
						</div>			
					</div>							
				</div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.4s">
					<div class="service-item d-flex flex-column h-100">
						<div class="text-center p-4 pb-0">
							<div class="flex-fill text-center border-bottom py-2">
								<img src="img/ikonki_numery/4.png">
							</div>
							<div class="flex-fill text-center border-bottom py-2">
								<h4 class="mb-2">Przekazanie PKK </br>do AUTO TURBO</h4>
							</div>
						</div>
						<div class="text-left py-2 px-4 pb-10">
							<p class="mb-0 border-bottom"><b>Po odbiorze numeru PKK</b> z Wydziału Komunikacji należy go przekazać <b>do biura OSK AUTO TURBO</b> lub przesłać SMS</p>
						</div>			
					</div>							
				</div>


			</div>

		</div>
		<!-- JAK ROZPOCZĄĆ ---------------------------------------- End -->
		
	
		
		
		
    </div>
	
	<div class="container-xxl py-5" id="najblizsze_kursy">
     		
    	<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Terminy</h6>
            <h1 class="mb-5">Najbliższe kursy</h1>
        </div>
		<div class="container">
            <div class="row g-4">
                <?php echo $this->partial('partials/najblizszykurskarteczka.phtml', 'default') ?>
            </div>
    	</div>
			
			
	<!-- przyciski na dole------------------>
			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
				<div class="row g-4 border-top mt-5">
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikkursy">CENNIK - Kursy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="cennikjazdy">CENNIK - Jazdy</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="tel:+48605330708"><i class="fa fa-phone-alt ms-3"></i> Zadzwoń</a>
						</div>
					</div>
					<div class="col-lg-3 col-md-6" data-wow-delay="0.1s">
						<div class="col-lg-3 col-sm-6 wow fadeInUp w-100" data-wow-delay="0.1s">
							<a class="btn btn-primary py-3 px-5 mt-2 w-100" href="zapisynakurs">Zapisz się</a>
						</div>
					</div>
				</div>
            </div>
			<!------------- koniec przycisków na dole ------->		
			
    </div>
    