<html>
    <head>
        <?php if(isset($includeStyles) && $includeStyles ){
                include_once 'styl.php'; 
         }
         $text = 'KURS DODATKOWY (5 godzin jazdy + zaświadczenie)';
         ?>
    </head>
    <body>
        
        <div id="tresc">
            <h1>
                Szanowni Państwo,
            </h1>

            <p>
                Dziękujemy za dokonanie zapisu on-line na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
                na <?php echo $text; ?>
            </p> 
            <p>
                W najbiższym czasie skontaktujemy sie z Państwem telefonicznie w celu ustalenai terminu zajęć praktycznych.
            </p>

            <p>
                Przed rozpoczęciem zajęć praktycznych uczestnik kursu powinien dokonać opłaty za szkolenie: 
            </p> 
            <ul>
                <li style="padding:5px">
                    opłata może zostać dokonana za pośrednictwem przelewu bankowego na konto naszego ośrodka:
                    <p>

                    </p>

                    <table border="1">
                        <tr>
                            <td colspan="2">
                                Dane do przelewu:
                            </td>
                        </tr>
                        <tr>
                            <td>Nazwa:</td>
                            <td>
                                Ośrodek Szkolenia Kierowców "Auto Turbo"
                                </br>Grzegorz Pałasz
                            </td>
                        </tr>
                        <tr>
                            <td>Adres:</td>
                            <td> 35-005 Rzeszów</br>
                                ul. Bardowskiego 4</td>
                        </tr>
                        <tr>
                            <td>Numer konta:</td>
                            <td>Idea Bank S.A.</br>
                                51 1950 0001 2006 0263 1600 0002</td>
                        </tr>
                        <tr>
                            <td>Tytuł przelewu:</td>
                            <td>opłata za kurs dodatkowy prawa jazdy kat. B</td>
                        </tr>
                    </table>

                </li>
            </ul>

            <p>
                Więcej informacji można uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 4 (I pietro, nad delikatesami "Jabłuszko"))</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą mailową: oskautoturbo@gmail.com</li>
           </ul>
            </p>

        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo"
        </p>
    </div>
    </body>
</html>
