<html>
    <head>
         <?php if(isset($includeStyles) && $includeStyles ){
                include_once 'styl.php'; 
         }
         ?>
    </head>
    <body>
        <!--KatB-->
        <div id="tresc">
            <h1>
                Szanowni Państwo,
            </h1>

            <p>
                Otrzymaliśmy od Państwa pytanie drogą elektroniczną na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
            </p> 

            <p>
                Postaramy się jak najszybciej z Państwem skontaktować w celu udzielenie odpowiedzi i rozwiania wszelkich watpliwości.
            </p> 
			
            <p>
                Więcej informacji można również uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 1C (I pietro, nad barberem)</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą mailową: oskautoturbo@gmail.com</li>
           </ul>
            </p>

        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo" Grzegorz Pałasz
        </p>
    </div>
</body>
</html>
