<html>
    <head>
        <?php if(isset($includeStyles) && $includeStyles ){
                include_once 'styl.php'; 
         }
         $text = 'JAZDY DOSZKALAJĄCE ';
         ?>
    </head>
    <body>
        
        <div id="tresc">
            <h1>Szanowni Państwo,</h1>
            <p>
                Dziękujemy za dokonanie zapisu on-line na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
                na <?php echo $text; ?>
            </p> 
            <p>
                W najbiższym czasie skontaktujemy sie z Państwem telefonicznie w celu ustalenai terminu zajęć praktycznych.
            </p>
            <p>
                Więcej informacji można uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 4 (I pietro, nad delikatesami "Jabłuszko"))</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą mailową: oskautoturbo@gmail.com</li>
           </ul>
            </p>
        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo"
        </p>
    </div>
    </body>
</html>
