<html>
    <head>
         <?php if(isset($includeStyles) && $includeStyles ){
                include_once 'styl.php'; 
         }
         ?>
    </head>
    <body>
        <!--Kat. B-->
        <div id="tresc">
            <h1>
                Szanowni Państwo,
            </h1>

            <p>
                Dziękujemy za dokonanie zapisu on-line na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
            </p> 

            <p>
                Zapraszamy na spotkanie organizacyjne w najbliższy poniedziałek, środę, lub czwartek na godz.: 16:00. 
            </p> 
			<p>Dokumenty, które należy skompletować w najbliższym czasie:</p>
            <ul>
                <li style="padding:5px"><b>Zdjęcie</b> do prawa jazdy o wymiarach 3,5 x 4,5 cm</li>
                <li style="padding:5px">dokument stwierdzający tożsamość osoby szkolonej: <b>dowód osobisty</b>, paszport lub kartę stałego pobytu (do wglądu), lub legitymację szkolną w przypadku osób, które nie ukończyły 18 roku życia</li>
                <li style="padding:5px"><b>pisemną zgodę rodziców</b> lub opiekunów prawnych, jeżeli osoba szkolona rozpoczyna szkolenie przed ukończeniem 18-tego roku życia (druk zgody jest również dostępny w biurze OSK Auto Turbo)</li>
                <li style="padding:5px"><b>oryginał orzeczenia lekarskiego</b> stwierdzającego brak przeciwwskazań zdrowotnych do kierowania pojazdami określonej kategorii (jeżeli był wcześniej wydany, jeżeli nie można badania lekarskie wykonać na miejscu w naszym ośrodku)</li>
                <li style="padding:5px"><b>wypełniony wniosek o wydanie prawa jazdy</b> – wniosek dostępny jest w biurze OSK Auto Turbo (można go wypełnić na miejscu)</li>
                <li style="padding:5px">
                    <b>potwierdzenie wpłaty</b> za określony rodzaj szkolenia, opłata może zostać dokonana za pośrednictwem przelewu bankowego na konto naszego ośrodka:
                    <p>

                    </p>

                    <table border="1">
                        <tr>
                            <td colspan="2">
                                Dane do przelewu:
                            </td>
                        </tr>
                        <tr>
                            <td>Nazwa:</td>
                            <td>
                                Ośrodek Szkolenia Kierowców "Auto Turbo"
                                </br>Grzegorz Pałasz
                            </td>
                        </tr>
                        <tr>
                            <td>Adres:</td>
                            <td> 35-005 Rzeszów</br>
                                ul. Bardowskiego 4</td>
                        </tr>
                        <tr>
                            <td>Numer konta:</td>
                            <td>PeKaO S.A.</br>
                                51 1950 0001 2006 0263 1600 0002</td>
                        </tr>
                        <tr>
                            <td>Tytuł przelewu:</td>
                            <td>Imię i nazwisko kursanta - kurs prawa jazdy</td>
                        </tr>
                    </table>

                </li>
            </ul>

            <p>
                Więcej informacji można uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 1C (I pietro, nad barberem)</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą mailową: oskautoturbo@gmail.com</li>
           </ul>
            </p>

        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo" Grzegorz Pałasz
        </p>
    </div>
</body>
</html>
