<html>
    <head>
        <?php if(isset($includeStyles) && $includeStyles ){
                include_once 'styl.php'; 
         }
         $text = 'JAZDY DOSZKALAJĄCE ';
         ?>
    </head>
    <body>
        
        <div id="tresc">
            <h1>Szanowni Państwo,</h1>
            <p>
                Dziękujemy za dokonanie zapisu on-line na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
                na <?php echo $text; ?>
            </p> 
            <p>
                W najbiższym czasie skontaktujemy sie z Państwem telefonicznie w celu ustalenia terminu jazd doszkalających.
            </p>
			
			<p>Przed rozpoczęciem jazd należy dokanać wpłaty.</p>
			<p>Opłaty za jazdy można dokonać:</p>
            <ul>
                <li style="padding:5px"><b>BLIKiem</b> na numer telefonu: <b>605330708</b>,</li>
                <li style="padding:5px">
                    <b>lub <b>przelewem</b> na konto OSK AUTO TURBO:
                    <p>

                    </p>

                    <table border="1">
                        <tr>
                            <td colspan="2">
                                Dane do przelewu:
                            </td>
                        </tr>
                        <tr>
                            <td>Nazwa:</td>
                            <td>
                                Ośrodek Szkolenia Kierowców "Auto Turbo"
                                </br>Grzegorz Pałasz
                            </td>
                        </tr>
                        <tr>
                            <td>Adres:</td>
                            <td> 35-005 Rzeszów</br>
                                ul. Bardowskiego 1C</td>
                        </tr>
                        <tr>
                            <td>Numer konta:</td>
                            <td>PeKaO S.A.</br>
                                51 1950 0001 2006 0263 1600 0002</td>
                        </tr>
                        <tr>
                            <td>Tytuł przelewu:</td>
                            <td>Imię i nazwisko kursanta - jazdy doszkalające</td>
                        </tr>
                    </table>

                </li>
            </ul>
			
			
			
			
            <p>
                Więcej informacji można uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 1C (I pietro, nad barberem)</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą mailową: oskautoturbo@gmail.com</li>
           </ul>
            </p>
        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo" Grzegorz Pałasz
        </p>
    </div>
    </body>
</html>
