<?php

/**
 * Application_Model_Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Application_Model_Article extends Application_Model_Base_Article
{
    function add($data){
       $str_small = $data['title'];
                    
                $old_string = array('Ą', 'Ó', 'Ż', 'Ź', 'Ł', 'Ć', 'Ń', 'Ś', 'Ę',
                                    'ą', 'ó', 'ż', 'ź', 'ł', 'ć', 'ń', 'ś', 'ę', 
                                    ' ','.','"',"'",'&quot;','?');
                $new_string = array('a', 'o', 'z', 'z', 'l', 'c', 'n', 's', 'e',
                                    'a', 'o', 'z', 'z', 'l', 'c', 'n', 's', 'e',
                                    '-','-','-','-','-','-');
                $slug = str_replace($old_string, $new_string, $str_small);
                //$slug = 'prawo-jazdy-rzeszow-nauka-jazdy-rzeszow-'.$slug;
               
           $data['content'] =    preg_replace('/([ \t]|(&nbsp;))+([a-zA-Z])([ ]|(&nbsp;))+/',' \3&nbsp;',$data['content']); 
                Zend_Debug::dump($data['content']);
              //die();
                Zend_Debug::dump($slug);
                do{
                    $slugsExist = Doctrine_Query::create()
                            ->from('Application_Model_Article a')
                            ->where('a.slug = ?',$slug)
                            ->execute();
                    $row = $slugsExist->toArray();
                    if(count($row)){
                      $slug = $slug.'re';  
                    }
                    else{
                        break;
                    }
                }while(true);
                Zend_Debug::dump($slug);
                
                    
            ////////////////////////////////////////
            
            
            $this->title = $data['title'];
            $this->slug = $slug;
            $this->content = $data['content'];
            $this->category_id = $data['category'];
            $this->date = $data['date'];

            $this->save();
   }
}