<?php

/**
 * Application_Model_Gallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Application_Model_Gallery extends Application_Model_Base_Gallery {

    private $_uploadPath;
    private $_galleryPath;
    private $_photosPath;
    private $_miniPath;
    private $_main_miniature_name = 'main.jpg';
    private $_main_miniature_size = 175;
    /**
     * @param string $id 
     */
    public static function create($id) {
        $gallery = new Application_Model_Gallery();
        $gallery->id = $id;
        //$gallery->init();
        return $gallery;
    }

    public function init() {
        $this->_uploadPath = realpath(APPLICATION_PATH . '/../public');
        $this->_galleryPath = '/uploads/' . $this->id;
        $this->_photosPath = $this->_galleryPath . '/photos/';
        $this->_miniPath = $this->_galleryPath . '/mini/';
    }

    /**
     * @param bool $isSystem 
     * @return string
     */
    public function getPath($isSystem) {
        if ($isSystem) {
            return $this->_uploadPath . $this->_galleryPath;
        }
        return $this->_galleryPath;
    }

    /**
     * @param bool $isSystem 
     * @return string
     */
    public function getPhotoPath($isSystem) {
        if ($isSystem) {
            return $this->_uploadPath . $this->_photosPath;
        }
        return $this->_photosPath;
    }

    /**
     * @param bool $isSystem 
     * @return string
     */
    public function getMiniPath($isSystem) {
        if ($isSystem) {
            return $this->_uploadPath . $this->_miniPath;
        }
        return $this->_miniPath;
    }

    /**
     * @return string
     */
    public function getLabel() {
        $label = $this->name ? $this->name : $this->id;
        return $label;
    }

    /**
     * @return string
     */
    public function getGalleryName() {
        if (isset($this->name)) {
            return $this->name;
        }
        else
            return null;
    }

    /**
     * @return bool
     */
    public function isPublic() {
        return !($this->getGalleryName() == null || $this->getGalleryName() == "" || $this->isEmpty());
    }

    /**
     * @return bool
     */
    public function isEmpty() {
        $dirPath = $this->getPhotoPath(true);
        $dir = new DirectoryIterator($dirPath);
        foreach ($dir as $file) {
            if ($file->isDot()) {
                continue;
            }
            if (!$file->isDir()) {
                return false;
            }
        }
        return true;
    }

    /**
     * @return bool
     */
    public function isDirExists() {

        return file_exists($this->getPath(true));
    }

    /**
     * @return bool
     */
    public function isDirNotExists() {
        return !$this->isDirExists();
    }

    /**
     * @return string
     */
    public function getSampleMiniPhoto() {
        $path = $this->getMiniPath(true) . $this->_main_miniature_name;
        if (!file_exists($path)) {
            $this->generateSamplePhoto() ;
        }
        return $this->getMiniPath(false) . $this->_main_miniature_name;
        $dirPath = $this->getPhotoPath(true);
        $dir = new DirectoryIterator($dirPath);
        foreach ($dir as $file) {
            if ($file->isDot()) {
                continue;
            }
            if (!$file->isDir()) {
                return $this->getMiniPath(false) . $file;
            }
        }
    }

    public function generateSamplePhoto() {
        $dirPath = $this->getPhotoPath(true);
        $dir = new DirectoryIterator($dirPath);
        foreach ($dir as $file) {
            if ($file->isDot()) {
                continue;
            }
            if (!$file->isDir()) {
                Turbo_Gallery_Utils::gdThumbnailFile($dirPath . $file, $this->_main_miniature_size, $this->_main_miniature_size, $this->getMiniPath(true) . $this->_main_miniature_name,true);
            }
        }
    }

    public function delete() {
        Doctrine_Query::create()
                ->delete('Application_Model_Gallery g')
                ->where('g.id = ?', $this->id)
                ->execute();

        $path = $this->getPath(true);

        if (file_exists($path)) {
            Turbo_IO_Dir::deleteDirectory($path);
        }
    }

    /**
     * @return array
     */
    public static function getGalleryList() {
        $galleries = Doctrine_Query::create()
                ->from('Application_Model_Gallery g')
                ->execute()
                ->getData();
        foreach ($galleries as $gallery) {
            /* @var $gallery Application_Model_Gallery */
            $gallery->init();
        }
        return $galleries;
    }

    /**
     * @return array
     */
    public static function getPublicGalleryList() {
        $galleries = Doctrine_Query::create()
                ->from('Application_Model_Gallery g')
                ->execute()
                ->getData();
        $galleriesOut = array();
        foreach ($galleries as $gallery) {
            /* @var $gallery Application_Model_Gallery */
            $gallery->init();
            if ($gallery->isPublic()) {
                $galleriesOut[] = $gallery;
            }
        }
        return $galleriesOut;
    }

    /**
     * @param string
     * @return Application_Model_Gallery
     */
    public static function getGalleryById($id) {
        $galleries = Doctrine_Query::create()
                ->from('Application_Model_Gallery g')
                ->where('g.id = ?', $id)
                ->execute()
                ->getData();
        if (count($galleries) == 1) {
            /* @var $gallery Application_Model_Gallery */
            $gallery = $galleries[0];
            $gallery->init();
            return $gallery;
        }
        return null;
    }

    /**
     * @param string
     * @return Application_Model_Gallery
     */
    public static function getGalleryBySlug($slug) {
        $galleries = Doctrine_Query::create()
                ->from('Application_Model_Gallery g')
                ->where('g.id = ?', $slug)
                ->execute()
                ->getData();
        if (count($galleries)) {
            /* @var $gallery Application_Model_Gallery */
            $gallery = $galleries[0];
            $gallery->init();
            return $gallery;
        }
        return null;
    }

    /**
     * @return array
     */
    public function getPhotosList() {
        $photos = array();
        $dir = new DirectoryIterator($this->getPhotoPath(true));
        foreach ($dir as $file) {
            if ($file->isDir())
                continue;
            if ($file->isDot())
                continue;

            $fileName = $file->getFilename();
            $photo = array();

            $photo['content'] = $this->getPhotoPath(false) . $fileName;
            $photo['mini'] = $this->getMiniPath(false) . $fileName;
            $photo['name'] = $fileName;

            $photos[] = $photo;
        }
        return $photos;
    }

    public static function updateGallery($gallery) {

        Doctrine_Query::create()
                ->update('Application_Model_Gallery g')
                ->set('g.name', '?', $gallery->name)
                ->where('g.id=?', $gallery->id)
                ->execute();
    }

    public function getSlug() {
        return $this->id;
    }

}
