<?php

/**
 * Application_Model_QuizUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Application_Model_QuizUser extends Application_Model_Base_QuizUser {

    public function add($data) {
        $this->nazwisko = $data['nazwisko'];
        $this->imie = $data['imie'];
        $this->email = $data['email'];
        $this->telefon = $data['telefon'];
        $this->uwagi = $data['uwagi'];
        $this->created = $data['date'];
        $this->registered = $data['registered'];
        $this->save();
    }

}