<?php

/**
 * Application_Model_Student
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Application_Model_Student extends Application_Model_Base_Student
{
    public function add($data){
        $this->nazwisko = $data['nazwisko'];
        $this->imie = $data['imie'];
        $this->email = $data['email'];
        $this->telefon = $data['telefon'];
        $this->uwagi = $data['uwagi'];
        $this->created = $data['created'];
        $this->registered = $data['registered'];
        
        $this->pesel = $data['pesel'];
        $this->miejsce_urodzenia = $data['miejsce_urodzenia'];
        $this->adres_zamieszkania = $data['adres_zamieszkania'];
        $this->obywatelstwo = $data['obywatelstwo'];
        
        $this->rodzaj_kursu = $data['rodzaj_kursu'];
        
        
        $this->save();
    }
    
    public function ToDto(){
        $data['nazwisko'] = $this->nazwisko;
        $data['imie'] = $this->imie;
        $data['email'] = $this->email;
        $data['telefon'] = $this->telefon;
        $data['uwagi'] = $this->uwagi;
       
        $data['registered'] = $this->registered;
        
        $data['pesel'] = $this->pesel;
        $data['miejsce_urodzenia'] = $this->miejsce_urodzenia;
        $data['adres_zamieszkania'] = $this->adres_zamieszkania;
        $data['obywatelstwo'] = $this->obywatelstwo;
        
        $data['rodzaj_kursu'] = $this->rodzaj_kursu;
        
        return $data;
        
    }
    
    
}