<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('students', 'rodzaj_kursu', 'integer', '8', array(
             ));
        $this->addColumn('students', 'pesel', 'string', '11', array(
             ));
        $this->addColumn('students', 'miejsce_urodzenia', 'string', '50', array(
             ));
        $this->addColumn('students', 'obywatelstwo', 'string', '50', array(
             ));
        $this->addColumn('students', 'adres_zamieszkania', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('students', 'rodzaj_kursu');
        $this->removeColumn('students', 'pesel');
        $this->removeColumn('students', 'miejsce_urodzenia');
        $this->removeColumn('students', 'obywatelstwo');
        $this->removeColumn('students', 'adres_zamieszkania');
    }
}