<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('galeries', array(
             'id' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '32',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('galeries');
    }
}