<ul class="adresikonki">
    <li class="i_adres">
        ul. Bardowskiego 1C (I piętro, nad barberem)<br/>
        35-005 Rzeszów
    </li>
    <li class="i_telefon">
        605 330 708</br>
        693 776 163
    </li>
    <li class="i_mail">
        oskautoturbo@gmail.com
    </li>
    <li class="i_www">
        <a href="http://www.oskautoturbo.pl">www.oskautoturbo.pl</a>
    </li>
    
</ul>



