			<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                <h1 class="mb-5">Kursy prawa jazdy</h1>
            </div>
			
			<!------------------------------- początek cen kursów -------------------------------------->
			
            <div class="row g-4 justify-content-center">
			
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="ramka">
					<div class="course-item bg-light d-flex flex-column h-100">
					<!--
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid" src="img/cennik_kursy/auto_turbo_kurs_podstawowy.jpg" alt="">
                        </div>
						-->
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                            <h3 class="mb-0 text-primary">3 199 PLN</h3>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-0">3 399 PLN</h5>
							<small>(pozostali)</small>
                        </div>
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">PODSTAWOWY</h4>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>WYKŁADY: 2 tygodnie</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>JAZDY: ok. 5-9 tygodni</small>
                        </div>
						

                    </div>
					</div>
                </div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.2s">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                            <h3 class="mb-0 text-primary">2 999 PLN</h3>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-0">3 199 PLN</h5>
							<small>(pozostali)</small>
                        </div>
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">PRAKTYCZNY</h4>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 5-9 tygodni</small>
                        </div>

                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                            <h3 class="mb-0 text-primary">3 999 PLN</h3>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-0">4 199 PLN</h5>
							<small>(pozostali)</small>
                        </div>
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">EKSPRESOWY</h4>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 30 dni</small>
                        </div>

                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.4s">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
						    <h6 class="mb-0 text-primary">PROMOCJA WIOSENNA</h6>
                            <h3 class="mb-0 text-primary">3 799 PLN</h3>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-0">3 999 PLN</h5>
							<small>(pozostali)</small>
                        </div>
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">EKSPRESOWY PRAKTYCZNY</h4>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 12-15 dni</small>
                        </div>

                    </div>
                </div>

		   </div>
		   
		   <!----------------------------------- koniec cen kursów ---------------------------------->

			<div class="row g-4 justify-content-center mt-1">
			

				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.5s">
					<div class="course-item bg-light d-flex flex-column h-100">
						<div class="text-left p-4 pb-0">
							<h5>Opłata za kurs może być wniesiona w całości lub w systemie ratalnym (RATY 0%)</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>I</b></div>
								</div>
								<div class="ms-3">

									<p class="mb-0"><b>I rata - 800 zł</b> - przy zapisie na kurs</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>II</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>II rata - 800 zł</b> - przed końcem zajęć teoretycznych</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>III</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>III rata - 800 zł</b> - przed 10 godziną jazdy</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>IV</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>IV rata - 799 zł</b> - przed 20 godziną jazdy</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<div class="text-center p-4 text-white"><b>V</b></div>
								</div>
								<div class="ms-3">
									<p class="mb-0"><b>V rata - pozostała kwota</b> - przed 30 godziną jazdy</p>
								</div>
							</div>
						</div>
					</div>				
				</div>
				
				<div class="col-lg-6 col-sm-12 wow fadeInUp" data-wow-delay="0.6s">
				
					<div class="course-item bg-light d-flex flex-column h-100">
						<div class="text-left p-4 pb-0">
							<h5>Dane do przelewu</h5>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-user text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nazwa odbiorcy:</h5>
									<p class="mb-0">OŚRODEK SZKOLENIA KIEROWCÓW “AUTO TURBO” GRZEGORZ PAŁASZ</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-map-marker-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Adres odbiorcy:</h5>
									<p class="mb-0">UL. BARDOWSKIEGO 1C, 35-005 RZESZÓW</p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-university text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Nr rachunku odbiorcy:</h5>
									<p class="mb-0"><b>51 1950 0001 2006 0263 1600 0002</b></p>
								</div>
							</div>
							<div class="d-flex align-items-center mb-3">
								<div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
									<i class="fa fa-pencil-alt text-white"></i>
								</div>
								<div class="ms-3">
									<h5 class="text-primary">Tytułem:</h5>
									<p class="mb-0">Imię i nazwisko kursanta - kurs prawa jazdy</p>
								</div>
							</div>
						</div>
					</div>
				
				</div>
			</div>