    		   	
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                    <h1 class="mb-5">Jazdy doszkalające</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-2 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h3 class="mb-0">110 PLN</h3>
                            </div>
							<div class="d-flex border-top">
								<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
							</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h6 class="mb-2">Jazda doszkalajaca kat. B</h6>
    							<h4 class="mb-0">1 godzina</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-3 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>1 godz.</small>
                            </div>    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-2 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h3 class="mb-0">220 PLN</h3>
                            </div>
							<div class="d-flex border-top">
								<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
							</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h6 class="mb-2">Jazda doszkalająca kat. B</h6>
    							<h4 class="mb-0">2 godziny</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-3 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość jazdy na plac manerwowy</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
                            </div>    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-2 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h3 class="mb-0">290 PLN</h3>
                            </div>
							<div class="d-flex border-top">
								<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
							</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h6 class="mb-2">Jazda doszkalająca kat. B</h6>
    							<h4 class="mb-0">2 godziny + WORD</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-3 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych (90 min)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po placu manewrowym WORD Rzeszów (30 min)</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić szczególnie przez egzaminem</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>2 godz.</small>
                            </div>    
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-2 pb-0">
    
    						<div class="flex-fill text-center border-bottom py-2">
    							<h3 class="mb-0">1000 PLN</h3>
                            </div>
							<div class="d-flex border-top">
								<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
							</div>
    						<div class="flex-fill text-center border-bottom py-2">
    							<h6 class="mb-2">Jazda doszkalająca kat. B</h6>
    							<h4 class="mb-0">PAKIET 10 godzin</h4>
    						</div>
    						</div>
    						
    							<div class="text-left py-2 px-3 pb-10">
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda po mieście po trasach egzaminacyjnych</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>możliwość wjazdu na plac manewrowy</p>
    								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>jazda dla osób, które chcą się doszkolić lub "odświeżyć" swoje umiejętności</p>
    							</div>
    
                            <div class="d-flex border-top mt-auto">
                                <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>10 godz.</small>
                            </div>   
                        </div>
                    </div>
    				
    		   </div>
    