			<div class="text-center">
                <h6 class="section-title bg-white text-center text-primary px-3">Cennik</h6>
                <h1 class="mb-5">Kursy prawa jazdy</h1>
            </div>
			
			<!------------------------------- początek cen kursów -------------------------------------->
			
            <div class="row g-4 justify-content-center">
			
				<div class="col-lg-3 col-sm-6">
                    <div class="ramka">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2">
							<h4 class="mb-0">4 499 PLN</h4>
						</div>
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
							<h4 class="mb-0 pulse-wow">-600 zł</h4>
							<h6 class="mb-2 pulse-wow promo-text">PROMOCJA WAKACYJNA</h6>
							<h2 class="mb-0 text-primary">3 899 PLN</h2>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">PODSTAWOWY</h4>
							<h6 class="mb-0">wykłady + jazdy</h6>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>WYKŁADY: 2 tygodnie</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>JAZDY: ok. 5-9 tygodni</small>
                        </div>
						

                    </div>
					</div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2">
							<h4 class="mb-0">4 499 PLN</h4>
							<!--<small>(pozostali)</small>-->
                        </div>
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
							<h4 class="mb-0 pulse-wow">-600 zł</h4>
							<h6 class="mb-2 pulse-wow promo-text">PROMOCJA WAKACYJNA</h6>
							<h2 class="mb-0 text-primary">3 899 PLN</h2>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>

						
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">PRAKTYCZNY</h4>
							<h6 class="mb-0">e-learning + jazdy</h6>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 5-9 tygodni</small>
                        </div>

                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2">
							<h4 class="mb-0">5 299 PLN</h4>
							<!--<small>(pozostali)</small>-->
                        </div>
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
							<h4 class="mb-0 pulse-wow">-600 zł</h4>
							<h6 class="mb-2 pulse-wow promo-text">PROMOCJA WAKACYJNA</h6>
							<h2 class="mb-0 text-primary">4 699 PLN</h2>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">EKSPRESOWY</h4>
							<h6 class="mb-0">wykłady + jazdy</h6>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>WYKŁADY STACJONARNE (30h lekcyjnych)</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>wewnętrzny egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 30 dni</small>
                        </div>

                    </div>
                </div>
				
				<div class="col-lg-3 col-sm-6">
                    <div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-2 pb-0">
						
						<div class="flex-fill text-center border-bottom py-2">
							<h4 class="mb-0">5 299 PLN</h4>
							<!--<small>(pozostali)</small>-->
                        </div>
						
						<div class="flex-fill text-center border-bottom py-2 px-3">
							<h4 class="mb-0 pulse-wow">-600 zł</h4>
							<h6 class="mb-2 pulse-wow promo-text">PROMOCJA WAKACYJNA</h6>
							<h2 class="mb-0 text-primary">4 699 PLN</h2>
							<small class="mb-0 text-primary">(uczniowie i studenci)</small>
						</div>
						
						<div class="d-flex border-top">
                            <small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3 w-100">Zapisz się</a></small>
                        </div>
						<div class="flex-fill text-center border-bottom py-2">
							<h5 class="mb-2">Kurs prawa jazdy kat. B</h5>
							<h4 class="mb-0">EKSPRES. PRAKTYCZNY</h4>
							<h6 class="mb-0">e-learning + jazdy</h6>
						</div>
						</div>
						
							<div class="text-left py-2 px-3 pb-10">
								<p class="mb-0"><i class="fa fa-laptop-house text-primary me-2"></i>teoria w formie E-LEARNINGU</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>JAZDY (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>pierwsza pomoc z ratownikiem medycznym</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
							</div>

                        <div class="d-flex border-top mt-auto">
                            <small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>ok. 12-15 dni</small>
                        </div>

                    </div>
                </div>

		   </div>
		   
		   <!----------------------------------- koniec cen kursów ---------------------------------->


						<style>
						.pulse-wow {
							display: inline-block;
							animation: promoPulse 1.8s ease-in-out infinite;
						}

						@keyframes promoPulse {
							0%, 100% {
								transform: scale(1);
								color: #0d6efd; /* niebieski */
								text-shadow: none;
							}

							50% {
								transform: scale(1.08);
								color: #ff6400; /* Twój pomarańcz */
								text-shadow: 0 0 5px rgba(255,100,0,0.3);
							}
						}

						@media (max-width: 576px) {
							.promo-text {
								display: block;
								margin-top: 6px;
							}
						}
						</style>