    <div id='myInfo'>ZAJĘCIA PRAKTYCZNE - jeździmy CODZIENNIE od poniedziałku do niedzieli w godz. 7.00 - 21.00
    </div>


<script type="text/javascript"> 
//var myInfo = [
//    "ZAJĘCIA PRAKTYCZNE - jeździmy CODZIENNIE od poniedziałku do niedzieli w godz. 7.00 - 21.00",
//    "ZAJĘCIA TEORETYCZNE - poniedziałki, środy i czwartki o godz. 17.00 (Bardowskiego 4, obok dworca PKP)"
//];
//var counter = 1;  // Start at number 2 since the HTML tag has the first


//function switchInfo() {
//    if (counter == myInfo.length) {
//        counter = 0;
//    }
//    
//    $('#myInfo').text(myInfo[counter]);
//    
//    counter += 1;
//}

//$(document).ready(function() {
//    setInterval(switchInfo, 500); 
//});

</script>