			
                <div class="row g-5">
				
                    <div class="col-lg-6" style="min-height: 400px;">
                        <div class="position-relative h-100">
                            <img class="img-fluid position-absolute w-100 h-100" src="/img/galeria/rel_2026_Feryjny_kurs_AUTO_TURBO_2.jpg" alt="" style="object-fit: cover;">
                        </div>
                    </div>
                    <div class="col-lg-6">

    <div class="course-item bg-light d-flex flex-column h-100">
        <div class="text-left p-4 pb-0">

            <div class="d-flex border-bottom mb-3">
                <h3>Ekspresowy kurs feryjny – kat. B</h3>
            </div>

            <div class="d-flex align-items-center mb-4">
                <div class="ms-0">
                    <h5 class="text-primary">Ferie, które się opłacają</h5>
                    <p class="mb-1">
                        <i class="fa fa-bolt text-primary me-2"></i>
                        Zrób prawo jazdy w <b>ekspresowym tempie</b> - <b class="text-primary">teoria tylko 3 dni!</b>
                    </p>
                    <p class="mb-1">
                        <i class="fa fa-smile text-primary me-2"></i>
                        Bez stresu, bez nudy i w <b>świetnej atmosferze</b>
                    </p>
                </div>
            </div>

            <div class="d-flex align-items-center mb-4 border-bottom pb-3">
                <div class="ms-0">
                    <h5 class="text-primary">Startujemy:</h5>
                    <p class="mb-1">
                        <i class="fa fa-calendar text-primary me-2"></i>
                        <b>17.02.2026 (wtorek)</b>
                    </p>
                    <p class="mb-1">
                        <i class="fa fa-clock text-primary me-2"></i>
                        Godzina: <b>9:00</b>
                    </p>
                    <p class="mb-1">
                        <i class="fa fa-map-marker-alt text-primary me-2"></i>
                        Rzeszów, ul. Bardowskiego 1C (I piętro)
                    </p>
                </div>
            </div>

            <div class="d-flex align-items-center mb-4 border-bottom pb-3">
                <div class="ms-0">
                    <h5 class="text-primary">W ofercie</h5>


                    <p class="mb-1"><i class="fa fa-check-circle text-primary me-2"></i>Pomoc w założeniu PKK</p>
                    <p class="mb-1"><i class="fa fa-check-circle text-primary me-2"></i>Badania lekarskie na miejscu</p>
                    <p class="mb-1"><i class="fa fa-car text-primary me-2"></i>Samochody jak na egzaminie – Hyundai i20</p>
					<p class="mb-1"><i class="fa fa-map text-primary me-2"></i>Świetna lokalizacja – <b>centrum Rzeszowa, obok PKP</b>
								<p class="mb-0"><i class="fa fa-chalkboard-teacher text-primary me-2"></i>Wykłady stacjonarne (teoria w 3 dni: wt., śr., czw.)</p>
								<p class="mb-0"><i class="fa fa-car text-primary me-2"></i>Jazdy (30h zegarowych)</p>
								<p class="mb-0"><i class="fa fa-medkit text-primary me-2"></i>Szkolenie z pierwszej pomocy</p>
								<p class="mb-0"><i class="fa fa-road text-primary me-2"></i><b>Jazda na placu WORD w Rzeszowie!</b></p>
								<p class="mb-0"><i class="fa fa-laptop text-primary me-2"></i>Wewnętrzny egzamin teoretyczny</p>
								<p class="mb-0"><i class="fa fa-car-side text-primary me-2"></i>Wewnętrzny egzamin praktyczny</p>
								<p class="mb-0"><i class="fa fa-gift text-primary me-2"></i>Materiały edukacyjne dla kursanta <b>GRATIS!</b> (testy + podręcznik)</p>
								<p class="mb-0"><i class="fa fa-money-bill-alt text-primary me-2"></i>Raty 0%!</p>
                </div>
            </div>

            <div class="d-flex align-items-center mb-4 border-bottom pb-3">
                <div class="ms-0">
                    <h5 class="text-primary">Liczba miejsc ograniczona!</h5>
                    <p class="mb-1">
                        
                    </p>
                    <p class="mb-1">
                        
                    </p>
                    <p class="mb-1 fw-bold">
                        <i class="fa text-primary fa-fire me-2"></i>
                        Zapisz się wcześniej i wykorzystaj ferie na 100%!
                    </p>
                </div>
            </div>

            <div class="d-flex align-items-center mb-3">
                <a class="btn btn-primary py-3 px-5 w-100" href="tel:+48605330708">
                    <i class="fa fa-phone me-2"></i>
                    Zadzwoń - zarezerwuj miejsce
                </a>
            </div>

            <div class="d-flex align-items-center mb-3">
                <a class="btn btn-outline-primary py-3 px-5 w-100" href="zapisyjakrozpoczac">
                    Jak zapisać się na kurs?
                </a>
            </div>

        </div>
    </div>



                    </div>
                </div>
            