<div class="lead-box">
    <div class="lead-box-top">
        PROMOCJE
    </div>
    <div class="lead-box-content">
        <a href="http://www.oskautoturbo.pl/zapisy" title="Promocje">
            <img id='myImage' src="<?php $this->baseUrl ?>/img/promocje/napis_47.png" />
        </a>
    </div>
</div>
                      


<script type="text/javascript"> 
var myImages = [
    "<?php $this->baseUrl ?>/img/promocje/napis_47.png",
    "<?php $this->baseUrl ?>/img/promocje/napis_45.png",
    "<?php $this->baseUrl ?>/img/promocje/napis_44.png",
    "<?php $this->baseUrl ?>/img/promocje/napis_46.png"
];
var counter = 1;  // Start at number 2 since the HTML tag has the first

function switchImage() {
    if (counter == myImages.length) {
        counter = 0;  
    }
    $('#myImage').attr('src', myImages[counter]);
    counter += 1;

    
}

$(document).ready(function() {
    setInterval(switchImage, 2000); 
});

</script>
