<h1>Przydatne linki</h1>

<!--a href="http://www.word.rzeszow.pl/" target="_blank" 
   title="WORD Rzeszów">
    <img src="../img/layout/linki/word.png" width=245 height=100 
         alt="WORD Rzeszów" title="WORD Rzeszów">
</a>/-->
    
<ul>
    <!--<li><a href="http://info-car.pl/bazapytan/" class="baza_oficjalna_link" target="_blank" title="Oficjalna baza pytań"></a></li>/-->
    <!--<li><li><a href="https://autoturbo.spsadmi.pl/" class="teoria_link" target="_blank" title="Teoria w domu"></a></li>/-->
    <!--<li><a href="http://prawkobazapytan.pl/" class="testy_link" target="_blank" title="Baza pytań"></a></li>/-->
    <!--<li><a href="http://www.word.rzeszow.pl/" target="_blank">WORD Rzeszów</a></li>/-->
    <!--<li><a href="http://www.prawojazdy.com.pl/aplikacje/prawojazdy/symulator/index.html" target="_blank">Symulator</a></li>/-->
    <!--<li><a href="http://www.prawojazdy.com.pl/aplikacje/prawojazdy/symulator/index.html" class="symulator_link" target="_blank" title="Symulator online"></a></li>/-->
    <!--<li><a href="http://www.podkarpacka.policja.gov.pl/ruch-drogowy/punkty-karne/" target="_blank">Portal Komendy Wojewódzkiej Policji w Rzeszowie  </a></li>/-->
	
    <li><a href="https://info-car.pl/infocar/konto/word/rezerwacja.html" class="zapis_link" target="_blank" title="Zapisz się na egzamin pańswowy on-line"></a></li>
    <li><a href="http://www.word.rzeszow.pl/" class="word_link" target="_blank" title="WORD Rzeszów"></a></li>
    <li><a href="https://info-car.pl/infocar/prawo-jazdy/sprawdz-status.html" class="prawko_link" target="_blank" title="Odbierz swoje prawko"></a></li>
    <li><a href="http://www.podkarpacka.policja.gov.pl/" class="policja_link" target="_blank" title="KWP w Rzeszowie"></a></li>
    
</ul>


