<style>
    #layout_message{

        z-index: 10000;
        background-color: rgba(119, 119, 119, 0.702);
        width:100%;
        height:100%;
        position:fixed;
        margin:0 auto;

    }
    .container_message{
        margin: 0 auto;
        display: table;
        height:95%;
    }
    .padding_message{
        display: table-cell;
        vertical-align: middle;

    }
    .dialog{	
        -width: 400px;
        -height: 400px;	
        -padding: 10px;
        -background-color:#fff;
        -border: 1px solid #000;
        -box-shadow: #222 5px 5px 20px 0px;
    }
    .dialog .buttons button{
        border: 0px;
        padding: 3px;
        width: 170px;
        display: inline;
        float: none;
		background-color: #ff6400;
		border-radius: 30px 30px 30px 30px;
		color: #fff;


    }
    .dialog .message_text{
        height:85%;
    }
    .buttons{
        text-align:center;
        margin:0 auto;
        background-color: #fff;
        padding-bottom: 3px;
    }
    .dialog{
        width: 390px;
    }
	
	.message_title {
		background-color: #fff;
		padding: 3 px;
		color: #000;
	}
	


</style>
<div id="layout_message"> 
    <div class="container_message">
        <div class="padding_message">
            <div class="karteczka dialog" >
                <dl>
                    <dt id="message-title" class="message_title">
                        <?php echo $this->dialogMessage['title'] ?>
                    </dt>
                    <dd class="_news">
                        <?php echo $this->dialogMessage['text'] ?>
                    </dd>
                    <form action="">
                        <div class="buttons">
                            <button class="przycisk">OK</button>
                        </div>
                    </form>
                </dl>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#layout_message button').click(function(){
        $('#layout_message').css('display','none');
    });
    $('form').submit(function(){
        return false;
    });
</script>
