<!--
<div class="col-lg-3 col-sm-6 wow fadeInUp my-3">
									<div class="ramka">
										<div class="course-item bg-light text-center pt-3 d-flex flex-column h-100">
											<div class="p-1">
												<!--<small class="text-primary text-center">NAJBLIŻSZY KURS</small>--><!--
												<h1 class="mb-3">16.04.2025 r.</h1>
												<div "mt-auto">
													<div class="d-flex border-top">
														<small class="flex-fill text-center border-end py-2"><i class="fa fa-calendar-day text-primary me-2"></i>ŚRODA</small>
														<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>godz.: 16<sup>00</sup></small>
													</div>
													<div class="d-flex border-top">
														<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								-->
								
								
								
<div class="col-lg-3 col-sm-6 wow fadeInUp my-1">
	<div class="ramka h-100">
	
		<div class="course-item bg-light text-center pt-1 d-flex flex-column h-100 shadow-sm rounded-4">
			<div class="p-1 d-flex flex-column h-100">
			<!-- Data kursu -->
			<h1 class="mb-1 text-dark">16.04.2025 r.</h1>
			<!-- Dzień i godzina -->
				<div class="mt-auto">
					<div class="d-flex border-top border-primary-subtle pt-1">
						<div class="flex-fill text-center border-end border-primary-subtle px-1 fs-6">
							<i class="fa fa-calendar-day text-primary me-1"></i>ŚRODA
						</div>
						<div class="flex-fill text-center px-1 fs-6">
							<i class="fa fa-clock text-primary me-1"></i>16:00
						</div>
					</div>
					<!-- Przycisk -->
					<div class="d-flex border-top border-primary-subtle mt-1 pt-1">
						<div class="flex-fill text-center">
							<a href="zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
						</div>
					</div>
				</div>

			</div>
		</div>
	
	</div>
</div>

<div class="col-lg-3 col-sm-6 wow fadeInUp my-1">
		<div class="course-item bg-light text-center pt-1 d-flex flex-column h-100 shadow-sm rounded-4">
			<div class="p-1 d-flex flex-column h-100">
			<!-- Data kursu -->
			<h1 class="mb-1 text-dark">23.04.2025 r.</h1>
			<!-- Dzień i godzina -->
				<div class="mt-auto">
					<div class="d-flex border-top border-primary-subtle pt-1">
						<div class="flex-fill text-center border-end border-primary-subtle px-1 fs-6">
							<i class="fa fa-calendar-day text-primary me-1"></i>ŚRODA
						</div>
						<div class="flex-fill text-center px-1 fs-6">
							<i class="fa fa-clock text-primary me-1"></i>16:00
						</div>
					</div>
					<!-- Przycisk -->
					<div class="d-flex border-top border-primary-subtle mt-1 pt-1">
						<div class="flex-fill text-center">
							<a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
						</div>
					</div>
				</div>

			</div>
		</div>
</div>

<div class="col-lg-3 col-sm-6 wow fadeInUp my-1">
		<div class="course-item bg-light text-center pt-1 d-flex flex-column h-100 shadow-sm rounded-4">
			<div class="p-1 d-flex flex-column h-100">
			<!-- Data kursu -->
			<h1 class="mb-1 text-dark">24.04.2025 r.</h1>
			<!-- Dzień i godzina -->
				<div class="mt-auto">
					<div class="d-flex border-top border-primary-subtle pt-1">
						<div class="flex-fill text-center border-end border-primary-subtle px-1 fs-6">
							<i class="fa fa-calendar-day text-primary me-1"></i>CZWARTEK
						</div>
						<div class="flex-fill text-center px-1 fs-6">
							<i class="fa fa-clock text-primary me-1"></i>16:00
						</div>
					</div>
					<!-- Przycisk -->
					<div class="d-flex border-top border-primary-subtle mt-1 pt-1">
						<div class="flex-fill text-center">
							<a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
						</div>
					</div>
				</div>

			</div>
		</div>
</div>

<div class="col-lg-3 col-sm-6 wow fadeInUp my-1">
		<div class="course-item bg-light text-center pt-1 d-flex flex-column h-100 shadow-sm rounded-4">
			<div class="p-1 d-flex flex-column h-100">
			<!-- Data kursu -->
			<h1 class="mb-1 text-dark">28.04.2025 r.</h1>
			<!-- Dzień i godzina -->
				<div class="mt-auto">
					<div class="d-flex border-top border-primary-subtle pt-1">
						<div class="flex-fill text-center border-end border-primary-subtle px-1 fs-6">
							<i class="fa fa-calendar-day text-primary me-1"></i>PONIEDZIAŁEK
						</div>
						<div class="flex-fill text-center px-1 fs-6">
							<i class="fa fa-clock text-primary me-1"></i>16:00
						</div>
					</div>
					<!-- Przycisk -->
					<div class="d-flex border-top border-primary-subtle mt-1 pt-1">
						<div class="flex-fill text-center">
							<a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
						</div>
					</div>
				</div>

			</div>
		</div>
</div>
