<div class="col-lg-3 col-sm-6 wow fadeInUp my-3">
									<div class="ramka">
										<div class="course-item bg-light text-center pt-3 d-flex flex-column h-100">
											<div class="p-1">
												<small class="text-primary text-center">NAJBLIŻSZY KURS</small>
												<h1 class="mb-3">16.04.2025 r.</h1>
												<div "mt-auto">
													<div class="d-flex border-top">
														<small class="flex-fill text-center border-end py-2"><i class="fa fa-calendar-day text-primary me-2"></i>ŚRODA</small>
														<small class="flex-fill text-center py-2"><i class="fa fa-clock text-primary me-2"></i>godz.: 16<sup>00</sup></small>
													</div>
													<div class="d-flex border-top">
														<small class="flex-fill text-center py-2"><a href="zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>