<div class="text-center">
            <h6 class="section-title bg-white text-center text-primary px-3">Zapisy</h6>
            <h1 class="mb-5">Najbliższe terminy kursów</h1>
</div>

<div class="container">
    <div class="row g-4">
			
	<?php echo $this->partial('partials/najblizszykurskarteczka.phtml', 'default') ?>
	
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">14.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>ŚRODA
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">15.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>CZWARTEK
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">19.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>PONIEDZIAŁEK
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">21.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>ŚRODA
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">22.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>CZWARTEK
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">26.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>PONIEDZIAŁEK
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">28.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>ŚRODA
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="col-12 col-sm-6 col-lg-3">
		  <div class="course-item bg-light text-center p-3 h-100 shadow-sm rounded-4 d-flex flex-column">
			<h1 class="mb-2">29.05.2025 r.</h1>
			<div class="mt-auto">
			  <div class="d-flex border-top border-primary-subtle pt-2 fs-6">
				<div class="flex-fill text-center border-end border-primary-subtle px-2">
				  <i class="fa fa-calendar-day text-primary me-1"></i>CZWARTEK
				</div>
				<div class="flex-fill text-center px-2">
				  <i class="fa fa-clock text-primary me-1"></i>16:00
				</div>
			  </div>
			  <div class="d-flex border-top border-primary-subtle mt-2 pt-2">
				<div class="flex-fill text-center">
				  <a href="/zapisynakurs" class="btn btn-sm btn-primary px-4 rounded-pill">Zapisz się</a>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
	</div>

</div>