       
    			
                <div class="owl-carousel testimonial-carousel position-relative">
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="/img/testimonial-1.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Ola Kociszewska</h5>
                        <p>08.04.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Z całego serca polecam tą szkołę jazdy! Organizacja jazd nastawiona na kursanta, wykłady prowadzone tak, aby każdy zrozumiał i przyswoił wiedzę, a jazdy z Panem Damianem odbywały się profesjonalnie. Polecam zapisać się do Auto Turbo i się nie bać, bo jest się w dobrych rękach!</p>
								   
						   
						 
                        </div>
                    </div>
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="/img/testimonial-2.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Regina Regi</h5>
                        <p>24.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Szkoła OSK TURBO zasługuje na najlepszą opinię , za całokształt.....za wykłady, za profesjonalnych instruktorów . Damian instruktor przygotował mnie na medal i zdałam za pierwszym razem . Polecam wszystkim !!!</p>
                        </div>
                    </div>
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="/img/testimonial-3.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Oliwia Furman</h5>
                        <p>14.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Gorąco polecam tę szkołę jazdy!! Profesjonalne podejście, miła atmosfera i skuteczna nauka sprawiają, że kurs przebiega sprawnie i bez stresu. Szczególnie polecam pana Rafała – świetnego instruktora, który cierpliwie i jasno tłumaczy, dodając pewności siebie za kierownicą. Nauka jazdy to tam prawdziwa przyjemność.</p>
	  
								 
																	   
			
                        </div>
                    </div>
			
                    <div class="testimonial-item text-center">
                        <img class="border rounded-circle p-2 mx-auto mb-3" src="/img/testimonial-4.jpg" style="width: 80px; height: 80px;">
                        <h5 class="mb-0">Zuza Świątek</h5>
                        <p>13.03.2025</p>
                        <div class="testimonial-text bg-light text-center p-4">
                        <p class="mb-0">Jeśli szukacie najlepszej szkoły jazdy, to OSK Auto Turbo jest idealnym miejscem. Profesjonalne podejście, świetna atmosfera i instruktorzy. Szczególnie polecam instruktora Damiana i Janusza – pełen profesjonalizm, cierpliwość i umiejętność przekazywania wiedzy w sposób zrozumiały i bezstresowy.</p>
                        </div>
                    </div>
                </div>
        