	
            <div class="row g-4 justify-content-center">	
					
				<div class="col-lg-3 col-sm-6">
					<div class="course-item h-100">
						<a href="https://www.superprawojazdy.pl/osk-auto-turbo,9598.htm" class="w-100 m-0 p-0">
							<div class="text-left">
								<h2 class="mb-0 text-white bg-primary px-3 d-inline-block">I miejsce</h2>
							</div>
							<div class="text-left p-1 bg-dark mx-3 pb-3">
								<small class="m-2 text-white"><i class="fa fa-check text-primary mx-2"></i>w największym rankingu szkół nauki jazdy w Polsce</small>
							</div>
							<div class="text-left p-0 bg-white mx-2">
								<div class="text-center m-0 p-0">
									<div class="bg-white" style="border: 3px solid #ff6400; border-radius: 7px; width: 100%; display: inline-block; margin-top: -10px;">
										<img class="img-fluid" style="border-radius: 15px; width: 100%; height: auto;" src="/img/opinie/1.png" alt="">
									</div>
								</div>
							</div>
						</a>
					</div>
				</div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item h-100">
						<a href="https://www.prawo-jazdy-360.pl/ranking-szkol-jazdy/osrodek-szkolenia-kierowcow-auto-turbo-grzegorz-palasz/rzeszow" class="w-100 m-0 p-0">
							<div class="text-left">
								<h2 class="mb-0 text-white bg-primary px-3 d-inline-block">II miejsce</h2>
							</div>
							<div class="text-left p-1 bg-dark mx-3 pb-3">
								<small class="m-2 text-white"><i class="fa fa-check text-primary mx-2"></i>w ogólnopolskim rankingu szkół nauki jazdy</small>
							</div>
							<div class="text-left p-0 bg-white mx-2">
								<div class="text-center m-0 p-0">
									<div class="bg-white" style="border: 3px solid #ff6400; border-radius: 7px; width: 100%; display: inline-block; margin-top: -10px;">
										<img class="img-fluid" style="border-radius: 15px; width: 100%; height: auto;" src="/img/opinie/2.png" alt="">
									</div>
								</div>
							</div>
						</a>
					</div>
				</div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item h-100">
						<a href="https://g.co/kgs/QFkZTSm" class="w-100 m-0 p-0">
							<div class="text-left">
								<h2 class="mb-0 text-white bg-primary px-3 d-inline-block">4,9 
									<i class="fa fa-star text-white fs-5"></i>
									<i class="fa fa-star text-white fs-5"></i>
									<i class="fa fa-star text-white fs-5"></i>
									<i class="fa fa-star text-white fs-5"></i>
									<i class="fa fa-star text-white fs-5"></i>
								</h2>
							</div>
							<div class="text-left p-1 bg-dark mx-3 pb-3">
								<small class="m-2 text-white"><i class="fa fa-check text-primary mx-2"></i>bardzo wysokie oceny w Google 4.9/5.0</small>
							</div>
							<div class="text-left p-0 bg-white mx-2">
								<div class="text-center m-0 p-0">
									<div class="bg-white" style="border: 3px solid #ff6400; border-radius: 7px; width: 100%; display: inline-block; margin-top: -10px;">
										<img class="img-fluid" style="border-radius: 15px; width: 100%; height: auto;" src="/img/opinie/3.png" alt="">
									</div>
								</div>
							</div>
						</a>
					</div>
				</div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item h-100">
						<a href="https://www.facebook.com/prawojazdyautoturbo" class="w-100 m-0 p-0">
							<div class="text-left">
								<h2 class="mb-0 text-white bg-primary px-3 d-inline-block">100% <span class="me-2 fs-5">kursantów</span></h2>
							</div>
							<div class="text-left p-1 bg-dark mx-3 pb-3">
								<small class="m-2 text-white"><i class="fa fa-check text-primary mx-2"></i>poleca AUTO TURBO na Facebooku</small>
							</div>
							<div class="text-left p-0 bg-white mx-2">
								<div class="text-center m-0 p-0">
									<div class="bg-white" style="border: 3px solid #ff6400; border-radius: 7px; width: 100%; display: inline-block; margin-top: -10px;">
										<img class="img-fluid" style="border-radius: 15px; width: 100%; height: auto;" src="/img/opinie/4.png" alt="">
									</div>
								</div>
							</div>
						</a>
					</div>
				</div>








		   </div>
		   
		   <!----------------------------------- koniec cen kursów ---------------------------------->

			