	
            <div class="row g-4 justify-content-center">	
									

				<div class="col-lg-3 col-sm-6">
					<div class="course-item h-100">
						<a href="https://www.superprawojazdy.pl/osk-auto-turbo,9598.htm" class="w-100 m-0 p-0">
							<div class="text-left" style="margin-bottom: -20px; position: relative; z-index: 1;">
								<h2 class="mb-0 text-white bg-primary px-3 d-inline-block" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%;">I miejsce</h2>
							</div>
							<div class="text-left px-2 bg-dark mx-3 pt-4 pb-5">
								<small class="text-white fs-6">w ogólnopolskim rankingu</small>
							</div>
							<div class="bg-white overflow-hidden" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%; display: inline-block; margin-top: -40px; z-index: 2;">
								<img class="img-fluid" style="border-radius: 7px; width: 100%; height: auto;" src="/img/opinie/1.svg" alt="">
							</div>
						</a>
					</div>
				</div>
				
				<div class="col-lg-3 col-sm-6">
					<div class="d-none d-md-block">
						<div class="course-item h-100">
							<a href="https://www.prawo-jazdy-360.pl/ranking-szkol-jazdy/osrodek-szkolenia-kierowcow-auto-turbo-grzegorz-palasz/rzeszow" class="w-100 m-0 p-0">
								<div class="text-left" style="margin-bottom: -20px; position: relative; z-index: 1;">
									<h2 class="mb-0 text-white bg-primary px-3 d-inline-block" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%;">II miejsce</h2>
								</div>
								<div class="text-left px-2 bg-dark mx-3 pt-4 pb-5">
									<small class="text-white fs-6">w ogólnopolskim rankingu</small>
								</div>
								<div class="bg-white overflow-hidden" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%; display: inline-block; margin-top: -40px; z-index: 2;">
									<img class="img-fluid" style="border-radius: 7px; width: 100%; height: auto;" src="/img/opinie/2.svg" alt="">
								</div>
							</a>
						</div>
					</div>
				</div>
				
				<div class="col-lg-3 col-sm-6">
						<div class="course-item h-100">
							<a href="https://g.co/kgs/QFkZTSm" class="w-100 m-0 p-0">
								<div class="text-left" style="margin-bottom: -20px; position: relative; z-index: 1;">
									<h2 class="mb-0 text-white bg-primary px-3 d-inline-block" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%;">4,9 
										<i class="fa fa-star text-white fs-6"></i>
										<i class="fa fa-star text-white fs-6"></i>
										<i class="fa fa-star text-white fs-6"></i>
										<i class="fa fa-star text-white fs-6"></i>
										<i class="fa fa-star text-white fs-6"></i>
									</h2>
								</div>
								<div class="text-left px-2 bg-dark mx-3 pt-4 pb-5">
									<small class="text-white fs-6">bardzo wysokie oceny</small>
								</div>
								<div class="bg-white overflow-hidden" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%; display: inline-block; margin-top: -40px; z-index: 2;">
									<img class="img-fluid" style="border-radius: 7px; width: 100%; height: auto;" src="/img/opinie/3.svg" alt="">
								</div>
							</a>
						</div>
				</div>

				<div class="col-lg-3 col-sm-6">
					<div class="d-none d-md-block">
						<div class="course-item h-100">
							<a href="https://www.facebook.com/prawojazdyautoturbo" class="w-100 m-0 p-0">
								<div class="text-left" style="margin-bottom: -20px; position: relative; z-index: 1;">
									<h2 class="mb-0 text-white bg-primary px-3 d-inline-block" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%;">100% <span class="me-2 fs-5">kursantów</span></h2>
								</div>
								<div class="text-left px-2 bg-dark mx-3 pt-4 pb-5">
									<small class="text-white fs-6">poleca AUTO TURBO</small>
								</div>
								<div class="bg-white overflow-hidden" style="border: 3px solid #ff6400; border-radius: 7px; width: 80%; display: inline-block; margin-top: -40px; z-index: 2;">
									<img class="img-fluid" style="border-radius: 7px; width: 100%; height: auto;" src="/img/opinie/4.svg" alt="">
								</div>
							</a>
						</div>
					</div>
				</div>

		   </div>



			