<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="120" height="600" id="baner_sps_pion" />
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="/img/layout/baner_sps_pion.swf" />
<param name="quality" value="high" />
<param name="bgcolor" value="#ffffff" />
<embed src="/img/layout/baner_sps_pion.swf"
       quality="high"
       bgcolor="#ffffff"
       width="120"
       height="600"
       name="baner_sps_pion"
       align="middle"
       allowScriptAccess="sameDomain"
       type="application/x-shockwave-flash"
       pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>