<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                    <h1 class="mb-5">Nasi instruktorzy</h1>
                </div>

    			<div class="owl-carousel testimonial-carousel position-relative">
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Grzegorz_Pałasz.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Grzegorz Pałasz</h5>
    									<small>Instruktor/Wykładowca</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Damian_Zamorski.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Damian Zamorski</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				<div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Mieczysław_Błądziński.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Mieczysław Błądziński</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Janusz_Froń.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Janusz Froń</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Rafał_Jaroń.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Rafał Jaroń</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Bogdan_Szewczyk.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Bogdan Szewczyk</h5>
    									<small>Instruktor</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div><div class="testimonial-item text-center">
    					<div class="wow zoomIn" data-wow-delay="0.1s">
    						<div class="team-item bg-light">
                                <a class="position-relative d-block overflow-hidden" href="">
                                    <div class="overflow-hidden">
    									<img class="img-fluid" src="/img/auto_turbo_instruktorzy/auto_turbo_instruktorzy_index/AUTO_TURBO_Piotr_Sowa.jpg" alt="">
    								</div>
    								<div class="text-center p-4">
    									<h5 class="mb-0">Piotr Sowa</h5>
    									<small>Ratownik medyczny</small>
    								</div>
                                </a>
                            </div>
    					</div>
                    </div>
    				
    			</div>
    			