			
                <div class="row g-5">
				
                    <div class="col-lg-6" style="min-height: 400px;">
                        <div class="position-relative h-100">
                            <img class="img-fluid position-absolute w-100 h-100" src="/img/galeria/auto_turbo_plac_manewrowy.jpg" alt="" style="object-fit: cover;">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <h6 class="section-title bg-white text-start text-primary pe-3">Szkolenie</h6>
                        <h1 class="mb-4">Praktyka</h1>
                        <p class="mb-4"><b>Po ukończeniu zajęć teoretycznych</b> (7 spotkań, około 2 tygodnie) uczestnik kursu rozpoczyna <b>zajęcia praktyczne</b>.</p>
                        <p class="mb-4">Na zajęcia praktyczne (jazdy) umawiamy się z kursantami indywidualnie:</p>
                        <div class="row gy-4 gx-8 mb-0">
                            <div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>codziennie: od poniedziałku do soboty</p>
                            </div>
                            <div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>w godz. 7.00 - 21.00</p>
                            </div>
    						<div class="col-sm-12">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>wszystkie jazdy rozpoczynają i kończą się z parkingu przed OSK AUTO TURBO przy ul. Bardowskiego</p>
                            </div>
                        </div>
                    </div>
                </div>
            