                <div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Szkolenie</h6>
                    <h1 class="mb-5">Teoretyczne</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
    			<p class="mb-0 border-bottom">Zajęcia teoretyczne odbywają się cyklicznie w <b>poniedziałki</b>, <b>środy</b> i <b>czwartki</b> o godz. <b>17.00</b> w siedzibie naszej szkoły (Rzeszów, ul. Bardowskiego 1C, I piętro nad barberem).</p>
    			<p class="mb-0">Całość teorii podzielona jest na siedem bloków temetycznych:</p>
    	
    			
    			<div class="row g-4 justify-content-left">
    			
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 1.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Wiadomości ogólne</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Ustawa i rozporządzenia</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Uprawnienia kat. B – dokumenty</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Podstawowe pojęcia</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Prędkość i hamowanie</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przejazdy kolejowe</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zachowanie się wobec pieszych</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 2.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Znaki i drogowe – ustawienie i znaczenie</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki ostrzegawcze</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki zakazu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki nakazu</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki informacyjne</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Znaki poziome</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 3.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Manewry na drodze </h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Włączanie się do ruchu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wymijanie, omijanie, cofanie</p> 
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zmiana kierunku jazdy i pasa ruchu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Wyprzedzanie </p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zawracanie</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 4.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Skrzyżowania</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Przecinanie kierunków ruchu </p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu okrężnym</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Skrzyżowania o ruchu kierowanym </p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 5.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Przepisy szczegółowe</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zatrzymanie i postój</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Awaria pojazdu</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Holowanie</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Kolizja – wypadek</p>
									<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Obowiązkowe wyposażenie pojazdu</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 6.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Zasady egzaminu państwowego</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>Egzamin teoretyczny</p>
    								<p class="mb-0"><i class="fa fa-arrow-right text-primary me-2 ms-4"></i>Egzamin praktyczny</p>
    							</div>
                        </div>
                    </div>
    				
    				<div class="col-lg-3 col-sm-6">
    					<div class="course-item bg-light d-flex flex-column h-100">
                            <div class="text-center p-4 pb-1 bg-dark">
    							<div class="flex-fill text-center py-2 px-3">
    								<h5 class="text-white">Blok tematyczny nr 7.</h5>
    							</div>
    						</div>
    						<div class="text-letf p-4 pb-0 border-bottom py-2">
    							<h6 class="text-dark">Pierwsza pomoc z ratownikiem medycznym</h6>
                            </div>						
    							<div class="text-left py-2 px-4 pb-10">
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Szkolenie teoretyczne</p>
    								<p class="mb-0"><i class="fa fa-check text-primary me-2"></i>Zajęcia praktyczne</p>
    							</div>
                        </div>

                    </div>
    				
    
    
    		   </div>
    		   
    		   
    			
    			</div>
    		