<html>
    <head>
        <style>
            /*! normalize.css 2011-11-04T15:38 UTC - http://github.com/necolas/normalize.css */

            /* =============================================================================
               HTML5 display definitions
               ========================================================================== */

            /*
             * Corrects block display not defined in IE6/7/8/9 & FF3
            */

            article,
            aside,
            details,
            figcaption,
            figure,
            footer,
            header,
            hgroup,
            nav,
            section {
                display: block;
            }

            /*
             * Corrects inline-block display not defined in IE6/7/8/9 & FF3
            */

            audio,
            canvas,
            video {
                display: inline-block;
                *display: inline;
                *zoom: 1;
            }

            /*
             * Prevents modern browsers from displaying 'audio' without controls
            */

            audio:not([controls]) {
                display: none;
            }

            /*
             * Addresses styling for 'hidden' attribute not present in IE7/8/9, FF3, S4
             * Known issue: no IE6 support
            */

            [hidden] {
                display: none;
            }


            /* =============================================================================
               Base
               ========================================================================== */

            /*
             * 1. Corrects text resizing oddly in IE6/7 when body font-size is set using em units
             *    http://clagnut.com/blog/348/#c790
             * 2. Keeps page centred in all browsers regardless of content height
             * 3. Prevents iOS text size adjust after orientation change, without disabling user zoom
             *    www.456bereastreet.com/archive/201012/controlling_text_size_in_safari_for_ios_without_disabling_user_zoom/
            */

            html {
                font-size: 100%; /* 1 */
                overflow-y: scroll; /* 2 */
                -webkit-text-size-adjust: 100%; /* 3 */
                -ms-text-size-adjust: 100%; /* 3 */
            }

            /*
             * Addresses margins handled incorrectly in IE6/7
            */

            body {
                margin: 0;
            }

            /* 
             * Addresses font-family inconsistency between 'textarea' and other form elements.
            */

            body,
            button,
            input,
            select,
            textarea {
                font-family: sans-serif;
            }


            /* =============================================================================
               Links
               ========================================================================== */

            /*
             * Addresses outline displayed oddly in Chrome
            */

            a:focus {
                outline: thin dotted;
            }

            /*
             * Improves readability when focused and also mouse hovered in all browsers
             * people.opera.com/patrickl/experiments/keyboard/test
            */

            a:hover,
            a:active {
                outline: 0;
            }


            /* =============================================================================
               Typography
               ========================================================================== */

            /*
             * Neutralise smaller font-size in 'section' and 'article' in FF4+, Chrome, S5
            */

            h1 {
                font-size: 2em;
            }

            /*
             * Addresses styling not present in IE7/8/9, S5, Chrome
            */

            abbr[title] {
                border-bottom: 1px dotted;
            }

            /*
             * Addresses style set to 'bolder' in FF3+, S4/5, Chrome
            */

            b, 
            strong { 
                font-weight: bold; 
            }

            blockquote {
                margin: 1em 40px;
                font-style: italic;
            }

            /*
             * Addresses styling not present in S5, Chrome
            */

            dfn {
                font-style: italic;
            }

            /*
             * Addresses styling not present in IE6/7/8/9
            */

            mark {
                background: #ff0;
                color: #000;
            }

            /*
             * Corrects font family set oddly in IE6, S4/5, Chrome
             * en.wikipedia.org/wiki/User:Davidgothberg/Test59
            */

            pre,
            code,
            kbd,
            samp {
                font-family: monospace, serif;
                _font-family: 'courier new', monospace;
                font-size: 1em;
            }

            /*
             * Improves readability of pre-formatted text in all browsers
            */

            pre {
                white-space: pre;
                white-space: pre-wrap;
                word-wrap: break-word;
            }

            /*
             * 1. Addresses CSS quotes not supported in IE6/7
             * 2. Addresses quote property not supported in S4
            */

            /* 1 */

            q {
                quotes: none;
            }

            /* 2 */

            q:before,
            q:after {
                content: '';
                content: none;
            }

            small {
                font-size: 75%;
            }

            /*
             * Prevents sub and sup affecting line-height in all browsers
             * gist.github.com/413930
            */

            sub,
            sup {
                font-size: 75%;
                line-height: 0;
                position: relative;
                vertical-align: baseline;
            }

            sup {
                top: -0.5em;
            }

            sub {
                bottom: -0.25em;
            }


            /* =============================================================================
               Lists
               ========================================================================== */

            ul,
            ol {
                margin-left: 0;
                padding: 0 0 0 40px;
            }

            dd {
                margin: 0 0 0 40px;
            }

            nav ul,
            nav ol {
                list-style: none;
                list-style-image: none;
            }


            /* =============================================================================
               Embedded content
               ========================================================================== */

            /*
             * 1. Removes border when inside 'a' element in IE6/7/8/9, FF3
             * 2. Improves image quality when scaled in IE7
             *    code.flickr.com/blog/2008/11/12/on-ui-quality-the-little-things-client-side-image-resizing/
            */

            img {
                border: 0; /* 1 */
                -ms-interpolation-mode: bicubic; /* 2 */
            }

            /*
             * Corrects overflow displayed oddly in IE9 
            */

            svg:not(:root) {
                overflow: hidden;
            }


            /* =============================================================================
               Figures
               ========================================================================== */

            /*
             * Addresses margin not present in IE6/7/8/9, S5, O11
            */

            figure {
                margin: 0;
            }


            /* =============================================================================
               Forms
               ========================================================================== */

            /*
             * Corrects margin displayed oddly in IE6/7
            */

            form {
                margin: 0;
            }

            /*
             * Define consistent border, margin, and padding
            */

            fieldset {
                border: 1px solid #c0c0c0;
                margin: 0 2px;
                padding: 0.35em 0.625em 0.75em;
            }

            /*
             * 1. Corrects color not being inherited in IE6/7/8/9
             * 2. Corrects alignment displayed oddly in IE6/7
            */

            legend {
                border: 0; /* 1 */
                *margin-left: -7px; /* 2 */
            }

            /*
             * 1. Corrects font size not being inherited in all browsers
             * 2. Addresses margins set differently in IE6/7, FF3+, S5, Chrome
             * 3. Improves appearance and consistency in all browsers
            */

            button,
            input,
            select,
            textarea {
                font-size: 100%; /* 1 */
                margin: 0; /* 2 */
                vertical-align: baseline; /* 3 */
                *vertical-align: middle; /* 3 */
            }

            /*
             * Addresses FF3/4 setting line-height on 'input' using !important in the UA stylesheet
            */

            button,
            input {
                line-height: normal; /* 1 */
            }

            /*
             * 1. Improves usability and consistency of cursor style between image-type 'input' and others
             * 2. Corrects inability to style clickable 'input' types in iOS
             * 3. Removes inner spacing in IE7 without affecting normal text inputs
             *    Known issue: inner spacing remains in IE6
            */

            button,
            input[type="button"], 
            input[type="reset"], 
            input[type="submit"] {
                cursor: pointer; /* 1 */
                -webkit-appearance: button; /* 2 */
                *overflow: visible;  /* 3 */
            }

            /*
             * 1. Addresses box sizing set to content-box in IE8/9
             * 2. Removes excess padding in IE8/9
            */

            input[type="checkbox"],
            input[type="radio"] {
                box-sizing: border-box; /* 1 */
                padding: 0; /* 2 */
            }

            /*
             * 1. Addresses appearance set to searchfield in S5, Chrome
             * 2. Addresses box-sizing set to border-box in S5, Chrome (include -moz to future-proof)
            */

            input[type="search"] {
                -webkit-appearance: textfield; /* 1 */
                -moz-box-sizing: content-box;
                -webkit-box-sizing: content-box; /* 2 */
                box-sizing: content-box;
            }

            /*
             * Removes inner padding that is displayed in S5, Chrome on OS X
            */

            input[type="search"]::-webkit-search-decoration {
                -webkit-appearance: none;
            }

            /*
             * Removes inner padding and border in FF3+
             * www.sitepen.com/blog/2008/05/14/the-devils-in-the-details-fixing-dojos-toolbar-buttons/
            */

            button::-moz-focus-inner,
            input::-moz-focus-inner {
                border: 0;
                padding: 0;
            }

            /*
             * 1. Removes default vertical scrollbar in IE6/7/8/9
             * 2. Improves readability and alignment in all browsers
            */

            textarea {
                overflow: auto; /* 1 */
                vertical-align: top; /* 2 */
            }


            /* =============================================================================
               Tables
               ========================================================================== */

            /* 
             * Remove most spacing between table cells
            */
            html,body{
                z-index: 99;
            }
            #styles{
                background-color: white;
                background-image: url('../img/layout/listheader.gif');
                right: 0;
                width: 130px;
                left: 0;
                z-index: 100;

            }
            #styles{
                position: fixed;
                top: 0px;
            }
            #styles ul{
                color: black;
                list-style-type: none;
                padding-left: 3px;
                margin: 0;
                font-family:arial;
                font-size:0.4cm;
            }
            #styles ul li{
                display:inline;
                padding:0px 5px;
            }
            #styles ul li:hover{
                color:red;
                cursor:pointer;
                font-weight:bold;
            }

            a:link,   a:visited {
                -text-decoration: none;
                -display: block;
                color: #000;
                padding: 1px 7px ;
                cursor: pointer;
            }

            a:hover {
                -text-decoration:underline;
                text-decoration: none;
                -color:#0099CC;
                color:#1144ff;
            }
            #right a{
                color: #000;

            }
            #right a:hover{
                color:#fff;
            }
            #tresc{
                padding: 10px;
            }
        </style>
    </head>
    <body>
        <div id="tresc">
            <h1>
                Szanowni Państwo,
            </h1>

            <p>
                Dziękujemy za dokonanie zapisu on-line na naszej stronie internetowej: <b>www.oskautoturbo.pl</b>
            </p> 

            <p>
                Przed rozpoczęciem zajęć teoretycznych uczestnik kursu powinien złożyć w biurze naszego ośrodka następujące dokumenty: 
            </p> 
            <ul>
                <li style="padding:5px"><b>Zdjęcie</b> do prawa jazdy o wymiarach 3,5 x 4,5 cm</li>
                <li style="padding:5px">dokument stwierdzający tożsamość osoby szkolonej: <b>dowód osobisty</b>, paszport lub kartę stałego pobytu (do wglądu), lub legitymację szkolną w przypadku osób, które nie ukończyły 18 roku życia</li>
                <li style="padding:5px"><b>pisemną zgodę rodziców</b> lub opiekunów prawnych, jeżeli osoba szkolona rozpoczyna szkolenie przed ukończeniem 18-tego roku życia (druk zgody rodziców lub opiekunów prawnych jest dostępny w biurze OSK Auto Turbo)</li>
                <li style="padding:5px"><b>oryginał orzeczenia lekarskiego</b> stwierdzającego brak przeciwwskazań zdrowotnych do kierowania pojazdami określonej kategorii (jeżeli był wcześniej wydany, jeżeli nie można badania lekarskie wykonać na miejscu w naszym ośrodku)</li>
                <li style="padding:5px"><b>wypełniony wniosek o wydanie prawa jazdy</b> – wniosek dostępny jest w biurze OSK Auto Turbo (można go wypełnić na miejscu)</li>
                <li style="padding:5px">
                    <b>dowód wpłaty</b> za określony rodzaj szkolenia, opłata może zostać dokonana za pośrednictwem przelewu bankowego na konto naszego ośrodka:
                    <p>

                    </p>

                    <table border="1">
                        <tr>
                            <td colspan="2">
                                Dane do przelewu:
                            </td>
                        </tr>
                        <tr>
                            <td>Nazwa:</td>
                            <td>
                                Ośrodek Szkolenia Kierowców "Auto Turbo"
                                </br>Grzegorz Pałasz
                            </td>
                        </tr>
                        <tr>
                            <td>Adres:</td>
                            <td> 35-005 Rzeszów</br>
                                ul. BArdowskiego 4</td>
                        </tr>
                        <tr>
                            <td>Numer konta:</td>
                            <td>Idea Bank S.A.</br>
                                51 1950 0001 2006 0263 1600 0002</td>
                        </tr>
                        <tr>
                            <td>Tytuł przelewu:</td>
                            <td>opłata za kurs prawa jazdy kat. B, szkolenie podstawowe (rozszerzone), rata 1 (jesli system ratalny) </td>
                        </tr>
                    </table>

                </li>
            </ul>

            <p>
                Więcej informacji można uzyskać:
            <ul>
                <li style="padding:5px">w biurze naszego ośrodka (Rzeszów, ul. Bardowskiego 4 (I pietro, nad delikatesami "Jabłuszko"))</li>
                <li style="padding:5px">pod numerami telefonów: 
                    <ul>
                        <li>693 776 163,</li>
                        <li>605 330 708.</li>
                    </ul> 
                </li>
                <li style="padding:5px">lub drogą malową: oskautoturbo@gmail.com</li>
           </ul>
            </p>

        <p>
            Pozdrawiamy 
        </p>
        <p>
            Ośrodek Szkolenia Kierowców "Auto Turbo"
        </p>
    </div>
</body>
</html>
