                <div class="text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Zapisy</h6>
                    <h1 class="mb-5">Jak rozpocząć kurs?</h1>
                </div>
    			
                <div class="row g-4 justify-content-center">
    			
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-0 pt-2 bg-primary">
							<div class="flex-fill text-center">
								<h1 class="btn btn-outline-light rounded-circle px-4 py-1 border-4 fs-1 hover-primary"> 1</h1>
							</div>
						</div>
						<div class="text-center p-2 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Zapis na kurs</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-3 pb-10">
    						<p class="mb-0 border-bottom">Na kurs prawa jazdy można zapisać się na kilka sposobów:</p>
    						<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i>Formularz zgłoszeniowy</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="/zapisynakurs" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Zapisz się</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-map-marker-alt text-primary me-2"></i>Osobiście</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="/kontakt" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Rzeszów, Bardowskiego 1C</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-phone text-primary me-2"></i>Telefonicznie</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="tel:+48605330708" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">605330708</a></small>
    						</div>
    					</div>	
						
						
                    </div>
                </div>
				
				
				<div class="col-lg-3 col-sm-6" id="jak_rozpoczac_2">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-0 pt-2 bg-primary">
							<div class="flex-fill text-center">
								<h1 class="btn btn-outline-light rounded-circle px-4 py-1 border-4 fs-1 hover-primary">2</h1>
							</div>
						</div>
						<div class="text-center p-2 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Dokumenty</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom">Będą potrzebne następujące dokumenty:</p>
    						<p class="mb-0"><i class="fa fa-file-alt text-primary me-2"></i><b>Wniosek o wydanie prawa jazdy</b> 
							<small>(dostępny również w ośrodku)</small>
							</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="../doci/2025_wniosek.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
    						</div>
    						<p class="mb-0"><i class="fa fa-file-medical text-primary me-2"></i><b>Orzeczenie lekarskie</b> <small>stwierdzające brak przeciwwskazań zdrowotnych do kierowania pojazdami (badania można zrobić w OSK Auto Turbo)</small>
							</p>
    						<p class="mb-0 border-top"><i class="fa fa-id-badge text-primary me-2"></i><b>Zdjęcie</b>
							<small>(aktualne, kolorowe) do prawa jazdy o wymiarach 3,5 x 4,5 cm</small>
							</p>
    						<p class="mb-0 border-top"><i class="fa fa-file-signature text-primary me-2"></i><b>Zgoda rodziców</b>
							<small>dotyczy osób przed ukończeniem 18-tego roku życia</small> 
							<small>(dostepna również w ośrodku)</small>
							</p>
    						<div class="d-flex border-bottom">
    							<small class="flex-fill text-center py-2"><a href="../doci/2025_zgoda.pdf" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px 30px 30px 30px;">Pobierz</a></small>
    						</div>
    						
    					</div>			
                    </div>
                </div>
				
				
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-0 pt-2 bg-primary">
							<div class="flex-fill text-center">
								<h1 class="btn btn-outline-light rounded-circle px-4 py-1 border-4 fs-1 hover-primary">3</h1>
							</div>
						</div>
						<div class="text-center p-2 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Założenie PKK</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom">PKK jest to numer, który zakłada się w <b>Wydziale Komunikacji</b> odpowiednim dla miejsca zameldowania</p>
    						<p class="mb-0 border-bottom">Aby go uzyskać należy złożyć w urzędzie przygotowane wcześniej <b>dokumenty</b> <a href="/#jak_rozpoczac_2">(patrz pkt. 2.)</a></p>
    					</div>		
                    </div>
                </div>
				
    			
				<div class="col-lg-3 col-sm-6">
					<div class="course-item bg-light d-flex flex-column h-100">
                        <div class="text-center p-0 pt-2 bg-primary">
							<div class="flex-fill text-center">
								<h1 class="btn btn-outline-light rounded-circle px-4 py-1 border-4 fs-1 hover-primary">4</h1>
							</div>
						</div>
						<div class="text-center p-2 pb-0">
    						<div class="flex-fill text-center border-bottom py-2">
    							<h4 class="mb-2">Przekazanie PKK </br>do AUTO TURBO</h4>
    						</div>
    					</div>
    					<div class="text-left py-2 px-4 pb-10">
    						<p class="mb-0 border-bottom"><b>Po odbiorze numeru PKK</b> z Wydziału Komunikacji należy go przekazać <b>do biura OSK AUTO TURBO</b> lub przesłać SMS</p>
    					</div>		
                    </div>
                </div>
				    			   
    			
    			</div>
    		