                    <form method="post">
                        <div class="row g-3">
                            <div class="col-12">
                                <div class="form-floating">
									<?php $imie = $this->element->imie->getValue(); ?>
                                    <input type="text" class="form-control" id="imie" name="imie" placeholder="Imię"
									value="<?php echo htmlspecialchars($imie) ?>">
                                    <label for="imie">Imię</label>
									<?php if ($this->element->imie->hasErrors()): ?>
									<div class="error">
									<?php echo $this->formErrors($this->element->imie->getMessages()); ?>
									</div>
									<?php endif; ?>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
								    <?php $nazwisko = $this->element->nazwisko->getValue(); ?>
                                    <input type="text" class="form-control" id="nazwisko" name="nazwisko" placeholder="Nazwisko" 
									value="<?php echo htmlspecialchars($nazwisko) ?>">
                                    <label for="nazwisko">Nazwisko</label>
									<?php if ($this->element->nazwisko->hasErrors()): ?>
									<div class="error">
									<?php echo $this->formErrors($this->element->nazwisko->getMessages()); ?>
									</div>
									<?php endif; ?>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
								    <?php $telefon = $this->element->telefon->getValue(); ?>
                                    <input type="text" class="form-control" id="telefon" name="telefon" placeholder="Telefon" 
									value="<?php echo htmlspecialchars($telefon) ?>">
                                    <label for="telefon">Telefon</label>
									<?php if ($this->element->telefon->hasErrors()): ?>
									<div class="error">
									<?php echo $this->formErrors($this->element->telefon->getMessages()); ?>
									</div>
									<?php endif; ?>
                                </div>
                            </div>
							
							<div class="col-12">
                                <div class="form-floating">
									<?php $email = $this->element->email->getValue(); ?>
                                    <input type="text" class="form-control" id="email" name="email" placeholder="E-mail"
									value="<?php echo htmlspecialchars($email) ?>">
                                    <label for="email">E-mail</label>
									<?php if ($this->element->email->hasErrors()): ?>
									<div class="error">
									<?php echo $this->formErrors($this->element->email->getMessages()); ?>
									</div>
									<?php endif; ?>
                                </div>
                            </div>

							<div class="col-12">
								<div class="form-floating">
								  <select class="form-select" id="rodzaj_kursu" name="rodzaj_kursu" required>
									<option selected disabled hidden value="">Wybierz rodzaj</option>
									<option value="0">Kurs prawa jazdy kat. B</option>
									<option value="1">Jazdy doszkalające</option>
									<option value="2">Pytanie</option>
								  </select>
								</div>
							</div>

                            <div class="col-12">
                                <div class="form-floating">
									<?php $uwagi = $this->element->uwagi->getValue(); ?>
                                    <textarea class="form-control" placeholder="Leave a message here" id="uwagi" name="uwagi" style="height: 100px"><?php echo htmlspecialchars($uwagi) ?></textarea>
                                    <label for="uwagi">Dodatkowe informacje (opcjonalnie)</label>
                                </div>
                            </div>
							<div class="col-12">
                                <div class="form-floating">
								
                                    <?php if(isset($this->element->txt_captcha)) {
										echo $this->element->txt_captcha->render();
										}else{
											echo APPLICATION_ENV;
										}
										?>
                                </div>
                            </div>
						
							
							
                            <div class="col-12">
							
							    <input type="submit" class="btn btn-primary w-100 py-3" id="zapisz" value="Zapisz się">
                                <!-- <button class="btn btn-primary w-100 py-3" type="submit">Zapisz się</button> -->
                            </div>
                        </div>
                    </form>