[production]

phpSettings.display_startup_errors = 1 
phpSettings.display_errors = 1
includePaths.library = APPLICATION_PATH "/../library"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
appnamespace = "Application"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
;resources.frontController.baseUrl = "/public"
resources.frontController.params.displayExceptions = 0
resources.layout.layoutPath = APPLICATION_PATH "/views/layouts" 
resources.frontController.plugins.acl = Application_Plugin_Acl
; domyślny moduł

autoloaderNamespaces[] = "Plugins"
autoloaderNamespaces[] = "Doctrine"
autoloaderNamespaces[] = "My"
autoloaderNamespaces[] = "Turbo"

resources.view[] =
pluginPaths.ZendX_Application_Resource_ = "ZendX/Application/Resource"
resources.jquery.localpath = "http://code.jquery.com/jquery-1.7.1.min.js"
resources.jquery.stylesheet = "http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css"
resources.jquery.uilocalpath = "http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"
 
;mwrons.phpnet.us
;doctrine.dsn = "mysql://pn_9351909:eenius12@sql309.phpnet.us/pn_9351909_turbo"

;mwrons.freeiz.com
;doctrine.dsn = "mysql://a7735137_turbo:franek12@mysql15.000webhost.com/a7735137_turbo" 

;mwrons.laohost.pl
;doctrine.dsn = "mysql://franek_osk:fckgw35@localhost/franek_osk"   
 
;mwrons.hekko.pl
doctrine.dsn = "mysql://franek_osk:fckgw35@localhost/franek_osk"   

doctrine.data_fixtures_path = APPLICATION_PATH "/../doctrine/data/fixtures"
doctrine.models_path = APPLICATION_PATH "/models"
doctrine.migrations_path = APPLICATION_PATH "/../doctrine/migrations"
doctrine.sql_path = APPLICATION_PATH "/../doctrine/data/sql"
doctrine.yaml_schema_path = APPLICATION_PATH "/../doctrine/schema"
doctrine.yaml_schema_all_path = APPLICATION_PATH "/../doctrine/schema_all"

doctrine.generate_models_options.pearStyle = true
doctrine.generate_models_options.generateTableClasses = true
doctrine.generate_models_options.generateBaseClasses = true
doctrine.generate_models_options.baseClassPrefix = "Base_"
doctrine.generate_models_options.baseClassesDirectory =
doctrine.generate_models_options.classPrefixFiles = false
doctrine.generate_models_options.classPrefix = "Application_Model_"

path.images            = ../public/img/
path.pdf               = ../public/doci/
resources.modules = "" 
resources.frontController.moduleDirectory = APPLICATION_PATH "/modules"
;mwrons.phpnet.us
;app.www.prefix = mwrons.phpnet.us
;mwrons.freeiz.com
app.www.prefix = mwrons.freeiz.com
app.admin.prefix = admin.marcoss.phpnet.us


[staging : production]



[development : production]
;phpSettings.display_startup_errors = 1
;phpSettings.display_errors = 1
;resources.frontController.params.displayExceptions = 1
;doctrine.dsn = "mysql://admin:admin@localhost/franek_osk"
;app.www.prefix = autoturbo.pl

[testing : development]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1

